package model

import (
	"fmt"
	"strings"
	"unicode"
)

// BuildArtifact wraps a tracked Operation's response tree into an *Artifact and
// resolves its SDK call bindings. It sets Name/Kind/SourceFile/Schema and the
// data-source SDK calls (Lifecycle.Read for by-id, Lifecycle.Search for the list
// call) plus Lifecycle.IdStrategy. The request side (Create/Update/Delete,
// GoRequestType) stays empty.
//
// A singular data source resolves its one record three ways, selected by which
// group operations are declared: read only (by-id, the original behavior),
// search only (find one in a list), or both (by-id when an id is given, else
// search). Plural is unchanged.
func BuildArtifact(op *Operation) (*Artifact, error) {
	if op == nil || op.Tracking == nil {
		return nil, fmt.Errorf("model: BuildArtifact requires a tracked operation")
	}
	if op.Tracking.Cardinality == CardinalityPlural {
		return buildPluralArtifact(op)
	}

	g := op.Tracking.Group
	hasRead := g != nil && g.Read != ""
	hasSearch := g != nil && g.Search != ""
	switch {
	case hasSearch && !hasRead:
		return buildSingularSearchArtifact(op)
	case hasSearch && hasRead:
		return buildSingularBothArtifact(op)
	default:
		// Read-only (group.read) or groupless: resolve the single record by id.
		return buildSingularByIdArtifact(op)
	}
}

// buildSingularByIdArtifact resolves the one record by direct id lookup: its
// Schema is the by-id response tree and Lifecycle.Read the get-by-id call.
func buildSingularByIdArtifact(op *Operation) (*Artifact, error) {
	schema, diags, err := BuildResponseTree(op.ResponseSchema)
	if err != nil {
		return nil, err
	}
	return &Artifact{
		Name:        op.Tracking.ArtifactName,
		Kind:        op.Tracking.ArtifactKind,
		Cardinality: CardinalitySingular,
		Description: op.Tracking.TfDescription,
		Schema:      schema,
		SourceFile:  sourceFileFor(op.Tracking.ArtifactName),
		Lifecycle: &LifecycleBindings{
			Read:       readCall(op),
			IdStrategy: op.Tracking.IdStrategy,
		},
		Diagnostics: diags,
	}, nil
}

// buildSingularSearchArtifact resolves the one record by searching a list: op is
// the list operation itself (group.search names it). The flat record is the list
// element reshaped into a singular {data:{…}} envelope so the by-id envelope
// flattener serves it unchanged; the search side adds Optional filters from the
// query parameters and the list call. No list/items block is emitted.
func buildSingularSearchArtifact(op *Operation) (*Artifact, error) {
	element := listElementSchema(op)
	if element == nil {
		return nil, fmt.Errorf("model: search data source %q has no result-array element to flatten", op.Tracking.ArtifactName)
	}
	record, recDiags, err := BuildResponseTree(singularEnvelope(element))
	if err != nil {
		return nil, err
	}
	filters, diags := buildFilterLeaves(op)
	diags = append(diags, recDiags...)
	return &Artifact{
		Name:        op.Tracking.ArtifactName,
		Kind:        op.Tracking.ArtifactKind,
		Cardinality: CardinalitySingular,
		Description: op.Tracking.TfDescription,
		Schema:      &AttributeTree{Attributes: append(filters, record.Attributes...)},
		SourceFile:  sourceFileFor(op.Tracking.ArtifactName),
		Lifecycle: &LifecycleBindings{
			Search:     listCall(op),
			IdStrategy: op.Tracking.IdStrategy,
		},
		Diagnostics: diags,
	}, nil
}

// buildSingularBothArtifact resolves the one record by id when given one and by
// search otherwise. The flat record is the canonical by-id response tree (the
// same element shape the search returns); the search side adds Optional filters
// from the list op's query parameters and the list call, alongside the by-id Read.
func buildSingularBothArtifact(op *Operation) (*Artifact, error) {
	searchOp := op.SearchOp
	if searchOp == nil {
		return nil, fmt.Errorf("model: data source %q declares group.search %q but no such operation exists",
			op.Tracking.ArtifactName, op.Tracking.Group.Search)
	}

	// When the by-id record shape diverges from the list element shape (e.g.
	// api_key: FullAPIKey vs PartialAPIKey), one state mapper cannot serve both.
	// Degrade to by-id-only (the full shape, id required) and record why.
	if op.ResponseDataRefName != "" && searchOp.ItemRefName != "" &&
		op.ResponseDataRefName != searchOp.ItemRefName {
		art, err := buildSingularByIdArtifact(op)
		if err != nil {
			return nil, err
		}
		art.Diagnostics = append(art.Diagnostics, Diagnostic{
			Severity: SeverityInfo,
			Message: fmt.Sprintf(
				"data source %q: search lookup dropped — by-id record %q diverges from list element %q; generated by-id-only",
				op.Tracking.ArtifactName, op.ResponseDataRefName, searchOp.ItemRefName),
		})
		return art, nil
	}

	record, recDiags, err := BuildResponseTree(op.ResponseSchema)
	if err != nil {
		return nil, err
	}
	filters, diags := buildFilterLeaves(searchOp)
	diags = append(diags, recDiags...)
	return &Artifact{
		Name:        op.Tracking.ArtifactName,
		Kind:        op.Tracking.ArtifactKind,
		Cardinality: CardinalitySingular,
		Description: op.Tracking.TfDescription,
		Schema:      &AttributeTree{Attributes: append(filters, record.Attributes...)},
		SourceFile:  sourceFileFor(op.Tracking.ArtifactName),
		Lifecycle: &LifecycleBindings{
			Read:       readCall(op),
			Search:     listCall(searchOp),
			IdStrategy: op.Tracking.IdStrategy,
		},
		Diagnostics: diags,
	}, nil
}

// sourceFileFor is the output path for a data-source artifact name.
func sourceFileFor(name string) string {
	return "datadog/fwprovider/data_source_datadog_" + name + ".go"
}

// singularEnvelope wraps a list element schema in a one-property {data: element}
// object, mimicking a by-id response so the singular envelope flattener can hoist
// the element's leaves regardless of where the record was fetched.
func singularEnvelope(element *Schema) *Schema {
	return &Schema{
		Kind:       SchemaKindObject,
		Properties: map[string]*Schema{defaultResultsPath: element},
	}
}

// listElementSchema returns the element schema of op's results array
// (op.Pagination.ResultsPath, else "data"), or nil when that property is absent
// or not an array.
func listElementSchema(op *Operation) *Schema {
	resultsPath := defaultResultsPath
	if op.Pagination != nil && op.Pagination.ResultsPath != "" {
		resultsPath = op.Pagination.ResultsPath
	}
	if op.ResponseSchema == nil || op.ResponseSchema.Kind != SchemaKindObject {
		return nil
	}
	arr := op.ResponseSchema.Properties[resultsPath]
	if arr == nil || arr.Kind != SchemaKindArray {
		return nil
	}
	return arr.Items
}

// buildPluralArtifact derives a plural data-source artifact: its Schema is the
// scalar-filter leaves (from the query parameters) followed by the response
// tree, whose single top-level results array the emit builder turns into the
// items block. It records the list-call bindings (item type, optional-params
// type, pagination) and any dropped filters as info Diagnostics.
func buildPluralArtifact(op *Operation) (*Artifact, error) {
	itemsBlock, itemDiags, err := buildItemsBlock(op)
	if err != nil {
		return nil, err
	}
	filters, diags := buildFilterLeaves(op)
	diags = append(diags, itemDiags...)
	attrs := filters
	if itemsBlock != nil {
		attrs = append(attrs, itemsBlock)
	}

	read := listCall(op)
	name := op.Tracking.ArtifactName
	return &Artifact{
		Name:        name,
		Kind:        op.Tracking.ArtifactKind,
		Cardinality: CardinalityPlural,
		Description: op.Tracking.TfDescription,
		Schema:      &AttributeTree{Attributes: attrs},
		SourceFile:  "datadog/fwprovider/data_source_datadog_" + name + ".go",
		Lifecycle: &LifecycleBindings{
			Read:       read,
			IdStrategy: op.Tracking.IdStrategy,
		},
		Diagnostics: diags,
	}, nil
}

// defaultResultsPath is the JSON:API response property holding a list's
// elements, used when no x-pagination resultsPath is declared.
const defaultResultsPath = "data"

// buildItemsBlock builds the plural items block from the results array alone
// (op.Pagination.ResultsPath, else "data"), so response siblings such as
// meta/links/included are dropped rather than emitted. Returns a nil Attribute
// when the response declares no such array, and the drop diagnostics raised
// while building the element.
func buildItemsBlock(op *Operation) (*Attribute, []Diagnostic, error) {
	resultsPath := defaultResultsPath
	if op.Pagination != nil && op.Pagination.ResultsPath != "" {
		resultsPath = op.Pagination.ResultsPath
	}
	if op.ResponseSchema == nil || op.ResponseSchema.Kind != SchemaKindObject {
		return nil, nil, nil
	}
	arr := op.ResponseSchema.Properties[resultsPath]
	if arr == nil {
		return nil, nil, nil
	}
	var diags []Diagnostic
	attr, err := buildAttribute(arr, "response."+resultsPath, nestBlock, &diags)
	return attr, diags, err
}

// readCall resolves the datadog-api-client-go binding for op's read.
func readCall(op *Operation) *SDKCall {
	return &SDKCall{
		GoPackage:      "datadog" + strings.ToUpper(versionSegment(op.Path)),
		GoApiStruct:    tagToClassName(op.Tag) + "Api",
		GoMethod:       op.OperationId,
		GoResponseType: op.ResponseRefName,
	}
}

// listCall resolves the datadog-api-client-go binding for op's list call: the
// base read binding plus the element type, the optional-parameters struct (the
// SDK generates one iff the endpoint declares query parameters — pagination
// params are query parameters), and the pagination flag. Shared by the plural
// path and the singular search path.
func listCall(op *Operation) *SDKCall {
	c := readCall(op)
	c.ItemType = op.ItemRefName
	c.Paginated = op.Pagination != nil
	if len(op.QueryParams) > 0 {
		c.OptionalParamsType = op.OperationId + "OptionalParameters"
	}
	return c
}

// buildFilterLeaves converts op's scalar query parameters into Optional
// top-level filter attributes. Pagination params are excluded (the SDK's
// pagination form handles them); array- and enum-valued params are dropped with
// an info Diagnostic rather than failing the build. The result preserves
// QueryParams' name order.
func buildFilterLeaves(op *Operation) ([]*Attribute, []Diagnostic) {
	var leaves []*Attribute
	var diags []Diagnostic
	for _, p := range op.QueryParams {
		if op.Pagination != nil && (p.Name == op.Pagination.LimitParam || p.Name == op.Pagination.PageParam) {
			continue
		}
		if reason := unsupportedFilterReason(p.Schema); reason != "" {
			diags = append(diags, Diagnostic{
				Severity: SeverityInfo,
				Message:  fmt.Sprintf("dropped query parameter %q from filters: %s", p.Name, reason),
			})
			continue
		}
		tfType, goType, err := FrameworkType(p.Schema)
		if err != nil {
			diags = append(diags, Diagnostic{
				Severity: SeverityInfo,
				Message:  fmt.Sprintf("dropped query parameter %q from filters: %v", p.Name, err),
			})
			continue
		}
		leaves = append(leaves, &Attribute{
			Path:        snakeCase(p.Name),
			TfType:      tfType,
			GoType:      goType,
			Format:      p.Schema.Format,
			Optional:    true,
			Description: p.Description,
		})
	}
	return leaves, diags
}

// unsupportedFilterReason reports why a query parameter cannot become a filter,
// or "" when it can. Array- and enum-valued params are deferred (their SDK
// optional-params field is a slice or named enum type a string filter cannot
// set); everything non-scalar is unsupported.
func unsupportedFilterReason(s *Schema) string {
	if s == nil {
		return "parameter has no schema"
	}
	switch s.Kind {
	case SchemaKindArray:
		return "array-valued query parameters are not supported as filters"
	case SchemaKindPrimitive:
		if len(s.Enum) > 0 {
			return "enum-valued query parameters are not supported as filters"
		}
		return ""
	default:
		return fmt.Sprintf("query parameter kind %q is not supported as a filter", s.Kind)
	}
}

// versionSegment returns the API version path segment immediately after "/api/",
// e.g. "/api/v2/incidents/config/types/{id}" → "v2". It returns "" when the path
// has no segment after "api", leaving the resolved GoPackage incomplete so the
// emit builder fail-slows on it rather than emitting a broken import.
func versionSegment(path string) string {
	segs := strings.Split(strings.Trim(path, "/"), "/")
	for i, s := range segs {
		if s == "api" && i+1 < len(segs) {
			return segs[i+1]
		}
	}
	return ""
}

// tagToClassName converts an OpenAPI tag into the datadog-api-client-go API
// struct base name: non-alphanumeric runs become word breaks, each word is
// capitalized on its first rune, and in-word casing is preserved. So "org
// groups" → "OrgGroups" and "APM" → "APM". This deliberately differs from
// SdkName, which lower-cases acronyms ("APM" → "Apm").
func tagToClassName(tag string) string {
	var b strings.Builder
	for _, word := range strings.FieldsFunc(tag, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsNumber(r)
	}) {
		runes := []rune(word)
		b.WriteRune(unicode.ToUpper(runes[0]))
		b.WriteString(string(runes[1:]))
	}
	return b.String()
}
