changelog:
  exclude:
    labels:
      - changelog/no-changelog
  categories:
    - title: BUGFIXES
      labels:
        - changelog/bufix
    - title: IMPROVEMENTS
      labels:
        - changelog/improvement
    - title: FEATURES
      labels:
        - changelog/feature
    - title: NOTES
      labels:
        - changelog/note
