changelog:
  exclude:
    labels:
      - changelog/no-changelog
  categories:
    - title: BUGFIXES
      labels:
        - changelog/bugfix
        - changelog/fixed
        - changelog/Fixed
    - title: IMPROVEMENTS
      labels:
        - changelog/improvement
        - changelog/changed
        - changelog/Changed
    - title: FEATURES
      labels:
        - changelog/feature
        - changelog/added
        - changelog/Added
    - title: NOTES
      labels:
        - changelog/note
        - changelog/removed
        - changelog/Removed
    - title: DOCUMENTATION
      labels:
        - changelog/documentation
