package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/emit"
	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/model"
)

// generatedMarker is the header comment tfgen stamps on every generated data
// source. retireArtifact refuses to delete a data-source .go file that lacks it,
// so a hand-written file is never removed by a name collision.
const generatedMarker = "Code generated by tfgen"

// testAccFuncRe captures an exported acceptance-test function name in a generated
// _test.go, e.g. "TestAccDatadogTeamDataSource". A recorded cassette uses the
// function name as its file-name prefix.
var testAccFuncRe = regexp.MustCompile(`func (TestAcc[A-Za-z0-9_]+)`)

// artifactNameRe is the safe charset for a Terraform artifact name, identical to
// the tracking-field schema's artifact_name pattern. retireArtifact rejects any
// name failing it before building a filesystem path, so a --retire value (which
// bypasses the schema-validated spec path) or an orphan resolution can never
// traverse (../) or inject path/ref metacharacters.
var artifactNameRe = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// retireArtifact deletes a generated data source's files and registration, gated
// by two checks that both err toward keeping the artifact:
//
//   - marker guard: the .go file must carry the tfgen generated-code marker, so a
//     hand-written data source is never deleted.
//   - cassette gate: a recorded cassette for the artifact's acceptance test means
//     a human adopted it toward release; deleting a published data source is a
//     breaking change, so it is left in place with status retire_blocked.
//
// When both pass it removes the data source .go, its _test.go, its docs page and
// its registration in generatedDatasources, reporting retired. Check mode skips
// the file deletes and the registry write, reporting the status the run would
// produce.
func retireArtifact(name, outputRoot, testsOutputRoot, docsRoot string, check bool) model.ArtifactReportEntry {
	// Fail closed on an unsafe name before any path is built from it: an invalid
	// name deletes nothing.
	if !artifactNameRe.MatchString(name) {
		return failEntry(model.ArtifactReportEntry{Name: name, Kind: model.ArtifactKindDataSource},
			fmt.Errorf("refusing to retire %q: invalid artifact name (must match %s)", name, artifactNameRe.String()))
	}

	goPath := filepath.Join(outputRoot, "data_source_datadog_"+name+".go")
	testPath := filepath.Join(testsOutputRoot, "data_source_datadog_"+name+"_test.go")
	docPath := filepath.Join(docsRoot, name+".md")
	genPath := filepath.Join(outputRoot, "datasources_generated.go")
	cassettesDir := filepath.Join(testsOutputRoot, "cassettes")

	entry := model.ArtifactReportEntry{Name: name, Kind: model.ArtifactKindDataSource, Path: goPath}

	src, err := os.ReadFile(goPath)
	switch {
	case err == nil:
		if !strings.Contains(string(src), generatedMarker) {
			entry.Status = model.ArtifactStatusRetireBlocked
			entry.Diagnostics = []model.Diagnostic{{Severity: model.SeverityWarning,
				Message: fmt.Sprintf("refusing to retire %s: not tfgen-generated (missing the generated-code marker)", goPath)}}
			return entry
		}
	case errors.Is(err, os.ErrNotExist):
		// No source to guard; still clean up any stray test/doc/registration below.
	default:
		return failEntry(entry, err)
	}

	if adopted, cassette := hasRecordedCassette(testPath, cassettesDir); adopted {
		entry.Status = model.ArtifactStatusRetireBlocked
		entry.Diagnostics = []model.Diagnostic{{Severity: model.SeverityWarning,
			Message: fmt.Sprintf("not retiring %q: recorded cassette %q shows it was adopted; needs a manual deprecation cycle", name, cassette)}}
		return entry
	}

	if !check {
		for _, p := range []string{goPath, testPath, docPath} {
			if err := os.Remove(p); err != nil && !errors.Is(err, os.ErrNotExist) {
				return failEntry(entry, err)
			}
		}
	}
	if _, err := emit.RemoveGeneratedDatasource(genPath, emit.DatasourceConstructor(name), check); err != nil {
		return failEntry(entry, err)
	}
	entry.Status = model.ArtifactStatusRetired
	return entry
}

// hasRecordedCassette reports whether a recorded cassette exists for any
// acceptance-test function declared in the generated test file at testPath. A
// cassette file uses its test function as a prefix (recorded variants append a
// suffix), so a prefix match under cassettesDir signals adoption. A missing test
// file or cassettes directory is no adoption signal. The matching cassette name
// is returned for the diagnostic.
func hasRecordedCassette(testPath, cassettesDir string) (bool, string) {
	data, err := os.ReadFile(testPath)
	if err != nil {
		return false, ""
	}
	var funcs []string
	for _, m := range testAccFuncRe.FindAllStringSubmatch(string(data), -1) {
		funcs = append(funcs, m[1])
	}
	if len(funcs) == 0 {
		return false, ""
	}
	entries, err := os.ReadDir(cassettesDir)
	if err != nil {
		return false, ""
	}
	for _, e := range entries {
		for _, fn := range funcs {
			if strings.HasPrefix(e.Name(), fn) {
				return true, e.Name()
			}
		}
	}
	return false, ""
}

// reconcileOrphans retires every generated data source still registered in
// generatedDatasources but no longer produced by this run — its annotation was
// removed from the spec. desired holds the constructors the run registered. Each
// orphan constructor is mapped back to its artifact name through the generated
// files on disk, since the name→constructor transform is not reversible. Returns
// one report entry per orphan.
func reconcileOrphans(outputRoot, testsOutputRoot, docsRoot string, desired map[string]bool, check bool) ([]model.ArtifactReportEntry, error) {
	genPath := filepath.Join(outputRoot, "datasources_generated.go")
	registered, err := emit.RegisteredGeneratedDatasources(genPath)
	if err != nil {
		return nil, err
	}
	ctorToName, err := generatedArtifactNames(outputRoot)
	if err != nil {
		return nil, err
	}

	var entries []model.ArtifactReportEntry
	for _, ctor := range registered {
		if desired[ctor] {
			continue
		}
		name, ok := ctorToName[ctor]
		if !ok {
			// Registered with no marker'd file to name it: drop the stale
			// registration only, since there are no files to delete.
			if _, err := emit.RemoveGeneratedDatasource(genPath, ctor, check); err != nil {
				return entries, err
			}
			entries = append(entries, model.ArtifactReportEntry{
				Name: ctor, Kind: model.ArtifactKindDataSource, Status: model.ArtifactStatusRetired,
				Diagnostics: []model.Diagnostic{{Severity: model.SeverityWarning,
					Message: fmt.Sprintf("registered constructor %q has no generated file; removed the stale registration only", ctor)}},
			})
			continue
		}
		entries = append(entries, retireArtifact(name, outputRoot, testsOutputRoot, docsRoot, check))
	}
	return entries, nil
}

// generatedArtifactNames maps each generated data source's constructor to its
// artifact name by scanning outputRoot for data_source_datadog_*.go files that
// carry the tfgen generated-code marker. Hand-written files are excluded, so an
// orphan constructor only ever resolves to a name whose files are safe to delete.
func generatedArtifactNames(outputRoot string) (map[string]string, error) {
	matches, err := filepath.Glob(filepath.Join(outputRoot, "data_source_datadog_*.go"))
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, path := range matches {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		if !strings.Contains(string(data), generatedMarker) {
			continue
		}
		name := strings.TrimSuffix(strings.TrimPrefix(filepath.Base(path), "data_source_datadog_"), ".go")
		out[emit.DatasourceConstructor(name)] = name
	}
	return out, nil
}
