package cli

import (
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/emit"
	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/model"
)

// artifactFixture lays down the on-disk footprint of one generated data source
// (source, test, doc, registration) under a fresh set of roots, so retirement
// and reconcile can be exercised end-to-end against real files.
type artifactFixture struct {
	outputRoot, testsRoot, docsRoot string
}

func newFixture() *artifactFixture {
	dir := GinkgoT().TempDir()
	f := &artifactFixture{
		outputRoot: filepath.Join(dir, "fwprovider"),
		testsRoot:  filepath.Join(dir, "tests"),
		docsRoot:   filepath.Join(dir, "docs"),
	}
	Expect(os.MkdirAll(f.outputRoot, 0o755)).To(Succeed())
	Expect(os.MkdirAll(filepath.Join(f.testsRoot, "cassettes"), 0o755)).To(Succeed())
	Expect(os.MkdirAll(f.docsRoot, 0o755)).To(Succeed())
	return f
}

// writeArtifact creates the four files for name; generated controls whether the
// .go source carries the tfgen generated-code marker.
func (f *artifactFixture) writeArtifact(name string, generated bool) {
	src := "package fwprovider\n\n"
	if generated {
		src += "// Code generated by tfgen; DO NOT EDIT.\n\n"
	}
	src += "func " + emit.DatasourceConstructor(name) + "() {}\n"
	Expect(os.WriteFile(f.goPath(name), []byte(src), 0o644)).To(Succeed())

	test := "package test\n\nfunc TestAccDatadog" + name + "DataSource(t *testing.T) {}\n"
	Expect(os.WriteFile(f.testPath(name), []byte(test), 0o644)).To(Succeed())

	Expect(os.WriteFile(f.docPath(name), []byte("# "+name), 0o644)).To(Succeed())

	_, err := emit.SyncGeneratedDatasources(f.genPath(), []string{emit.DatasourceConstructor(name)}, false)
	Expect(err).NotTo(HaveOccurred())
}

func (f *artifactFixture) writeCassette(fn string) {
	Expect(os.WriteFile(filepath.Join(f.testsRoot, "cassettes", fn), []byte("x"), 0o644)).To(Succeed())
}

func (f *artifactFixture) goPath(name string) string {
	return filepath.Join(f.outputRoot, "data_source_datadog_"+name+".go")
}
func (f *artifactFixture) testPath(name string) string {
	return filepath.Join(f.testsRoot, "data_source_datadog_"+name+"_test.go")
}
func (f *artifactFixture) docPath(name string) string {
	return filepath.Join(f.docsRoot, name+".md")
}
func (f *artifactFixture) genPath() string {
	return filepath.Join(f.outputRoot, "datasources_generated.go")
}
func (f *artifactFixture) registry() string {
	data, err := os.ReadFile(f.genPath())
	Expect(err).NotTo(HaveOccurred())
	return string(data)
}

func (f *artifactFixture) retire(name string, check bool) model.ArtifactReportEntry {
	return retireArtifact(name, f.outputRoot, f.testsRoot, f.docsRoot, check)
}

var _ = Describe("retireArtifact", func() {
	It("deletes the source, test and doc and removes the registration", func() {
		f := newFixture()
		f.writeArtifact("team", true)

		entry := f.retire("team", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.goPath("team")).NotTo(BeAnExistingFile())
		Expect(f.testPath("team")).NotTo(BeAnExistingFile())
		Expect(f.docPath("team")).NotTo(BeAnExistingFile())
		Expect(f.registry()).NotTo(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("blocks retirement and keeps every file when a recorded cassette adopted it", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		f.writeCassette("TestAccDatadogteamDataSource.yaml")

		entry := f.retire("team", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetireBlocked))
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.testPath("team")).To(BeAnExistingFile())
		Expect(f.docPath("team")).To(BeAnExistingFile())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("blocks retirement of a file that lacks the tfgen generated-code marker", func() {
		f := newFixture()
		f.writeArtifact("team", false)

		entry := f.retire("team", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetireBlocked))
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("matches a cassette recorded under a variant suffix", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		f.writeCassette("TestAccDatadogteamDataSource_AWS_AssumeRole.yaml")

		Expect(f.retire("team", false).Status).To(Equal(model.ArtifactStatusRetireBlocked))
	})

	It("touches nothing on disk in check mode", func() {
		f := newFixture()
		f.writeArtifact("team", true)

		entry := f.retire("team", true)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("fails closed on a traversal name and deletes nothing outside the roots", func() {
		f := newFixture()
		// docPath is filepath.Join(docsRoot, name+".md"), so a "../" name escapes
		// the docs root; this sentinel sits where "../secret" would resolve to.
		sentinel := filepath.Join(filepath.Dir(f.docsRoot), "secret.md")
		Expect(os.WriteFile(sentinel, []byte("keep me"), 0o644)).To(Succeed())

		entry := f.retire("../secret", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusFailed))
		Expect(sentinel).To(BeAnExistingFile())
	})

	It("fails closed on a name carrying path or ref metacharacters", func() {
		f := newFixture()
		for _, bad := range []string{"foo/bar", "foo;rm", "Foo", "foo bar", ".."} {
			Expect(f.retire(bad, false).Status).To(Equal(model.ArtifactStatusFailed),
				"expected %q to be rejected", bad)
		}
	})
})

var _ = Describe("reconcileOrphans", func() {
	It("retires a registered data source no longer in the desired set and keeps the rest", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		f.writeArtifact("zoo", true)
		desired := map[string]bool{emit.DatasourceConstructor("team"): true}

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, desired, false)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(HaveLen(1))
		Expect(entries[0].Name).To(Equal("zoo"))
		Expect(entries[0].Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.goPath("zoo")).NotTo(BeAnExistingFile())
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
		Expect(f.registry()).NotTo(ContainSubstring(emit.DatasourceConstructor("zoo")))
	})

	It("leaves an adopted orphan in place with status retire_blocked", func() {
		f := newFixture()
		f.writeArtifact("zoo", true)
		f.writeCassette("TestAccDatadogzooDataSource.yaml")

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, map[string]bool{}, false)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(HaveLen(1))
		Expect(entries[0].Status).To(Equal(model.ArtifactStatusRetireBlocked))
		Expect(f.goPath("zoo")).To(BeAnExistingFile())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("zoo")))
	})

	It("finds no orphans when every registration is still desired", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		desired := map[string]bool{emit.DatasourceConstructor("team"): true}

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, desired, false)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(BeEmpty())
	})
})
