package cli

import (
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/emit"
	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/model"
)

// artifactFixture lays down the on-disk footprint of one generated data source
// (source, test, doc, example, registration) under a fresh set of roots, so
// retirement and reconcile can be exercised end-to-end against real files.
type artifactFixture struct {
	outputRoot, testsRoot, docsRoot, examplesRoot string
}

func newFixture() *artifactFixture {
	dir := GinkgoT().TempDir()
	f := &artifactFixture{
		outputRoot:   filepath.Join(dir, "fwprovider"),
		testsRoot:    filepath.Join(dir, "tests"),
		docsRoot:     filepath.Join(dir, "docs"),
		examplesRoot: filepath.Join(dir, "examples"),
	}
	Expect(os.MkdirAll(f.outputRoot, 0o755)).To(Succeed())
	Expect(os.MkdirAll(filepath.Join(f.testsRoot, "cassettes"), 0o755)).To(Succeed())
	Expect(os.MkdirAll(f.docsRoot, 0o755)).To(Succeed())
	Expect(os.MkdirAll(f.examplesRoot, 0o755)).To(Succeed())
	return f
}

// writeArtifact creates the artifact files for name; generated controls whether the
// .go source carries the tfgen generated-code marker.
func (f *artifactFixture) writeArtifact(name string, generated bool) {
	src := "package fwprovider\n\n"
	if generated {
		src += "// Code generated by tfgen; DO NOT EDIT.\n\n"
	}
	src += "func " + emit.DatasourceConstructor(name) + "() {}\n"
	Expect(os.WriteFile(f.goPath(name), []byte(src), 0o644)).To(Succeed())

	test := "package test\n\nfunc " + testAccName(name) + "(t *testing.T) {}\n"
	Expect(os.WriteFile(f.testPath(name), []byte(test), 0o644)).To(Succeed())

	Expect(os.WriteFile(f.docPath(name), []byte("# "+name), 0o644)).To(Succeed())
	Expect(os.MkdirAll(filepath.Dir(f.examplePath(name)), 0o755)).To(Succeed())
	Expect(os.WriteFile(f.examplePath(name), []byte("data \"datadog_"+name+"\" \"example\" {}\n"), 0o644)).To(Succeed())

	_, err := emit.SyncGeneratedDatasources(f.genPath(), []string{emit.DatasourceConstructor(name)}, false)
	Expect(err).NotTo(HaveOccurred())
}

// registerOnly wires a constructor into the registry without laying down any of
// its generated files, reproducing a stale registration whose source is gone.
func (f *artifactFixture) registerOnly(name string) {
	_, err := emit.SyncGeneratedDatasources(f.genPath(), []string{emit.DatasourceConstructor(name)}, false)
	Expect(err).NotTo(HaveOccurred())
}

func (f *artifactFixture) writeCassette(fn string) {
	Expect(os.WriteFile(filepath.Join(f.testsRoot, "cassettes", fn), []byte("x"), 0o644)).To(Succeed())
}

func (f *artifactFixture) writeEndpointTags(names ...string) {
	path := f.providerTestPath()
	Expect(os.WriteFile(path, []byte("package test\n\nvar testFiles2EndpointTags = map[string]string{\n}\n"), 0o644)).To(Succeed())
	for _, name := range names {
		_, err := emit.InsertEndpointTag(path, emit.EndpointTagTestKey(name), name, false)
		Expect(err).NotTo(HaveOccurred())
	}
}

func testAccName(name string) string {
	return "TestAccDatadog" + model.SdkName(name) + "Datasource"
}

func (f *artifactFixture) goPath(name string) string {
	return filepath.Join(f.outputRoot, "data_source_datadog_"+name+".go")
}
func (f *artifactFixture) testPath(name string) string {
	return filepath.Join(f.testsRoot, "data_source_datadog_"+name+"_test.go")
}
func (f *artifactFixture) docPath(name string) string {
	return filepath.Join(f.docsRoot, name+".md")
}
func (f *artifactFixture) exampleDir(name string) string {
	return filepath.Join(f.examplesRoot, "datadog_"+name)
}
func (f *artifactFixture) examplePath(name string) string {
	return filepath.Join(f.exampleDir(name), "data-source.tf")
}
func (f *artifactFixture) genPath() string {
	return filepath.Join(f.outputRoot, "datasources_generated.go")
}
func (f *artifactFixture) providerTestPath() string {
	return filepath.Join(f.testsRoot, "provider_test.go")
}
func (f *artifactFixture) registry() string {
	data, err := os.ReadFile(f.genPath())
	Expect(err).NotTo(HaveOccurred())
	return string(data)
}
func (f *artifactFixture) providerTest() string {
	data, err := os.ReadFile(f.providerTestPath())
	Expect(err).NotTo(HaveOccurred())
	return string(data)
}

func (f *artifactFixture) retire(name string, check bool) model.ArtifactReportEntry {
	return retireArtifact(name, f.outputRoot, f.testsRoot, f.docsRoot, f.examplesRoot, check)
}

var _ = Describe("retireArtifact", func() {
	It("deletes the source, test, doc and example and removes the registration", func() {
		f := newFixture()
		f.writeArtifact("team", true)

		entry := f.retire("team", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.goPath("team")).NotTo(BeAnExistingFile())
		Expect(f.testPath("team")).NotTo(BeAnExistingFile())
		Expect(f.docPath("team")).NotTo(BeAnExistingFile())
		Expect(f.examplePath("team")).NotTo(BeAnExistingFile())
		Expect(f.exampleDir("team")).NotTo(BeADirectory())
		Expect(f.registry()).NotTo(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("preserves a non-empty example directory", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		sidecar := filepath.Join(f.exampleDir("team"), "README.md")
		Expect(os.WriteFile(sidecar, []byte("keep me"), 0o644)).To(Succeed())

		entry := f.retire("team", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.examplePath("team")).NotTo(BeAnExistingFile())
		Expect(f.exampleDir("team")).To(BeADirectory())
		Expect(sidecar).To(BeAnExistingFile())
	})

	It("blocks retirement and keeps every file when a recorded cassette adopted it", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		f.writeCassette(testAccName("team") + ".yaml")

		entry := f.retire("team", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetireBlocked))
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.testPath("team")).To(BeAnExistingFile())
		Expect(f.docPath("team")).To(BeAnExistingFile())
		Expect(f.examplePath("team")).To(BeAnExistingFile())
		Expect(f.exampleDir("team")).To(BeADirectory())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("blocks retirement of a file that lacks the tfgen generated-code marker", func() {
		f := newFixture()
		f.writeArtifact("team", false)

		entry := f.retire("team", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetireBlocked))
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.testPath("team")).To(BeAnExistingFile())
		Expect(f.docPath("team")).To(BeAnExistingFile())
		Expect(f.examplePath("team")).To(BeAnExistingFile())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("cleans up stray files and registration when the generated source is already missing", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		Expect(os.Remove(f.goPath("team"))).To(Succeed())

		entry := f.retire("team", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.testPath("team")).NotTo(BeAnExistingFile())
		Expect(f.docPath("team")).NotTo(BeAnExistingFile())
		Expect(f.examplePath("team")).NotTo(BeAnExistingFile())
		Expect(f.exampleDir("team")).NotTo(BeADirectory())
		Expect(f.registry()).NotTo(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("touches nothing on disk in check mode", func() {
		f := newFixture()
		f.writeArtifact("team", true)

		entry := f.retire("team", true)

		Expect(entry.Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.testPath("team")).To(BeAnExistingFile())
		Expect(f.docPath("team")).To(BeAnExistingFile())
		Expect(f.examplePath("team")).To(BeAnExistingFile())
		Expect(f.exampleDir("team")).To(BeADirectory())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("fails closed on a traversal name and deletes nothing outside the roots", func() {
		f := newFixture()
		// docPath is filepath.Join(docsRoot, name+".md"), so a "../" name escapes
		// the docs root; this sentinel sits where "../secret" would resolve to.
		sentinel := filepath.Join(filepath.Dir(f.docsRoot), "secret.md")
		Expect(os.WriteFile(sentinel, []byte("keep me"), 0o644)).To(Succeed())

		entry := f.retire("../secret", false)

		Expect(entry.Status).To(Equal(model.ArtifactStatusFailed))
		Expect(sentinel).To(BeAnExistingFile())
	})

	It("fails closed on a name carrying path or ref metacharacters", func() {
		f := newFixture()
		for _, bad := range []string{"foo/bar", "foo;rm", "Foo", "foo bar", ".."} {
			Expect(f.retire(bad, false).Status).To(Equal(model.ArtifactStatusFailed),
				"expected %q to be rejected", bad)
		}
	})
})

var _ = Describe("hasRecordedCassette", func() {
	DescribeTable("recognizes supported cassette names",
		func(suffix string) {
			f := newFixture()
			f.writeArtifact("team", true)
			name := testAccName("team") + suffix
			f.writeCassette(name)

			adopted, cassette := hasRecordedCassette(f.testPath("team"), filepath.Join(f.testsRoot, "cassettes"))

			Expect(adopted).To(BeTrue())
			Expect(cassette).To(Equal(name))
		},
		Entry("yaml", ".yaml"),
		Entry("freeze", ".freeze"),
		Entry("variant suffix", "_AWS_AssumeRole.yaml"),
	)

	It("ignores directories, unsupported extensions, and prefix collisions", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		funcName := testAccName("team")
		cassettesDir := filepath.Join(f.testsRoot, "cassettes")
		Expect(os.Mkdir(filepath.Join(cassettesDir, funcName+".yaml"), 0o755)).To(Succeed())
		f.writeCassette(funcName + ".txt")
		f.writeCassette(funcName + "Extra.yaml")

		adopted, cassette := hasRecordedCassette(f.testPath("team"), cassettesDir)

		Expect(adopted).To(BeFalse())
		Expect(cassette).To(BeEmpty())
	})

	It("treats missing or function-free test files as unadopted", func() {
		f := newFixture()
		missing := filepath.Join(f.testsRoot, "missing_test.go")
		adopted, cassette := hasRecordedCassette(missing, filepath.Join(f.testsRoot, "cassettes"))
		Expect(adopted).To(BeFalse())
		Expect(cassette).To(BeEmpty())

		f.writeArtifact("team", true)
		adopted, cassette = hasRecordedCassette(f.testPath("team"), filepath.Join(f.testsRoot, "missing-cassettes"))
		Expect(adopted).To(BeFalse())
		Expect(cassette).To(BeEmpty())

		empty := filepath.Join(f.testsRoot, "empty_test.go")
		Expect(os.WriteFile(empty, []byte("package test\n"), 0o644)).To(Succeed())
		adopted, cassette = hasRecordedCassette(empty, filepath.Join(f.testsRoot, "cassettes"))
		Expect(adopted).To(BeFalse())
		Expect(cassette).To(BeEmpty())
	})
})

var _ = Describe("reconcileOrphans", func() {
	It("retires a registered data source no longer in the desired set and keeps the rest", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		f.writeArtifact("zoo", true)
		f.writeEndpointTags("team", "zoo")
		desired := map[string]bool{emit.DatasourceConstructor("team"): true}

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, f.examplesRoot, desired, false)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(HaveLen(1))
		Expect(entries[0].Name).To(Equal("zoo"))
		Expect(entries[0].Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.goPath("zoo")).NotTo(BeAnExistingFile())
		Expect(f.examplePath("zoo")).NotTo(BeAnExistingFile())
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.examplePath("team")).To(BeAnExistingFile())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
		Expect(f.registry()).NotTo(ContainSubstring(emit.DatasourceConstructor("zoo")))
		Expect(f.providerTest()).To(ContainSubstring(emit.EndpointTagTestKey("team")))
		Expect(f.providerTest()).NotTo(ContainSubstring(emit.EndpointTagTestKey("zoo")))
	})

	It("leaves an adopted orphan in place with status retire_blocked", func() {
		f := newFixture()
		f.writeArtifact("zoo", true)
		f.writeCassette(testAccName("zoo") + ".yaml")

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, f.examplesRoot, map[string]bool{}, false)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(HaveLen(1))
		Expect(entries[0].Status).To(Equal(model.ArtifactStatusRetireBlocked))
		Expect(f.goPath("zoo")).To(BeAnExistingFile())
		Expect(f.examplePath("zoo")).To(BeAnExistingFile())
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("zoo")))
	})

	It("drops a registration whose generated files are already gone as registration_retired", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		f.registerOnly("ghost")
		desired := map[string]bool{emit.DatasourceConstructor("team"): true}

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, f.examplesRoot, desired, false)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(HaveLen(1))
		Expect(entries[0].Status).To(Equal(model.ArtifactStatusRegistrationRetired))
		Expect(entries[0].Constructor).To(Equal(emit.DatasourceConstructor("ghost")))
		Expect(entries[0].Name).To(Equal(emit.RegistrationRetirementName(emit.DatasourceConstructor("ghost"))))
		Expect(f.registry()).NotTo(ContainSubstring(emit.DatasourceConstructor("ghost")))
		Expect(f.registry()).To(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("removes only the stale registration for a handwritten source", func() {
		f := newFixture()
		f.writeArtifact("team", false)

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, f.examplesRoot, map[string]bool{}, false)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(HaveLen(1))
		Expect(entries[0].Status).To(Equal(model.ArtifactStatusRegistrationRetired))
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.testPath("team")).To(BeAnExistingFile())
		Expect(f.docPath("team")).To(BeAnExistingFile())
		Expect(f.examplePath("team")).To(BeAnExistingFile())
		Expect(f.registry()).NotTo(ContainSubstring(emit.DatasourceConstructor("team")))
	})

	It("reports mixed orphans deterministically without modifying disk in check mode", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		f.registerOnly("ghost")
		registryBefore := f.registry()

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, f.examplesRoot, map[string]bool{}, true)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(HaveLen(2))
		Expect(entries[0].Status).To(Equal(model.ArtifactStatusRegistrationRetired))
		Expect(entries[0].Constructor).To(Equal(emit.DatasourceConstructor("ghost")))
		Expect(entries[1].Name).To(Equal("team"))
		Expect(entries[1].Status).To(Equal(model.ArtifactStatusRetired))
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.testPath("team")).To(BeAnExistingFile())
		Expect(f.docPath("team")).To(BeAnExistingFile())
		Expect(f.examplePath("team")).To(BeAnExistingFile())
		Expect(f.registry()).To(Equal(registryBefore))
	})

	It("finds no orphans when every registration is still desired", func() {
		f := newFixture()
		f.writeArtifact("team", true)
		desired := map[string]bool{emit.DatasourceConstructor("team"): true}
		registryBefore := f.registry()

		entries, err := reconcileOrphans(f.outputRoot, f.testsRoot, f.docsRoot, f.examplesRoot, desired, false)

		Expect(err).NotTo(HaveOccurred())
		Expect(entries).To(BeEmpty())
		Expect(f.goPath("team")).To(BeAnExistingFile())
		Expect(f.registry()).To(Equal(registryBefore))
	})
})
