blank_issues_enabled: true
contact_links:
  - name: Datadog Support
    url: https://help.datadoghq.com/hc/en-us/requests/new
    about: Submit a ticket here for urgent issues, questions, and feature requests for the Datadog product and/or its API.
  - name: Datadog Documentation
    url: https://docs.datadoghq.com/
    about: For questions about usage of Datadog products, check here.