package codegen

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/DataDog/terraform-provider-datadog/generator/internal/config"
)

func TestGenerate_TeamDataSource(t *testing.T) {
	cfg := &config.Config{
		Specs: map[string]config.SpecConfig{
			"v2": {Path: "minimal.yaml"},
		},
		DataSources: map[string]config.DataSourceConfig{
			"team": {
				Spec: "v2",
				Read: config.OperationRef{
					Path:   "/api/v2/team/{team_id}",
					Method: "get",
				},
			},
		},
	}

	outputDir := t.TempDir()
	configDir := "../../testdata"

	err := Generate(cfg, configDir, outputDir, false, 5)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	// Verify generated file exists
	genPath := filepath.Join(outputDir, "data_source_datadog_team_generated.go")
	if _, err := os.Stat(genPath); os.IsNotExist(err) {
		t.Fatal("generated file not created")
	}

	// Verify hooks file exists
	hooksPath := filepath.Join(outputDir, "data_source_datadog_team_hooks.go")
	if _, err := os.Stat(hooksPath); os.IsNotExist(err) {
		t.Fatal("hooks file not created")
	}

	// Verify generated file is valid Go
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, genPath, nil, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated file is not valid Go: %v", err)
	}

	// Verify generated file contains expected patterns
	content, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("reading generated file: %v", err)
	}

	expectedPatterns := []string{
		"// Code generated by dd-tf-generator; DO NOT EDIT.",
		"package fwprovider",
		"datadogTeamDataSource",
		"datadogTeamDataSourceModel",
		`tfsdk:"team_id"`,
		`tfsdk:"name"`,
		"schema.StringAttribute",
		"schema.Int64Attribute",
		"schema.BoolAttribute",
		"GetTeam",
		"GetTeamsApiV2",
		"TeamsApi",
		"utils.FrameworkErrorDiag",
		"GetData()",
		"GetAttributes()",
	}

	for _, pattern := range expectedPatterns {
		if !strings.Contains(string(content), pattern) {
			t.Errorf("generated file missing expected pattern: %q", pattern)
		}
	}
}

func TestGenerate_DryRun(t *testing.T) {
	cfg := &config.Config{
		Specs: map[string]config.SpecConfig{
			"v2": {Path: "minimal.yaml"},
		},
		DataSources: map[string]config.DataSourceConfig{
			"team": {
				Spec: "v2",
				Read: config.OperationRef{
					Path:   "/api/v2/team/{team_id}",
					Method: "get",
				},
			},
		},
	}

	outputDir := t.TempDir()
	configDir := "../../testdata"

	err := Generate(cfg, configDir, outputDir, true, 5)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	// Verify no files were written
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		t.Fatalf("reading output dir: %v", err)
	}

	if len(entries) != 0 {
		t.Errorf("dry-run should not create files, found %d", len(entries))
	}
}

func TestGenerate_MissingPath(t *testing.T) {
	cfg := &config.Config{
		Specs: map[string]config.SpecConfig{
			"v2": {Path: "minimal.yaml"},
		},
		DataSources: map[string]config.DataSourceConfig{
			"nonexistent": {
				Spec: "v2",
				Read: config.OperationRef{
					Path:   "/api/v2/nonexistent",
					Method: "get",
				},
			},
		},
	}

	outputDir := t.TempDir()
	configDir := "../../testdata"

	err := Generate(cfg, configDir, outputDir, false, 5)
	if err == nil {
		t.Fatal("expected error for missing path")
	}

	if !strings.Contains(err.Error(), "not found in spec") {
		t.Errorf("expected error about missing path, got: %v", err)
	}

	// No files should be created
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		t.Fatalf("reading output dir: %v", err)
	}
	if len(entries) != 0 {
		t.Errorf("error case should not create files, found %d", len(entries))
	}
}

func TestGenerate_HooksPreserved(t *testing.T) {
	cfg := &config.Config{
		Specs: map[string]config.SpecConfig{
			"v2": {Path: "minimal.yaml"},
		},
		DataSources: map[string]config.DataSourceConfig{
			"team": {
				Spec: "v2",
				Read: config.OperationRef{
					Path:   "/api/v2/team/{team_id}",
					Method: "get",
				},
			},
		},
	}

	outputDir := t.TempDir()
	configDir := "../../testdata"

	// First generation
	if err := Generate(cfg, configDir, outputDir, false, 5); err != nil {
		t.Fatalf("first Generate() error: %v", err)
	}

	// Modify hooks file with custom content
	hooksPath := filepath.Join(outputDir, "data_source_datadog_team_hooks.go")
	customContent := []byte("package fwprovider\n\n// Custom hook code\n")
	if err := os.WriteFile(hooksPath, customContent, 0644); err != nil {
		t.Fatalf("writing custom hooks: %v", err)
	}

	// Second generation
	if err := Generate(cfg, configDir, outputDir, false, 5); err != nil {
		t.Fatalf("second Generate() error: %v", err)
	}

	// Verify hooks file is unchanged
	data, err := os.ReadFile(hooksPath)
	if err != nil {
		t.Fatalf("reading hooks file: %v", err)
	}
	if string(data) != string(customContent) {
		t.Error("hooks file was overwritten during regeneration")
	}

	// Verify generated file was regenerated (exists and is valid Go)
	genPath := filepath.Join(outputDir, "data_source_datadog_team_generated.go")
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, genPath, nil, parser.AllErrors)
	if err != nil {
		t.Fatalf("regenerated file is not valid Go: %v", err)
	}
}

// T108: Composition types generate successfully (replaces TestGenerate_UnsupportedOneOf)
func TestGenerate_CompositionOneOf(t *testing.T) {
	cfg, err := config.LoadConfig("../../testdata/config_with_composition.yaml")
	if err != nil {
		t.Fatalf("LoadConfig() error: %v", err)
	}

	outputDir := t.TempDir()
	configDir := "../../testdata"

	err = Generate(cfg, configDir, outputDir, false, 5)
	if err != nil {
		t.Fatalf("Generate() error (composition should succeed): %v", err)
	}

	genPath := filepath.Join(outputDir, "data_source_datadog_composed_generated.go")

	// Verify valid Go
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, genPath, nil, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated file is not valid Go: %v", err)
	}

	content, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("reading generated file: %v", err)
	}
	s := string(content)

	// Verify allOf merged properties from ComposedBase + ComposedExtension
	expectedPatterns := []string{
		"package fwprovider",
		"datadogComposedDataSource",
		"GetComposedApiV2",    // SDK accessor
		"ComposedResponse",    // Response type from $ref
		`tfsdk:"name"`,        // From ComposedBase
		`tfsdk:"version"`,     // From ComposedBase
		`tfsdk:"priority"`,    // From ComposedExtension
		"GetData()",           // JSON:API
		"GetAttributes()",     // JSON:API
		"schema.MapAttribute", // From additionalProperties
	}

	for _, pattern := range expectedPatterns {
		if !strings.Contains(s, pattern) {
			t.Errorf("generated file missing expected pattern: %q", pattern)
		}
	}
}

func TestGenerate_SimpleEndpoint(t *testing.T) {
	cfg := &config.Config{
		Specs: map[string]config.SpecConfig{
			"v2": {Path: "minimal.yaml"},
		},
		DataSources: map[string]config.DataSourceConfig{
			"simple": {
				Spec: "v2",
				Read: config.OperationRef{
					Path:   "/api/v2/simple/{id}",
					Method: "get",
				},
			},
		},
	}

	outputDir := t.TempDir()
	configDir := "../../testdata"

	err := Generate(cfg, configDir, outputDir, false, 5)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	genPath := filepath.Join(outputDir, "data_source_datadog_simple_generated.go")
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, genPath, nil, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated file is not valid Go: %v", err)
	}

	// Non-JSON:API endpoint should not have GetData()/GetAttributes()
	content, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("reading file: %v", err)
	}

	if strings.Contains(string(content), "GetData()") {
		t.Error("non-JSON:API endpoint should not use GetData()")
	}
}

// T042: Regenerate after spec change - new field appears in output
func TestGenerate_NewFieldDetection(t *testing.T) {
	// Create a temporary spec with fewer fields
	dir := t.TempDir()
	specDir := filepath.Join(dir, "specs")
	if err := os.MkdirAll(specDir, 0755); err != nil {
		t.Fatalf("creating spec dir: %v", err)
	}

	specV1 := `openapi: 3.0.0
info:
  title: Test API
  version: "1.0"
paths:
  /api/v2/item/{id}:
    get:
      operationId: GetItem
      tags:
        - Items
      summary: Get an item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: The item name.
`
	specPath := filepath.Join(specDir, "spec.yaml")
	if err := os.WriteFile(specPath, []byte(specV1), 0644); err != nil {
		t.Fatalf("writing v1 spec: %v", err)
	}

	cfg := &config.Config{
		Specs: map[string]config.SpecConfig{
			"v2": {Path: "spec.yaml"},
		},
		DataSources: map[string]config.DataSourceConfig{
			"item": {
				Spec: "v2",
				Read: config.OperationRef{
					Path:   "/api/v2/item/{id}",
					Method: "get",
				},
			},
		},
	}

	outputDir := filepath.Join(dir, "output")

	// First generation
	if err := Generate(cfg, specDir, outputDir, false, 5); err != nil {
		t.Fatalf("first Generate() error: %v", err)
	}

	genPath := filepath.Join(outputDir, "data_source_datadog_item_generated.go")
	content1, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("reading generated file: %v", err)
	}

	if !strings.Contains(string(content1), "name") {
		t.Error("first generation should contain 'name' field")
	}
	if strings.Contains(string(content1), "price") {
		t.Error("first generation should NOT contain 'price' field")
	}

	// Update spec with a new field
	specV2 := `openapi: 3.0.0
info:
  title: Test API
  version: "1.0"
paths:
  /api/v2/item/{id}:
    get:
      operationId: GetItem
      tags:
        - Items
      summary: Get an item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: The item name.
                  price:
                    type: number
                    format: double
                    description: The item price.
`
	if err := os.WriteFile(specPath, []byte(specV2), 0644); err != nil {
		t.Fatalf("writing v2 spec: %v", err)
	}

	// Regenerate
	if err := Generate(cfg, specDir, outputDir, false, 5); err != nil {
		t.Fatalf("second Generate() error: %v", err)
	}

	content2, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("reading regenerated file: %v", err)
	}

	if !strings.Contains(string(content2), "price") {
		t.Error("regenerated file should contain new 'price' field")
	}
	if !strings.Contains(string(content2), "Float64") {
		t.Error("regenerated file should contain Float64 type for price")
	}
}

// T062: Filter-fallback integration test
func TestGenerate_WithListFallback(t *testing.T) {
	cfg, err := config.LoadConfig("../../testdata/config_with_list.yaml")
	if err != nil {
		t.Fatalf("LoadConfig() error: %v", err)
	}

	outputDir := t.TempDir()
	configDir := "../../testdata"

	err = Generate(cfg, configDir, outputDir, false, 5)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	// Verify team generated file (with list fallback)
	genPath := filepath.Join(outputDir, "data_source_datadog_team_generated.go")
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, genPath, nil, parser.AllErrors)
	if err != nil {
		t.Fatalf("team generated file is not valid Go: %v", err)
	}

	content, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("reading team generated file: %v", err)
	}

	// Filter-fallback patterns
	filterPatterns := []string{
		"datasourcevalidator.AtLeastOneOf", // Validator
		"ListTeams",                        // List method
		"ListTeamsOptionalParameters",      // Optional params
		"FilterKeyword",                    // Filter param in model
		"FilterMe",                         // Filter param in model
		"filter_keyword",                   // Filter param in schema
		"filter_me",                        // Filter param in schema
		"!state.TeamID.IsNull()",           // ID check branch
		"path.MatchRoot",                   // Validator paths
	}

	for _, pattern := range filterPatterns {
		if !strings.Contains(string(content), pattern) {
			t.Errorf("team file missing filter-fallback pattern: %q", pattern)
		}
	}

	// Verify simple generated file (without list fallback) also valid
	simplePath := filepath.Join(outputDir, "data_source_datadog_simple_generated.go")
	_, err = parser.ParseFile(fset, simplePath, nil, parser.AllErrors)
	if err != nil {
		t.Fatalf("simple generated file is not valid Go: %v", err)
	}

	simpleContent, err := os.ReadFile(simplePath)
	if err != nil {
		t.Fatalf("reading simple generated file: %v", err)
	}

	// Simple should NOT have filter-fallback patterns
	if strings.Contains(string(simpleContent), "datasourcevalidator") {
		t.Error("simple file should not contain datasourcevalidator (no list fallback)")
	}
	if strings.Contains(string(simpleContent), "ListTeams") {
		t.Error("simple file should not contain ListTeams")
	}
}

// T078: Correctness fixes integration test
func TestGenerate_CorrectnessPatterns(t *testing.T) {
	cfg := &config.Config{
		Specs: map[string]config.SpecConfig{
			"v2": {Path: "minimal.yaml"},
		},
		DataSources: map[string]config.DataSourceConfig{
			"team": {
				Spec: "v2",
				Read: config.OperationRef{
					Path:   "/api/v2/team/{team_id}",
					Method: "get",
				},
			},
		},
	}

	outputDir := t.TempDir()
	configDir := "../../testdata"

	err := Generate(cfg, configDir, outputDir, false, 5)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	genPath := filepath.Join(outputDir, "data_source_datadog_team_generated.go")
	content, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("reading generated file: %v", err)
	}

	s := string(content)

	// Phase 8: 11a - $ref-based response type (TeamResponse from $ref)
	if !strings.Contains(s, "*datadogV2.TeamResponse") {
		t.Error("should use $ref-based response type *datadogV2.TeamResponse")
	}

	// Phase 8: 11b - Nullable fields use GetXxxOk pattern
	if !strings.Contains(s, "GetDescriptionOk()") {
		t.Error("nullable field 'description' should use GetDescriptionOk()")
	}
	if !strings.Contains(s, "GetSummaryOk()") {
		t.Error("nullable field 'summary' should use GetSummaryOk()")
	}
	if !strings.Contains(s, "types.StringNull()") {
		t.Error("nullable fields should have null value fallback")
	}

	// Phase 8: 11c - Date-time fields excluded
	if strings.Contains(s, "created_at") || strings.Contains(s, "CreatedAt") {
		t.Error("date-time field created_at should be excluded")
	}
	if strings.Contains(s, "modified_at") || strings.Contains(s, "ModifiedAt") {
		t.Error("date-time field modified_at should be excluded")
	}

	// Phase 8: 11d - Array fields use ListValueFrom
	if !strings.Contains(s, "types.ListValueFrom") {
		t.Error("array fields should use types.ListValueFrom")
	}
	if !strings.Contains(s, "HiddenModules") {
		t.Error("array field hidden_modules should be present")
	}
	if !strings.Contains(s, "VisibleModules") {
		t.Error("array field visible_modules should be present")
	}

	// Phase 8: 11e - ctx parameter in updateState
	if !strings.Contains(s, "func (d *datadogTeamDataSource) updateState(ctx context.Context") {
		t.Error("updateState should accept ctx context.Context parameter")
	}
}

// T045: Config validation errors surface correctly through Generate()
func TestGenerate_ConfigValidationErrors(t *testing.T) {
	tests := []struct {
		name    string
		cfg     *config.Config
		wantErr string
	}{
		{
			name: "missing spec file",
			cfg: &config.Config{
				Specs: map[string]config.SpecConfig{
					"v2": {Path: "nonexistent.yaml"},
				},
				DataSources: map[string]config.DataSourceConfig{
					"team": {
						Spec: "v2",
						Read: config.OperationRef{
							Path:   "/api/v2/team/{team_id}",
							Method: "get",
						},
					},
				},
			},
			wantErr: "loading spec",
		},
		{
			name: "path not in spec",
			cfg: &config.Config{
				Specs: map[string]config.SpecConfig{
					"v2": {Path: "minimal.yaml"},
				},
				DataSources: map[string]config.DataSourceConfig{
					"missing": {
						Spec: "v2",
						Read: config.OperationRef{
							Path:   "/api/v2/does_not_exist",
							Method: "get",
						},
					},
				},
			},
			wantErr: "not found in spec",
		},
		{
			name: "wrong method",
			cfg: &config.Config{
				Specs: map[string]config.SpecConfig{
					"v2": {Path: "minimal.yaml"},
				},
				DataSources: map[string]config.DataSourceConfig{
					"team": {
						Spec: "v2",
						Read: config.OperationRef{
							Path:   "/api/v2/team/{team_id}",
							Method: "delete",
						},
					},
				},
			},
			wantErr: "not found for path",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			outputDir := t.TempDir()

			err := Generate(tt.cfg, "../../testdata", outputDir, false, 5)
			if err == nil {
				t.Fatalf("expected error containing %q, got nil", tt.wantErr)
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("expected error containing %q, got %q", tt.wantErr, err.Error())
			}

			// No files should be created on error
			entries, err := os.ReadDir(outputDir)
			if err != nil {
				t.Fatalf("reading output dir: %v", err)
			}
			if len(entries) != 0 {
				t.Errorf("error case should not create files, found %d", len(entries))
			}
		})
	}
}
