package emit

import (
	"errors"
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/model"
)

var _ = Describe("WriteFile", func() {
	var dir string

	BeforeEach(func() {
		var err error
		dir, err = os.MkdirTemp("", "writer-test-*")
		Expect(err).NotTo(HaveOccurred())
		DeferCleanup(os.RemoveAll, dir)
	})

	path := func(name string) string { return filepath.Join(dir, name) }

	Describe("write mode", func() {
		It("creates a new file and returns Created", func() {
			p := path("new.go")
			status, err := WriteFile(p, []byte("hello"), false)
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(model.ArtifactStatusCreated))
			Expect(os.ReadFile(p)).To(Equal([]byte("hello")))
		})

		It("returns Unchanged and leaves the file alone when content matches", func() {
			p := path("same.go")
			Expect(os.WriteFile(p, []byte("hello"), 0o644)).To(Succeed())
			status, err := WriteFile(p, []byte("hello"), false)
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(model.ArtifactStatusUnchanged))
			Expect(os.ReadFile(p)).To(Equal([]byte("hello")))
		})

		It("overwrites a file with changed content and returns Updated", func() {
			p := path("changed.go")
			Expect(os.WriteFile(p, []byte("old"), 0o644)).To(Succeed())
			status, err := WriteFile(p, []byte("new"), false)
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(model.ArtifactStatusUpdated))
			Expect(os.ReadFile(p)).To(Equal([]byte("new")))
		})

		It("creates parent directories as needed", func() {
			p := filepath.Join(dir, "sub", "dir", "file.go")
			status, err := WriteFile(p, []byte("hello"), false)
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(model.ArtifactStatusCreated))
			Expect(os.ReadFile(p)).To(Equal([]byte("hello")))
		})
	})

	Describe("check mode", func() {
		It("returns Created without creating the file", func() {
			p := path("check-new.go")
			status, err := WriteFile(p, []byte("hello"), true)
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(model.ArtifactStatusCreated))
			_, statErr := os.Stat(p)
			Expect(os.IsNotExist(statErr)).To(BeTrue())
		})

		It("returns Unchanged without touching the file", func() {
			p := path("check-same.go")
			Expect(os.WriteFile(p, []byte("hello"), 0o644)).To(Succeed())
			status, err := WriteFile(p, []byte("hello"), true)
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(model.ArtifactStatusUnchanged))
		})

		It("returns Updated without writing the file", func() {
			p := path("check-changed.go")
			Expect(os.WriteFile(p, []byte("old"), 0o644)).To(Succeed())
			status, err := WriteFile(p, []byte("new"), true)
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(model.ArtifactStatusUpdated))
			Expect(os.ReadFile(p)).To(Equal([]byte("old")))
		})
	})

})

var _ = Describe("WriteArtifactSource", func() {
	var dir string

	BeforeEach(func() {
		var err error
		dir, err = os.MkdirTemp("", "artifact-source-test-*")
		Expect(err).NotTo(HaveOccurred())
		DeferCleanup(os.RemoveAll, dir)
	})

	generated := []byte("// Code generated by tfgen; DO NOT EDIT.\npackage fwprovider\n")

	It("writes when nothing occupies the path", func() {
		path := filepath.Join(dir, "resource_datadog_thing.go")
		status, err := WriteArtifactSource(path, generated, false, false)
		Expect(err).NotTo(HaveOccurred())
		Expect(status).To(Equal(model.ArtifactStatusCreated))
	})

	It("replaces a file it generated on an earlier run", func() {
		By("the marker is tfgen's proof of ownership, so a re-run needs no authorization")
		path := filepath.Join(dir, "resource_datadog_thing.go")
		Expect(os.WriteFile(path, generated, 0o644)).To(Succeed())

		status, err := WriteArtifactSource(path, append(generated, []byte("// changed\n")...), false, false)
		Expect(err).NotTo(HaveOccurred())
		Expect(status).To(Equal(model.ArtifactStatusUpdated))
	})

	It("refuses to replace a hand-written file, leaving it untouched", func() {
		path := filepath.Join(dir, "resource_datadog_thing.go")
		handwritten := []byte("package fwprovider\n\nfunc NewThingResource() {}\n")
		Expect(os.WriteFile(path, handwritten, 0o644)).To(Succeed())

		status, err := WriteArtifactSource(path, generated, false, false)
		Expect(status).To(Equal(model.ArtifactStatusFailed))

		var collision *HandwrittenCollisionError
		Expect(errors.As(err, &collision)).To(BeTrue())
		Expect(collision.Path).To(Equal(path))
		By("the message names the annotation that would authorize the takeover")
		Expect(err.Error()).To(ContainSubstring(`"overwrites"`))

		onDisk, readErr := os.ReadFile(path)
		Expect(readErr).NotTo(HaveOccurred())
		Expect(onDisk).To(Equal(handwritten), "a refused write must not touch the file")
	})

	It("replaces a hand-written file when the annotation authorizes the takeover", func() {
		path := filepath.Join(dir, "resource_datadog_thing.go")
		Expect(os.WriteFile(path, []byte("package fwprovider\n"), 0o644)).To(Succeed())

		status, err := WriteArtifactSource(path, generated, false, true)
		Expect(err).NotTo(HaveOccurred())
		Expect(status).To(Equal(model.ArtifactStatusUpdated))
	})

	It("refuses in check mode too, without writing", func() {
		By("--check must report the collision rather than pass and fail on the next real run")
		path := filepath.Join(dir, "resource_datadog_thing.go")
		Expect(os.WriteFile(path, []byte("package fwprovider\n"), 0o644)).To(Succeed())

		_, err := WriteArtifactSource(path, generated, true, false)
		Expect(err).To(HaveOccurred())
	})
})
