package emit

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/model"
)

// generatedMarker is the header comment every generated artifact carries, and
// tfgen's proof of ownership: a file without it was not produced by tfgen, so
// tfgen neither deletes nor replaces it. Unexported so both gates match it
// through IsGeneratedSource rather than spelling the test themselves.
const generatedMarker = "Code generated by tfgen"

// generatedMarkerBytes avoids re-allocating the marker on every ownership test.
var generatedMarkerBytes = []byte(generatedMarker)

// IsGeneratedSource reports whether content was produced by tfgen — the single
// ownership predicate gating both deletion and replacement.
func IsGeneratedSource(content []byte) bool {
	return bytes.Contains(content, generatedMarkerBytes)
}

// HandwrittenCollisionError reports a generated artifact whose output path is
// already occupied by a file tfgen did not generate. It names both the path and
// the annotation that would authorize the takeover, the two ways out being
// different decisions: rename the artifact, or declare the replacement.
type HandwrittenCollisionError struct {
	Path string
}

func (e *HandwrittenCollisionError) Error() string {
	return fmt.Sprintf(
		"refusing to overwrite %s: it carries no %q marker, so tfgen did not generate it. "+
			"Either rename the artifact, or — if this artifact is meant to replace that hand-written one in place — "+
			"declare its constructor in the tracking extension's \"overwrites\" field, which also de-registers it from the provider",
		e.Path, generatedMarker)
}

// WriteArtifactSource writes a generated artifact's Go source. Unlike WriteFile
// it refuses to replace a file carrying no generated marker, which would
// otherwise delete hand-written code while reporting "updated".
// authorizedTakeover, from the annotation's "overwrites" field, lifts the
// refusal; a re-run needs none, the file on disk being tfgen's own by then.
func WriteArtifactSource(path string, content []byte, check, authorizedTakeover bool) (model.ArtifactStatus, error) {
	existing, err := readExisting(path)
	if err != nil {
		return model.ArtifactStatusFailed, err
	}
	if existing != nil && !authorizedTakeover && !IsGeneratedSource(existing) {
		return model.ArtifactStatusFailed, &HandwrittenCollisionError{Path: path}
	}
	return writeContent(path, content, existing, check)
}

// WriteFileIfAbsent writes content only when path does not exist, reporting
// ArtifactStatusSkipped when a file is already there. Generated acceptance
// tests use it: the scaffold is completed by hand, so regeneration must never
// overwrite one.
func WriteFileIfAbsent(path string, content []byte, check bool) (model.ArtifactStatus, error) {
	if _, err := os.Stat(path); err == nil {
		return model.ArtifactStatusSkipped, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return model.ArtifactStatusFailed, err
	}
	return WriteFile(path, content, check)
}

// WriteFile writes content to path, skipping the write when on-disk content
// matches. In check mode it reports what would happen without touching disk.
// Parent directories are created as needed.
func WriteFile(path string, content []byte, check bool) (model.ArtifactStatus, error) {
	existing, err := readExisting(path)
	if err != nil {
		return model.ArtifactStatusFailed, err
	}
	return writeContent(path, content, existing, check)
}

// readExisting reads path, reporting a missing file as nil content rather than
// an error so callers branch on presence instead of re-classifying errno. One
// read serves both the ownership test and the content diff.
func readExisting(path string) ([]byte, error) {
	content, err := os.ReadFile(path)
	switch {
	case err == nil:
		return content, nil
	case errors.Is(err, os.ErrNotExist):
		return nil, nil
	default:
		return nil, err
	}
}

// writeContent applies content to path given what is already there: nil
// existing means the file is new. In check mode it reports what would happen
// without touching disk. Parent directories are created as needed.
func writeContent(path string, content, existing []byte, check bool) (model.ArtifactStatus, error) {
	if existing == nil {
		if !check {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return model.ArtifactStatusFailed, err
			}
			if err := os.WriteFile(path, content, 0o644); err != nil {
				return model.ArtifactStatusFailed, err
			}
		}
		return model.ArtifactStatusCreated, nil
	}

	if bytes.Equal(existing, content) {
		return model.ArtifactStatusUnchanged, nil
	}

	if !check {
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return model.ArtifactStatusFailed, err
		}
	}
	return model.ArtifactStatusUpdated, nil
}
