package split

import (
	"os"
	"path/filepath"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/emit"
)

const fwDir = "datadog/fwprovider"

func dsFileName(name string) string { return "data_source_datadog_" + name + ".go" }

func writeFile(root, rel, content string) {
	GinkgoHelper()
	p := filepath.Join(root, rel)
	Expect(os.MkdirAll(filepath.Dir(p), 0o755)).To(Succeed())
	Expect(os.WriteFile(p, []byte(content), 0o644)).To(Succeed())
}

func readFile(path string) string {
	GinkgoHelper()
	b, err := os.ReadFile(path)
	Expect(err).NotTo(HaveOccurred())
	return string(b)
}

// writeRegistry renders a datasources_generated.go under root holding exactly the
// given constructors, using the real serializer so the fixture matches production.
func writeRegistry(root string, constructors ...string) {
	GinkgoHelper()
	_, err := emit.SyncGeneratedDatasources(filepath.Join(root, fwDir, registryFile), constructors, false)
	Expect(err).NotTo(HaveOccurred())
}

// dataSourceContent is a minimal generated-file body declaring one constructor;
// split copies it verbatim and never parses it (except a base file for overwrite
// attribution, which only needs the func declaration).
func dataSourceContent(constructor string) string {
	return "// Code generated by tfgen; DO NOT EDIT.\npackage fwprovider\n\nfunc " + constructor + "() {}\n"
}

// providerFileContent renders a framework_provider.go whose hand-written
// Datasources slice lists the given constructors.
func providerFileContent(constructors ...string) string {
	var b strings.Builder
	b.WriteString("package fwprovider\n\n")
	b.WriteString(datasourcesSliceHeader + "\n")
	for _, c := range constructors {
		b.WriteString("\t")
		b.WriteString(c)
		b.WriteString(",\n")
	}
	b.WriteString("}\n")
	return b.String()
}

var _ = Describe("Split", func() {
	var base, gen, out string

	BeforeEach(func() {
		base = GinkgoT().TempDir()
		gen = GinkgoT().TempDir()
		out = GinkgoT().TempDir()
	})

	It("routes a single net-new artifact into its own bundle with the registry reconstructed as base plus itself", func() {
		writeRegistry(base) // empty
		ctor := emit.DatasourceConstructor("rum_applications")
		writeFile(gen, filepath.Join(fwDir, dsFileName("rum_applications")), dataSourceContent(ctor))
		writeRegistry(gen, ctor)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Errors).To(BeEmpty())
		Expect(rep.Artifacts).To(HaveLen(1))

		art := rep.Artifacts[0]
		Expect(art.Name).To(Equal("rum_applications"))
		Expect(art.Status).To(Equal("created"))
		Expect(art.Files).To(ConsistOf(
			filepath.Join(fwDir, dsFileName("rum_applications")),
			filepath.Join(fwDir, registryFile),
		))

		routedReg := readFile(filepath.Join(out, "rum_applications", fwDir, registryFile))
		Expect(routedReg).To(ContainSubstring(ctor))
		routedSrc := readFile(filepath.Join(out, "rum_applications", fwDir, dsFileName("rum_applications")))
		Expect(routedSrc).To(Equal(dataSourceContent(ctor)), "source file must be copied verbatim")
	})

	It("gives each artifact of a multi-artifact push its own bundle whose registry holds base plus only that artifact", func() {
		existing := emit.DatasourceConstructor("existing")
		writeRegistry(base, existing) // base already has one generated data source

		names := []string{"alpha", "bravo", "charlie"}
		ctors := map[string]string{}
		genSet := []string{existing}
		for _, n := range names {
			ctors[n] = emit.DatasourceConstructor(n)
			genSet = append(genSet, ctors[n])
			writeFile(gen, filepath.Join(fwDir, dsFileName(n)), dataSourceContent(ctors[n]))
		}
		writeRegistry(gen, genSet...)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(3))

		for _, n := range names {
			routedReg := readFile(filepath.Join(out, n, fwDir, registryFile))
			Expect(routedReg).To(ContainSubstring(existing), "each branch must preserve the base entry")
			Expect(routedReg).To(ContainSubstring(ctors[n]), "each branch must hold its own constructor")
			for _, other := range names {
				if other == n {
					continue
				}
				Expect(routedReg).NotTo(ContainSubstring(ctors[other]), "a branch must not carry a sibling's constructor")
			}
		}
	})

	It("fails loud on a changed file it cannot attribute to any artifact", func() {
		writeRegistry(base)
		writeFile(gen, filepath.Join(fwDir, registryFile), readFile(filepath.Join(base, fwDir, registryFile)))
		writeFile(gen, filepath.Join(fwDir, "surprise_helper.go"), "package fwprovider\n")

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).To(HaveOccurred())
		Expect(rep.Artifacts).To(BeEmpty())
		Expect(rep.Errors).To(ContainElement(ContainSubstring("surprise_helper.go")))
	})

	It("routes an overwrites artifact's framework_provider.go, removing only the retired constructor", func() {
		teamCtor := emit.DatasourceConstructor("team") // NewDatadogTeamDataSource
		neighbor := "NewDatadogTeamHierarchyLinksDataSource"

		// Base: a hand-written team data source, registered in the Datasources slice.
		writeRegistry(base)
		writeFile(base, filepath.Join(fwDir, providerFile), providerFileContent(teamCtor, neighbor))
		writeFile(base, filepath.Join(fwDir, dsFileName("team")), dataSourceContent(teamCtor))

		// Gen: generated team overwrote it — file rewritten, constructor moved from
		// the hand-written slice into the generated registry.
		writeFile(gen, filepath.Join(fwDir, providerFile), providerFileContent(neighbor))
		writeFile(gen, filepath.Join(fwDir, dsFileName("team")), dataSourceContent(teamCtor)+"// regenerated\n")
		writeRegistry(gen, teamCtor)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(1))
		Expect(rep.Artifacts[0].Status).To(Equal("updated"))
		Expect(rep.Artifacts[0].Files).To(ContainElement(filepath.Join(fwDir, providerFile)))

		routedProvider := readFile(filepath.Join(out, "team", fwDir, providerFile))
		Expect(routedProvider).NotTo(ContainSubstring(teamCtor+","), "the overwritten constructor must be retired")
		Expect(routedProvider).To(ContainSubstring(neighbor), "neighbors must be left intact")
	})

	It("fails loud when a data source file changed but the registry did not", func() {
		writeRegistry(base)
		writeFile(gen, filepath.Join(fwDir, registryFile), readFile(filepath.Join(base, fwDir, registryFile)))
		ctor := emit.DatasourceConstructor("orphan")
		writeFile(gen, filepath.Join(fwDir, dsFileName("orphan")), dataSourceContent(ctor))

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).To(HaveOccurred())
		Expect(rep.Errors).To(ContainElement(ContainSubstring(registryFile)))
	})

	It("fails loud on a removed file, since retirement is out of scope for the create/update MVP", func() {
		writeRegistry(base)
		writeFile(base, filepath.Join(fwDir, dsFileName("gone")), dataSourceContent(emit.DatasourceConstructor("gone")))
		writeFile(gen, filepath.Join(fwDir, registryFile), readFile(filepath.Join(base, fwDir, registryFile)))

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).To(HaveOccurred())
		Expect(rep.Errors).To(ContainElement(ContainSubstring("removed")))
	})

	It("writes no bundle in check mode but still reports the plan", func() {
		writeRegistry(base)
		ctor := emit.DatasourceConstructor("dryrun")
		writeFile(gen, filepath.Join(fwDir, dsFileName("dryrun")), dataSourceContent(ctor))
		writeRegistry(gen, ctor)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out, Check: true})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(1))
		_, statErr := os.Stat(filepath.Join(out, "dryrun"))
		Expect(os.IsNotExist(statErr)).To(BeTrue(), "check mode must not write bundles")
	})
})
