package split

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/emit"
	"github.com/terraform-providers/terraform-provider-datadog/generator/internal/model"
)

const fwDir = "datadog/fwprovider"
const testsDir = "datadog/tests"

func dsFileName(name string) string { return "data_source_datadog_" + name + ".go" }
func dsTestFileName(name string) string {
	return "data_source_datadog_" + name + "_test.go"
}

func writeFile(root, rel, content string) {
	GinkgoHelper()
	p := filepath.Join(root, rel)
	Expect(os.MkdirAll(filepath.Dir(p), 0o755)).To(Succeed())
	Expect(os.WriteFile(p, []byte(content), 0o644)).To(Succeed())
}

func readFile(path string) string {
	GinkgoHelper()
	b, err := os.ReadFile(path)
	Expect(err).NotTo(HaveOccurred())
	return string(b)
}

// writeRegistry renders a datasources_generated.go under root holding exactly the
// given constructors, using the real serializer so the fixture matches production.
func writeRegistry(root string, constructors ...string) {
	GinkgoHelper()
	_, err := emit.SyncGeneratedDatasources(filepath.Join(root, fwDir, registryFile), constructors, false)
	Expect(err).NotTo(HaveOccurred())
}

func writeGenerationReport(root string, entries ...model.ArtifactReportEntry) string {
	GinkgoHelper()
	data, err := json.Marshal(model.RunReport{Artifacts: entries})
	Expect(err).NotTo(HaveOccurred())
	const rel = "generation-report.json"
	writeFile(root, rel, string(data))
	return filepath.Join(root, rel)
}

func writeEndpointTags(root string, tags map[string]string) {
	GinkgoHelper()
	path := filepath.Join(root, testsDir, providerTestFile)
	writeFile(root, filepath.Join(testsDir, providerTestFile), "package test\n\nvar testFiles2EndpointTags = map[string]string{\n}\n")
	keys := make([]string, 0, len(tags))
	for key := range tags {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		_, err := emit.InsertEndpointTag(path, key, tags[key], false)
		Expect(err).NotTo(HaveOccurred())
	}
}

// dataSourceContent is a minimal generated-file body declaring one constructor;
// split copies it verbatim and never parses it (except a base file for overwrite
// attribution, which only needs the func declaration).
func dataSourceContent(constructor string) string {
	return "// Code generated by tfgen; DO NOT EDIT.\npackage fwprovider\n\nfunc " + constructor + "() {}\n"
}

// providerFileContent renders a framework_provider.go whose hand-written
// Datasources slice lists the given constructors.
func providerFileContent(constructors ...string) string {
	var b strings.Builder
	b.WriteString("package fwprovider\n\n")
	b.WriteString(datasourcesSliceHeader + "\n")
	for _, c := range constructors {
		b.WriteString("\t")
		b.WriteString(c)
		b.WriteString(",\n")
	}
	b.WriteString("}\n")
	return b.String()
}

var _ = Describe("Split", func() {
	var base, gen, out string

	BeforeEach(func() {
		base = GinkgoT().TempDir()
		gen = GinkgoT().TempDir()
		out = GinkgoT().TempDir()
	})

	It("routes a single net-new artifact into its own bundle with the registry reconstructed as base plus itself", func() {
		writeRegistry(base) // empty
		ctor := emit.DatasourceConstructor("rum_applications")
		writeFile(gen, filepath.Join(fwDir, dsFileName("rum_applications")), dataSourceContent(ctor))
		writeRegistry(gen, ctor)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Errors).To(BeEmpty())
		Expect(rep.Artifacts).To(HaveLen(1))

		art := rep.Artifacts[0]
		Expect(art.Name).To(Equal("rum_applications"))
		Expect(art.Status).To(Equal(model.ArtifactStatusCreated))
		Expect(art.Files).To(ConsistOf(
			filepath.Join(fwDir, dsFileName("rum_applications")),
			filepath.Join(fwDir, registryFile),
		))

		routedReg := readFile(filepath.Join(out, "rum_applications", fwDir, registryFile))
		Expect(routedReg).To(ContainSubstring(ctor))
		routedSrc := readFile(filepath.Join(out, "rum_applications", fwDir, dsFileName("rum_applications")))
		Expect(routedSrc).To(Equal(dataSourceContent(ctor)), "source file must be copied verbatim")
	})

	It("ignores unrelated repository drift outside the provider and docs scopes", func() {
		writeFile(base, "README.md", "older base content\n")
		writeFile(gen, "README.md", "newer generated-branch content\n")
		writeFile(base, "scripts/removed_upstream.sh", "removed after the branch was cut\n")
		writeFile(gen, "config/new_upstream.yaml", "added after the branch was cut\n")
		writeFile(base, filepath.Join(testsDir, "unrelated_test.go"), "package test\n// old\n")
		writeFile(gen, filepath.Join(testsDir, "unrelated_test.go"), "package test\n// new\n")
		writeFile(base, filepath.Join(testsDir, "cassettes", "unrelated.yaml"), "old cassette\n")

		writeRegistry(base)
		ctor := emit.DatasourceConstructor("rum_applications")
		writeFile(gen, filepath.Join(fwDir, dsFileName("rum_applications")), dataSourceContent(ctor))
		writeRegistry(gen, ctor)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Errors).To(BeEmpty())
		Expect(rep.Artifacts).To(HaveLen(1))
		Expect(rep.Artifacts[0].Name).To(Equal("rum_applications"))
	})

	It("continues to fail loud on unexpected changes inside the scoped docs path", func() {
		writeRegistry(base)
		ctor := emit.DatasourceConstructor("rum_applications")
		writeFile(gen, filepath.Join(fwDir, dsFileName("rum_applications")), dataSourceContent(ctor))
		writeRegistry(gen, ctor)
		writeFile(gen, filepath.Join("docs", "data-sources", "unexpected.md"), "unexpected upstream docs\n")

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).To(HaveOccurred())
		Expect(rep.Errors).To(ContainElement(ContainSubstring(filepath.Join("docs", "data-sources", "unexpected.md"))))
	})

	It("gives each artifact of a multi-artifact push its own bundle whose registry holds base plus only that artifact", func() {
		existing := emit.DatasourceConstructor("existing")
		writeRegistry(base, existing) // base already has one generated data source

		names := []string{"alpha", "bravo", "charlie"}
		ctors := map[string]string{}
		genSet := []string{existing}
		for _, n := range names {
			ctors[n] = emit.DatasourceConstructor(n)
			genSet = append(genSet, ctors[n])
			writeFile(gen, filepath.Join(fwDir, dsFileName(n)), dataSourceContent(ctors[n]))
		}
		writeRegistry(gen, genSet...)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(3))

		for _, n := range names {
			routedReg := readFile(filepath.Join(out, n, fwDir, registryFile))
			Expect(routedReg).To(ContainSubstring(existing), "each branch must preserve the base entry")
			Expect(routedReg).To(ContainSubstring(ctors[n]), "each branch must hold its own constructor")
			for _, other := range names {
				if other == n {
					continue
				}
				Expect(routedReg).NotTo(ContainSubstring(ctors[other]), "a branch must not carry a sibling's constructor")
			}
		}
	})

	It("routes generated tests and gives each artifact only its own endpoint tag", func() {
		writeRegistry(base)
		writeEndpointTags(base, nil)

		names := []string{"alpha", "bravo"}
		var entries []model.ArtifactReportEntry
		var constructors []string
		tags := map[string]string{}
		for _, name := range names {
			constructor := emit.DatasourceConstructor(name)
			constructors = append(constructors, constructor)
			writeFile(gen, filepath.Join(fwDir, dsFileName(name)), dataSourceContent(constructor))
			writeFile(gen, filepath.Join(testsDir, dsTestFileName(name)), "package test\n")
			tags[emit.EndpointTagTestKey(name)] = name + "-service"
			entries = append(entries,
				model.ArtifactReportEntry{
					Name: name, Kind: model.ArtifactKindDataSource, Status: model.ArtifactStatusCreated,
					Path:        filepath.Join(fwDir, dsFileName(name)),
					Diagnostics: []model.Diagnostic{{Severity: model.SeverityInfo, Message: name + " diagnostic"}},
				},
				model.ArtifactReportEntry{
					Name: name, Kind: model.ArtifactKindDataSource, Status: model.ArtifactStatusCreated,
					Path: filepath.Join(testsDir, dsTestFileName(name)),
				},
			)
		}
		writeRegistry(gen, constructors...)
		writeEndpointTags(gen, tags)
		reportPath := writeGenerationReport(gen, entries...)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out, GenerationReport: reportPath})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(2))

		for _, artifact := range rep.Artifacts {
			Expect(artifact.Files).To(ContainElement(filepath.Join(testsDir, dsTestFileName(artifact.Name))))
			Expect(artifact.Files).To(ContainElement(filepath.Join(testsDir, providerTestFile)))
			Expect(artifact.Diagnostics).To(ConsistOf(model.Diagnostic{Severity: model.SeverityInfo, Message: artifact.Name + " diagnostic"}))

			routedTags, err := emit.RegisteredEndpointTags(filepath.Join(out, artifact.Name, testsDir, providerTestFile))
			Expect(err).NotTo(HaveOccurred())
			Expect(routedTags).To(Equal(map[string]string{
				emit.EndpointTagTestKey(artifact.Name): artifact.Name + "-service",
			}))
		}
	})

	It("routes a test-only rollout as an updated artifact when its generated source is unchanged", func() {
		name := "existing"
		constructor := emit.DatasourceConstructor(name)
		sourceRel := filepath.Join(fwDir, dsFileName(name))
		source := dataSourceContent(constructor)
		writeFile(base, sourceRel, source)
		writeFile(gen, sourceRel, source)
		writeRegistry(base, constructor)
		writeRegistry(gen, constructor)
		writeEndpointTags(base, nil)
		writeEndpointTags(gen, map[string]string{emit.EndpointTagTestKey(name): "existing-service"})
		writeFile(gen, filepath.Join(testsDir, dsTestFileName(name)), "package test\n")
		reportPath := writeGenerationReport(gen,
			model.ArtifactReportEntry{Name: name, Kind: model.ArtifactKindDataSource, Status: model.ArtifactStatusUnchanged, Path: sourceRel},
			model.ArtifactReportEntry{Name: name, Kind: model.ArtifactKindDataSource, Status: model.ArtifactStatusCreated, Path: filepath.Join(testsDir, dsTestFileName(name))},
		)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out, GenerationReport: reportPath})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(1))
		Expect(rep.Artifacts[0].Status).To(Equal(model.ArtifactStatusUpdated))
		Expect(rep.Artifacts[0].Files).To(ConsistOf(
			filepath.Join(fwDir, registryFile),
			filepath.Join(testsDir, dsTestFileName(name)),
			filepath.Join(testsDir, providerTestFile),
		))
	})

	It("routes a retirement as exact file deletions plus reconstructed shared registrations", func() {
		name := "gone"
		constructor := emit.DatasourceConstructor(name)
		existing := emit.DatasourceConstructor("existing")
		sourceRel := filepath.Join(fwDir, dsFileName(name))
		testRel := filepath.Join(testsDir, dsTestFileName(name))
		docRel := filepath.Join("docs", "data-sources", name+".md")

		writeRegistry(base, existing, constructor)
		writeRegistry(gen, existing)
		writeFile(base, sourceRel, dataSourceContent(constructor))
		writeFile(base, testRel, "package test\n")
		writeFile(base, docRel, "# gone\n")
		writeEndpointTags(base, map[string]string{emit.EndpointTagTestKey(name): "gone-service"})
		writeEndpointTags(gen, nil)
		reportPath := writeGenerationReport(gen, model.ArtifactReportEntry{
			Name: name, Kind: model.ArtifactKindDataSource, Status: model.ArtifactStatusRetired, Path: sourceRel,
			Diagnostics: []model.Diagnostic{{Severity: model.SeverityInfo, Message: "safe to retire"}},
		})

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out, GenerationReport: reportPath})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(1))
		artifact := rep.Artifacts[0]
		Expect(artifact.Status).To(Equal(model.ArtifactStatusRetired))
		Expect(artifact.RemovedFiles).To(ConsistOf(sourceRel, testRel, docRel))
		Expect(artifact.Files).To(ConsistOf(
			filepath.Join(fwDir, registryFile),
			filepath.Join(testsDir, providerTestFile),
		))

		routedRegistry := readFile(filepath.Join(out, name, fwDir, registryFile))
		Expect(routedRegistry).NotTo(ContainSubstring(constructor))
		Expect(routedRegistry).To(ContainSubstring(existing))
		routedTags, err := emit.RegisteredEndpointTags(filepath.Join(out, name, testsDir, providerTestFile))
		Expect(err).NotTo(HaveOccurred())
		Expect(routedTags).NotTo(HaveKey(emit.EndpointTagTestKey(name)))
	})

	It("reports retire_blocked without materializing a deletion bundle", func() {
		name := "adopted"
		constructor := emit.DatasourceConstructor(name)
		sourceRel := filepath.Join(fwDir, dsFileName(name))
		source := dataSourceContent(constructor)
		writeRegistry(base, constructor)
		writeRegistry(gen, constructor)
		writeFile(base, sourceRel, source)
		writeFile(gen, sourceRel, source)
		reportPath := writeGenerationReport(gen, model.ArtifactReportEntry{
			Name: name, Kind: model.ArtifactKindDataSource, Status: model.ArtifactStatusRetireBlocked, Path: sourceRel,
			Diagnostics: []model.Diagnostic{{Severity: model.SeverityWarning, Message: "recorded cassette"}},
		})

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out, GenerationReport: reportPath})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(1))
		Expect(rep.Artifacts[0].Status).To(Equal(model.ArtifactStatusRetireBlocked))
		Expect(rep.Artifacts[0].Files).To(BeEmpty())
		Expect(rep.Artifacts[0].RemovedFiles).To(BeEmpty())
		_, statErr := os.Stat(filepath.Join(out, name))
		Expect(os.IsNotExist(statErr)).To(BeTrue())
	})

	It("routes a registration-only retirement as a registry edit with no file deletions", func() {
		ghostCtor := emit.DatasourceConstructor("ghost")
		existing := emit.DatasourceConstructor("existing")
		slug := emit.RegistrationRetirementName(ghostCtor)

		writeRegistry(base, existing, ghostCtor)
		writeRegistry(gen, existing)
		reportPath := writeGenerationReport(gen, model.ArtifactReportEntry{
			Name: slug, Kind: model.ArtifactKindDataSource,
			Status: model.ArtifactStatusRegistrationRetired, Constructor: ghostCtor,
			Diagnostics: []model.Diagnostic{{Severity: model.SeverityWarning, Message: "no generated file"}},
		})

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out, GenerationReport: reportPath})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Errors).To(BeEmpty())
		Expect(rep.Artifacts).To(HaveLen(1))
		artifact := rep.Artifacts[0]
		Expect(artifact.Status).To(Equal(model.ArtifactStatusRegistrationRetired))
		Expect(artifact.Name).To(Equal(slug))
		Expect(artifact.Files).To(ConsistOf(filepath.Join(fwDir, registryFile)))
		Expect(artifact.RemovedFiles).To(BeEmpty())

		routedRegistry := readFile(filepath.Join(out, slug, fwDir, registryFile))
		Expect(routedRegistry).NotTo(ContainSubstring(ghostCtor))
		Expect(routedRegistry).To(ContainSubstring(existing))
	})

	It("fails loud when the generation report contradicts the tree diff", func() {
		name := "mismatch"
		constructor := emit.DatasourceConstructor(name)
		sourceRel := filepath.Join(fwDir, dsFileName(name))
		source := dataSourceContent(constructor)
		writeRegistry(base, constructor)
		writeRegistry(gen, constructor)
		writeFile(base, sourceRel, source)
		writeFile(gen, sourceRel, source)
		reportPath := writeGenerationReport(gen, model.ArtifactReportEntry{
			Name: name, Kind: model.ArtifactKindDataSource, Status: model.ArtifactStatusCreated, Path: sourceRel,
		})

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out, GenerationReport: reportPath})
		Expect(err).To(HaveOccurred())
		Expect(rep.Errors).To(ContainElement(ContainSubstring("not newly added")))
	})

	It("fails loud on a changed file it cannot attribute to any artifact", func() {
		writeRegistry(base)
		writeFile(gen, filepath.Join(fwDir, registryFile), readFile(filepath.Join(base, fwDir, registryFile)))
		writeFile(gen, filepath.Join(fwDir, "surprise_helper.go"), "package fwprovider\n")

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).To(HaveOccurred())
		Expect(rep.Artifacts).To(BeEmpty())
		Expect(rep.Errors).To(ContainElement(ContainSubstring("surprise_helper.go")))
	})

	It("routes an overwrites artifact's framework_provider.go, removing only the retired constructor", func() {
		teamCtor := emit.DatasourceConstructor("team") // NewDatadogTeamDataSource
		neighbor := "NewDatadogTeamHierarchyLinksDataSource"

		// Base: a hand-written team data source, registered in the Datasources slice.
		writeRegistry(base)
		writeFile(base, filepath.Join(fwDir, providerFile), providerFileContent(teamCtor, neighbor))
		writeFile(base, filepath.Join(fwDir, dsFileName("team")), dataSourceContent(teamCtor))

		// Gen: generated team overwrote it — file rewritten, constructor moved from
		// the hand-written slice into the generated registry.
		writeFile(gen, filepath.Join(fwDir, providerFile), providerFileContent(neighbor))
		writeFile(gen, filepath.Join(fwDir, dsFileName("team")), dataSourceContent(teamCtor)+"// regenerated\n")
		writeRegistry(gen, teamCtor)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(1))
		Expect(rep.Artifacts[0].Status).To(Equal(model.ArtifactStatusUpdated))
		Expect(rep.Artifacts[0].Files).To(ContainElement(filepath.Join(fwDir, providerFile)))

		routedProvider := readFile(filepath.Join(out, "team", fwDir, providerFile))
		Expect(routedProvider).NotTo(ContainSubstring(teamCtor+","), "the overwritten constructor must be retired")
		Expect(routedProvider).To(ContainSubstring(neighbor), "neighbors must be left intact")
	})

	It("fails loud when a data source file changed but the registry did not", func() {
		writeRegistry(base)
		writeFile(gen, filepath.Join(fwDir, registryFile), readFile(filepath.Join(base, fwDir, registryFile)))
		ctor := emit.DatasourceConstructor("orphan")
		writeFile(gen, filepath.Join(fwDir, dsFileName("orphan")), dataSourceContent(ctor))

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).To(HaveOccurred())
		Expect(rep.Errors).To(ContainElement(ContainSubstring(registryFile)))
	})

	It("fails loud on a removed file, since retirement is out of scope for the create/update MVP", func() {
		writeRegistry(base)
		writeFile(base, filepath.Join(fwDir, dsFileName("gone")), dataSourceContent(emit.DatasourceConstructor("gone")))
		writeFile(gen, filepath.Join(fwDir, registryFile), readFile(filepath.Join(base, fwDir, registryFile)))

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out})
		Expect(err).To(HaveOccurred())
		Expect(rep.Errors).To(ContainElement(ContainSubstring("removed")))
	})

	It("writes no bundle in check mode but still reports the plan", func() {
		writeRegistry(base)
		ctor := emit.DatasourceConstructor("dryrun")
		writeFile(gen, filepath.Join(fwDir, dsFileName("dryrun")), dataSourceContent(ctor))
		writeRegistry(gen, ctor)

		rep, err := Split(Options{BaseDir: base, GeneratedDir: gen, OutDir: out, Check: true})
		Expect(err).NotTo(HaveOccurred())
		Expect(rep.Artifacts).To(HaveLen(1))
		_, statErr := os.Stat(filepath.Join(out, "dryrun"))
		Expect(os.IsNotExist(statErr)).To(BeTrue(), "check mode must not write bundles")
	})
})
