resources:
  pipelines:
    read: 
      method: get
      path: /api/v2/remote_config/products/obs_pipelines/pipelines/{pipeline_id}
    create: 
      method: post
      path: /api/v2/remote_config/products/obs_pipelines/pipelines
    update: 
      method: put
      path: /api/v2/remote_config/products/obs_pipelines/pipelines/{pipeline_id}
    delete:
      method: delete
      path: /api/v2/remote_config/products/obs_pipelines/pipelines/{pipeline_id}

