#!/usr/bin/env bash
# Generate the documentation using tfplugindocs and remove changes to files that shouldn't change

# Used in long pages that can't be rendered by the registry so we can link
# to the latest version of the full documentation on github
VERSION=$(git describe --tags --abbrev=0)

# Add here the files to be excluded from the doc generation
exclude_files=(
  "docs/resources/integration_aws_account.md"
  "docs/resources/compliance_custom_framework.md"
  "docs/resources/on_call_schedule.md"
  "docs/resources/on_call_team_routing_rules.md"
)

# Check if manual changes were made to any excluded files and exit
# otherwise these will be lost with `tfplugindocs`
if [ "${#exclude_files[@]}" -ne 0 ] && [ "$(git status --porcelain "${exclude_files[@]}")" ]; then
  echo "Uncommitted changes were detected to the following files. These aren't autogenerated, please commit or stash these changes and try again"
  echo $(git status --porcelain "${exclude_files[@]}")
  exit 1
fi

# FIRST PASS: full dump, *no* overrides
rm -rf docs_full
tfplugindocs generate \
  --rendered-website-dir docs_full \
  --website-source-dir blank_templates

# SECOND PASS: real site, *with* your stub‐templates
rm -rf docs
tfplugindocs generate \
  --rendered-website-dir docs \
  --website-source-dir templates

# Extract the full dashboard page
mkdir -p docs/resources
cp docs_full/resources/dashboard.md docs/resources/dashboard_full.md

# Cleanup
rm -rf docs_full

# Remove the changes to files we don't autogenerate
git checkout HEAD -- "${exclude_files[@]}"
