// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogRumApplicationsDataSource{}
)

type datadogRumApplicationsDataSourceModel struct {
	// Results
	ID              types.String               `tfsdk:"id"`
	RumApplications []*RumApplicationListModel `tfsdk:"rum_applications"`
}

type RumApplicationListModel struct {
	ApplicationId   types.String        `tfsdk:"application_id"`
	CreatedAt       types.Int64         `tfsdk:"created_at"`
	CreatedByHandle types.String        `tfsdk:"created_by_handle"`
	Hash            types.String        `tfsdk:"hash"`
	ID              types.String        `tfsdk:"id"`
	IsActive        types.Bool          `tfsdk:"is_active"`
	Name            types.String        `tfsdk:"name"`
	OrgId           types.Int64         `tfsdk:"org_id"`
	Type            types.String        `tfsdk:"type"`
	UpdatedAt       types.Int64         `tfsdk:"updated_at"`
	UpdatedByHandle types.String        `tfsdk:"updated_by_handle"`
	ProductScales   *ProductScalesModel `tfsdk:"product_scales"`
}

type ProductScalesModel struct {
	ProductAnalyticsRetentionScale *ProductAnalyticsRetentionScaleModel `tfsdk:"product_analytics_retention_scale"`
	RumEventProcessingScale        *RumEventProcessingScaleModel        `tfsdk:"rum_event_processing_scale"`
}

type ProductAnalyticsRetentionScaleModel struct {
	LastModifiedAt types.Int64  `tfsdk:"last_modified_at"`
	State          types.String `tfsdk:"state"`
}

type RumEventProcessingScaleModel struct {
	LastModifiedAt types.Int64  `tfsdk:"last_modified_at"`
	State          types.String `tfsdk:"state"`
}

type datadogRumApplicationsDataSource struct {
	Api  *datadogV2.RUMApi
	Auth context.Context
}

func NewDatadogRumApplicationsDataSource() datasource.DataSource {
	return &datadogRumApplicationsDataSource{}
}

func (d *datadogRumApplicationsDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetRumApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogRumApplicationsDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "rum_applications"
}

func (d *datadogRumApplicationsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog rum applications.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
		},
		Blocks: map[string]schema.Block{
			"rum_applications": schema.ListNestedBlock{
				Description: "RUM applications array response.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"application_id": schema.StringAttribute{
							Description: "ID of the RUM application.",
							Computed:    true,
						},
						"created_at": schema.Int64Attribute{
							Description: "Timestamp in ms of the creation date.",
							Computed:    true,
						},
						"created_by_handle": schema.StringAttribute{
							Description: "Handle of the creator user.",
							Computed:    true,
						},
						"hash": schema.StringAttribute{
							Description: "Hash of the RUM application. Optional.",
							Computed:    true,
						},
						"id": schema.StringAttribute{
							Description: "RUM application ID.",
							Computed:    true,
						},
						"is_active": schema.BoolAttribute{
							Description: "Indicates if the RUM application is active.",
							Computed:    true,
						},
						"name": schema.StringAttribute{
							Description: "Name of the RUM application.",
							Computed:    true,
						},
						"org_id": schema.Int64Attribute{
							Description: "Org ID of the RUM application.",
							Computed:    true,
						},
						"type": schema.StringAttribute{
							Description: "Type of the RUM application. Supported values are `browser`, `ios`, `android`, `react-native`, `flutter`, `roku`, `electron`, `unity`, `kotlin-multiplatform`.",
							Computed:    true,
						},
						"updated_at": schema.Int64Attribute{
							Description: "Timestamp in ms of the last update date.",
							Computed:    true,
						},
						"updated_by_handle": schema.StringAttribute{
							Description: "Handle of the updater user.",
							Computed:    true,
						},
					},
					Blocks: map[string]schema.Block{
						"product_scales": schema.SingleNestedBlock{
							Description: "Product Scales configuration for the RUM application.",

							Blocks: map[string]schema.Block{
								"product_analytics_retention_scale": schema.SingleNestedBlock{
									Description: "Product Analytics retention scale configuration.",

									Attributes: map[string]schema.Attribute{
										"last_modified_at": schema.Int64Attribute{
											Description: "Timestamp in milliseconds when this scale was last modified.",
											Computed:    true,
										},
										"state": schema.StringAttribute{
											Description: "Controls the retention policy for Product Analytics data derived from RUM events.",
											Computed:    true,
										},
									},
								},

								"rum_event_processing_scale": schema.SingleNestedBlock{
									Description: "RUM event processing scale configuration.",

									Attributes: map[string]schema.Attribute{
										"last_modified_at": schema.Int64Attribute{
											Description: "Timestamp in milliseconds when this scale was last modified.",
											Computed:    true,
										},
										"state": schema.StringAttribute{
											Description: "Configures which RUM events are processed and stored for the application.",
											Computed:    true,
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (d *datadogRumApplicationsDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogRumApplicationsDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var items []datadogV2.RUMApplicationList
	resp, _, err := d.Api.GetRUMApplications(d.Auth)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "Error when calling `GetRUMApplications`"))
		return
	}
	items = append(items, resp.Data...)

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogRumApplicationsDataSource) updateState(state *datadogRumApplicationsDataSourceModel, data *[]datadogV2.RUMApplicationList) {
	results := make([]*RumApplicationListModel, 0, len(*data))
	for _, item := range *data {
		r := RumApplicationListModel{
			ApplicationId:   types.StringValue(item.Attributes.GetApplicationId()),
			CreatedAt:       types.Int64Value(int64(item.Attributes.GetCreatedAt())),
			CreatedByHandle: types.StringValue(item.Attributes.GetCreatedByHandle()),
			Hash:            types.StringValue(item.Attributes.GetHash()),
			ID:              types.StringValue(item.GetId()),
			IsActive:        types.BoolValue(item.Attributes.GetIsActive()),
			Name:            types.StringValue(item.Attributes.GetName()),
			OrgId:           types.Int64Value(int64(item.Attributes.GetOrgId())),
			Type:            types.StringValue(item.Attributes.GetType()),
			UpdatedAt:       types.Int64Value(int64(item.Attributes.GetUpdatedAt())),
			UpdatedByHandle: types.StringValue(item.Attributes.GetUpdatedByHandle()),
		}
		if productScales, ok := item.Attributes.GetProductScalesOk(); ok && productScales != nil {
			productScalesModel := &ProductScalesModel{}
			if productAnalyticsRetentionScale, ok := productScales.GetProductAnalyticsRetentionScaleOk(); ok && productAnalyticsRetentionScale != nil {
				productAnalyticsRetentionScaleModel := &ProductAnalyticsRetentionScaleModel{}
				if lastModifiedAt, ok := productAnalyticsRetentionScale.GetLastModifiedAtOk(); ok && lastModifiedAt != nil {
					productAnalyticsRetentionScaleModel.LastModifiedAt = types.Int64Value(int64(*lastModifiedAt))
				}
				if stateValue, ok := productAnalyticsRetentionScale.GetStateOk(); ok && stateValue != nil {
					productAnalyticsRetentionScaleModel.State = types.StringValue(string(*stateValue))
				}
				productScalesModel.ProductAnalyticsRetentionScale = productAnalyticsRetentionScaleModel
			}
			if rumEventProcessingScale, ok := productScales.GetRumEventProcessingScaleOk(); ok && rumEventProcessingScale != nil {
				rumEventProcessingScaleModel := &RumEventProcessingScaleModel{}
				if lastModifiedAt, ok := rumEventProcessingScale.GetLastModifiedAtOk(); ok && lastModifiedAt != nil {
					rumEventProcessingScaleModel.LastModifiedAt = types.Int64Value(int64(*lastModifiedAt))
				}
				if stateValue, ok := rumEventProcessingScale.GetStateOk(); ok && stateValue != nil {
					rumEventProcessingScaleModel.State = types.StringValue(string(*stateValue))
				}
				productScalesModel.RumEventProcessingScale = rumEventProcessingScaleModel
			}
			r.ProductScales = productScalesModel
		}
		results = append(results, &r)
	}

	hashingData := "rum_applications"
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.RumApplications = results
}
