// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogApplicationKeysDataSource{}
)

type datadogApplicationKeysDataSourceModel struct {
	// Query Parameters
	Filter               types.String `tfsdk:"filter"`
	FilterCreatedAtEnd   types.String `tfsdk:"filter_created_at_end"`
	FilterCreatedAtStart types.String `tfsdk:"filter_created_at_start"`
	FilterOwnedBy        types.String `tfsdk:"filter_owned_by"`
	Include              types.String `tfsdk:"include"`
	PageNumber           types.Int64  `tfsdk:"page_number"`
	PageSize             types.Int64  `tfsdk:"page_size"`

	// Results
	ID              types.String                  `tfsdk:"id"`
	ApplicationKeys []*PartialApplicationKeyModel `tfsdk:"application_keys"`
}

type PartialApplicationKeyModel struct {
	ID         types.String `tfsdk:"id"`
	Last4      types.String `tfsdk:"last4"`
	LastUsedAt types.String `tfsdk:"last_used_at"`
	Name       types.String `tfsdk:"name"`
	Scopes     types.List   `tfsdk:"scopes"`
}

type datadogApplicationKeysDataSource struct {
	Api  *datadogV2.KeyManagementApi
	Auth context.Context
}

func NewDatadogApplicationKeysDataSource() datasource.DataSource {
	return &datadogApplicationKeysDataSource{}
}

func (d *datadogApplicationKeysDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetKeyManagementApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogApplicationKeysDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "application_keys"
}

func (d *datadogApplicationKeysDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog application keys.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"filter": schema.StringAttribute{
				Description: "Filter application keys by the specified string.",
				Optional:    true,
			},
			"filter_created_at_end": schema.StringAttribute{
				Description: "Only include application keys created on or before the specified date.",
				Optional:    true,
			},
			"filter_created_at_start": schema.StringAttribute{
				Description: "Only include application keys created on or after the specified date.",
				Optional:    true,
			},
			"filter_owned_by": schema.StringAttribute{
				Description: "Filter application keys by owner ID.",
				Optional:    true,
			},
			"include": schema.StringAttribute{
				Description: "Resource path for related resources to include in the response. Only `owned_by` is supported.",
				Optional:    true,
			},
			"page_number": schema.Int64Attribute{
				Description: "Specific page number to return.",
				Optional:    true,
			},
			"page_size": schema.Int64Attribute{
				Description: "Size for a given page. The maximum allowed value is 100.",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"application_keys": schema.ListNestedBlock{
				Description: "Array of application keys.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description: "ID of the application key.",
							Computed:    true,
						},
						"last4": schema.StringAttribute{
							Description: "The last four characters of the application key.",
							Computed:    true,
						},
						"last_used_at": schema.StringAttribute{
							Description: "Last usage timestamp of the application key.",
							Computed:    true,
						},
						"name": schema.StringAttribute{
							Description: "Name of the application key.",
							Computed:    true,
						},
						"scopes": schema.ListAttribute{
							Description: "Array of scopes to grant the application key.",
							ElementType: types.StringType,
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *datadogApplicationKeysDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogApplicationKeysDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var optionalParams datadogV2.ListApplicationKeysOptionalParameters
	if !state.Filter.IsNull() {
		optionalParams.Filter = state.Filter.ValueStringPointer()
	}
	if !state.FilterCreatedAtEnd.IsNull() {
		optionalParams.FilterCreatedAtEnd = state.FilterCreatedAtEnd.ValueStringPointer()
	}
	if !state.FilterCreatedAtStart.IsNull() {
		optionalParams.FilterCreatedAtStart = state.FilterCreatedAtStart.ValueStringPointer()
	}
	if !state.FilterOwnedBy.IsNull() {
		optionalParams.FilterOwnedBy = state.FilterOwnedBy.ValueStringPointer()
	}
	if !state.Include.IsNull() {
		optionalParams.Include = state.Include.ValueStringPointer()
	}
	if !state.PageNumber.IsNull() {
		optionalParams.PageNumber = state.PageNumber.ValueInt64Pointer()
	}
	if !state.PageSize.IsNull() {
		optionalParams.PageSize = state.PageSize.ValueInt64Pointer()
	}

	var items []datadogV2.PartialApplicationKey
	resp, _, err := d.Api.ListApplicationKeys(d.Auth, optionalParams)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "Error when calling `ListApplicationKeys`"))
		return
	}
	items = append(items, resp.Data...)

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogApplicationKeysDataSource) updateState(state *datadogApplicationKeysDataSourceModel, data *[]datadogV2.PartialApplicationKey) {
	results := make([]*PartialApplicationKeyModel, 0, len(*data))
	for _, item := range *data {
		r := PartialApplicationKeyModel{
			ID:         types.StringValue(item.GetId()),
			Last4:      types.StringValue(item.Attributes.GetLast4()),
			LastUsedAt: types.StringValue(item.Attributes.GetLastUsedAt()),
			Name:       types.StringValue(item.Attributes.GetName()),
		}
		if scopes, ok := item.Attributes.GetScopesOk(); ok && scopes != nil {
			r.Scopes, _ = types.ListValueFrom(context.Background(), types.StringType, *scopes)
		} else {
			r.Scopes = types.ListNull(types.StringType)
		}
		results = append(results, &r)
	}

	hashingData := fmt.Sprintf("%s:%s:%s:%s:%s:%d:%d", state.Filter.ValueString(), state.FilterCreatedAtEnd.ValueString(), state.FilterCreatedAtStart.ValueString(), state.FilterOwnedBy.ValueString(), state.Include.ValueString(), state.PageNumber.ValueInt64(), state.PageSize.ValueInt64())
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.ApplicationKeys = results
}
