// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogUserDataSource{}
)

type datadogUserDataSourceModel struct {
	// Datasource ID
	ID types.String `tfsdk:"id"`

	// Query Parameters
	Filter       types.String `tfsdk:"filter"`
	FilterStatus types.String `tfsdk:"filter_status"`
	Sort         types.String `tfsdk:"sort"`

	// Computed values
	CreatedAt      types.String `tfsdk:"created_at"`
	Disabled       types.Bool   `tfsdk:"disabled"`
	Email          types.String `tfsdk:"email"`
	Handle         types.String `tfsdk:"handle"`
	Icon           types.String `tfsdk:"icon"`
	LastLoginTime  types.String `tfsdk:"last_login_time"`
	MfaEnabled     types.Bool   `tfsdk:"mfa_enabled"`
	ModifiedAt     types.String `tfsdk:"modified_at"`
	Name           types.String `tfsdk:"name"`
	ServiceAccount types.Bool   `tfsdk:"service_account"`
	Status         types.String `tfsdk:"status"`
	Title          types.String `tfsdk:"title"`
	Uuid           types.String `tfsdk:"uuid"`
	Verified       types.Bool   `tfsdk:"verified"`
}

type datadogUserDataSource struct {
	Api  *datadogV2.UsersApi
	Auth context.Context
}

func NewDatadogUserDataSource() datasource.DataSource {
	return &datadogUserDataSource{}
}

func (d *datadogUserDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetUsersApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogUserDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "user"
}

func (d *datadogUserDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about an existing Datadog user.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"filter": schema.StringAttribute{
				Description: "Filter all users by the given string. Defaults to no filtering.",
				Optional:    true,
			},
			"filter_status": schema.StringAttribute{
				Description: "Filter on status attribute.\nComma separated list, with possible values `Active`, `Pending`, and `Disabled`.\nDefaults to no filtering.",
				Optional:    true,
			},
			"sort": schema.StringAttribute{
				Description: "User attribute to order results by. Sort order is ascending by default.\nSort order is descending if the field\nis prefixed by a negative sign, for example `sort=-name`. Options: `name`,\n`modified_at`, `user_count`.",
				Optional:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "The ISO 8601 timestamp of when the user account was created.",
				Computed:    true,
			},
			"disabled": schema.BoolAttribute{
				Description: "Whether the user account is deactivated. Disabled users cannot log in.",
				Computed:    true,
			},
			"email": schema.StringAttribute{
				Description: "The email address of the user, used for login and notifications.",
				Computed:    true,
			},
			"handle": schema.StringAttribute{
				Description: "The unique handle (username) of the user, typically matching their email prefix.",
				Computed:    true,
			},
			"icon": schema.StringAttribute{
				Description: "URL of the user's profile icon, typically a Gravatar URL derived from the email address.",
				Computed:    true,
			},
			"last_login_time": schema.StringAttribute{
				Description: "The ISO 8601 timestamp of the user's most recent login, or null if the user has never logged in.",
				Computed:    true,
			},
			"mfa_enabled": schema.BoolAttribute{
				Description: "Whether multi-factor authentication (MFA) is enabled for the user's account.",
				Computed:    true,
			},
			"modified_at": schema.StringAttribute{
				Description: "The ISO 8601 timestamp of when the user account was last modified.",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "The full display name of the user as shown in the Datadog UI.",
				Computed:    true,
			},
			"service_account": schema.BoolAttribute{
				Description: "Whether this is a service account rather than a human user.\nService accounts are used for programmatic API access.",
				Computed:    true,
			},
			"status": schema.StringAttribute{
				Description: "The current status of the user account (for example, `Active`, `Pending`, or `Disabled`).",
				Computed:    true,
			},
			"title": schema.StringAttribute{
				Description: "The job title of the user (for example, \"Senior Engineer\" or \"Product Manager\").",
				Computed:    true,
			},
			"uuid": schema.StringAttribute{
				Description: "The globally unique identifier (UUID) of the user.",
				Computed:    true,
			},
			"verified": schema.BoolAttribute{
				Description: "Whether the user's email address has been verified.",
				Computed:    true,
			},
		},
	}
}

func (d *datadogUserDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogUserDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var optionalParams datadogV2.ListUsersOptionalParameters
	if !state.Filter.IsNull() {
		optionalParams.Filter = state.Filter.ValueStringPointer()
	}
	if !state.FilterStatus.IsNull() {
		optionalParams.FilterStatus = state.FilterStatus.ValueStringPointer()
	}
	if !state.Sort.IsNull() {
		optionalParams.Sort = state.Sort.ValueStringPointer()
	}

	var items []datadogV2.User
	result, cancel := d.Api.ListUsersWithPagination(d.Auth, optionalParams)
	defer cancel()
	for paginationResult := range result {
		if paginationResult.Error != nil {
			response.Diagnostics.Append(utils.FrameworkErrorDiag(paginationResult.Error, "Error when calling `ListUsersWithPagination`"))
			return
		}
		items = append(items, paginationResult.Item)
	}

	if len(items) == 0 {
		response.Diagnostics.AddError("filters returned no results", "")
		return
	}
	if len(items) > 1 {
		response.Diagnostics.AddError("filters returned more than one result, use more specific search criteria", "")
		return
	}
	d.updateState(&state, items[0])

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogUserDataSource) updateState(state *datadogUserDataSourceModel, data datadogV2.User) {
	attributes := data.GetAttributes()
	if id, ok := data.GetIdOk(); ok && id != nil {
		state.ID = types.StringValue(*id)
	}
	if createdAt, ok := attributes.GetCreatedAtOk(); ok && createdAt != nil {
		state.CreatedAt = types.StringValue(createdAt.String())
	}
	if disabled, ok := attributes.GetDisabledOk(); ok && disabled != nil {
		state.Disabled = types.BoolValue(*disabled)
	}
	if email, ok := attributes.GetEmailOk(); ok && email != nil {
		state.Email = types.StringValue(*email)
	}
	if handle, ok := attributes.GetHandleOk(); ok && handle != nil {
		state.Handle = types.StringValue(*handle)
	}
	if icon, ok := attributes.GetIconOk(); ok && icon != nil {
		state.Icon = types.StringValue(*icon)
	}
	if lastLoginTime, ok := attributes.GetLastLoginTimeOk(); ok && lastLoginTime != nil {
		state.LastLoginTime = types.StringValue(lastLoginTime.String())
	}
	if mfaEnabled, ok := attributes.GetMfaEnabledOk(); ok && mfaEnabled != nil {
		state.MfaEnabled = types.BoolValue(*mfaEnabled)
	}
	if modifiedAt, ok := attributes.GetModifiedAtOk(); ok && modifiedAt != nil {
		state.ModifiedAt = types.StringValue(modifiedAt.String())
	}
	if name, ok := attributes.GetNameOk(); ok && name != nil {
		state.Name = types.StringValue(*name)
	}
	if serviceAccount, ok := attributes.GetServiceAccountOk(); ok && serviceAccount != nil {
		state.ServiceAccount = types.BoolValue(*serviceAccount)
	}
	if status, ok := attributes.GetStatusOk(); ok && status != nil {
		state.Status = types.StringValue(*status)
	}
	if title, ok := attributes.GetTitleOk(); ok && title != nil {
		state.Title = types.StringValue(*title)
	}
	if uuid, ok := attributes.GetUuidOk(); ok && uuid != nil {
		state.Uuid = types.StringValue(*uuid)
	}
	if verified, ok := attributes.GetVerifiedOk(); ok && verified != nil {
		state.Verified = types.BoolValue(*verified)
	}
}
