// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogDatastoresDataSource{}
)

type datadogDatastoresDataSourceModel struct {
	// Results
	ID         types.String          `tfsdk:"id"`
	Datastores []*DatastoreDataModel `tfsdk:"datastores"`
}

type DatastoreDataModel struct {
	CreatorUserId                types.Int64  `tfsdk:"creator_user_id"`
	CreatorUserUuid              types.String `tfsdk:"creator_user_uuid"`
	Description                  types.String `tfsdk:"description"`
	ID                           types.String `tfsdk:"id"`
	Name                         types.String `tfsdk:"name"`
	OrgId                        types.Int64  `tfsdk:"org_id"`
	PrimaryColumnName            types.String `tfsdk:"primary_column_name"`
	PrimaryKeyGenerationStrategy types.String `tfsdk:"primary_key_generation_strategy"`
}

type datadogDatastoresDataSource struct {
	Api  *datadogV2.ActionsDatastoresApi
	Auth context.Context
}

func NewDatadogDatastoresDataSource() datasource.DataSource {
	return &datadogDatastoresDataSource{}
}

func (d *datadogDatastoresDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetActionsDatastoresApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogDatastoresDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "datastores"
}

func (d *datadogDatastoresDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog datastores.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
		},
		Blocks: map[string]schema.Block{
			"datastores": schema.ListNestedBlock{
				Description: "An array of datastore objects containing their configurations and metadata.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"creator_user_id": schema.Int64Attribute{
							Description: "The numeric ID of the user who created the datastore.",
							Computed:    true,
						},
						"creator_user_uuid": schema.StringAttribute{
							Description: "The UUID of the user who created the datastore.",
							Computed:    true,
						},
						"description": schema.StringAttribute{
							Description: "A human-readable description about the datastore.",
							Computed:    true,
						},
						"id": schema.StringAttribute{
							Description: "The unique identifier of the datastore.",
							Computed:    true,
						},
						"name": schema.StringAttribute{
							Description: "The display name of the datastore.",
							Computed:    true,
						},
						"org_id": schema.Int64Attribute{
							Description: "The ID of the organization that owns this datastore.",
							Computed:    true,
						},
						"primary_column_name": schema.StringAttribute{
							Description: "The name of the primary key column for this datastore. Primary column names:\n  - Must abide by both [PostgreSQL naming conventions](https://www.postgresql.org/docs/7.0/syntax525.htm)\n  - Cannot exceed 63 characters",
							Computed:    true,
						},
						"primary_key_generation_strategy": schema.StringAttribute{
							Description: "Can be set to `uuid` to automatically generate primary keys when new items are added. Default value is `none`, which requires you to supply a primary key for each new item.",
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *datadogDatastoresDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogDatastoresDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var items []datadogV2.DatastoreData
	resp, _, err := d.Api.ListDatastores(d.Auth)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "Error when calling `ListDatastores`"))
		return
	}
	items = append(items, resp.Data...)

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogDatastoresDataSource) updateState(state *datadogDatastoresDataSourceModel, data *[]datadogV2.DatastoreData) {
	results := make([]*DatastoreDataModel, 0, len(*data))
	for _, item := range *data {
		r := DatastoreDataModel{
			CreatorUserId:                types.Int64Value(int64(item.Attributes.GetCreatorUserId())),
			CreatorUserUuid:              types.StringValue(item.Attributes.GetCreatorUserUuid()),
			Description:                  types.StringValue(item.Attributes.GetDescription()),
			ID:                           types.StringValue(item.GetId()),
			Name:                         types.StringValue(item.Attributes.GetName()),
			OrgId:                        types.Int64Value(int64(item.Attributes.GetOrgId())),
			PrimaryColumnName:            types.StringValue(item.Attributes.GetPrimaryColumnName()),
			PrimaryKeyGenerationStrategy: types.StringValue(string(item.Attributes.GetPrimaryKeyGenerationStrategy())),
		}
		results = append(results, &r)
	}

	hashingData := "datastores"
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.Datastores = results
}
