// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogAuthnMappingsDataSource{}
)

type datadogAuthnMappingsDataSourceModel struct {
	// Query Parameters
	Filter     types.String `tfsdk:"filter"`
	PageNumber types.Int64  `tfsdk:"page_number"`
	PageSize   types.Int64  `tfsdk:"page_size"`

	// Results
	ID            types.String         `tfsdk:"id"`
	AuthnMappings []*AuthNMappingModel `tfsdk:"authn_mappings"`
}

type AuthNMappingModel struct {
	AttributeKey             types.String `tfsdk:"attribute_key"`
	AttributeValue           types.String `tfsdk:"attribute_value"`
	ID                       types.String `tfsdk:"id"`
	SamlAssertionAttributeId types.String `tfsdk:"saml_assertion_attribute_id"`
}

type datadogAuthnMappingsDataSource struct {
	Api  *datadogV2.AuthNMappingsApi
	Auth context.Context
}

func NewDatadogAuthnMappingsDataSource() datasource.DataSource {
	return &datadogAuthnMappingsDataSource{}
}

func (d *datadogAuthnMappingsDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetAuthNMappingsApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogAuthnMappingsDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "authn_mappings"
}

func (d *datadogAuthnMappingsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog AuthN mappings.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"filter": schema.StringAttribute{
				Description: "Filter all mappings by the given string.",
				Optional:    true,
			},
			"page_number": schema.Int64Attribute{
				Description: "Specific page number to return.",
				Optional:    true,
			},
			"page_size": schema.Int64Attribute{
				Description: "Size for a given page. The maximum allowed value is 100.",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"authn_mappings": schema.ListNestedBlock{
				Description: "Array of returned AuthN Mappings.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"attribute_key": schema.StringAttribute{
							Description: "Key portion of a key/value pair of the attribute sent from the Identity Provider.",
							Computed:    true,
						},
						"attribute_value": schema.StringAttribute{
							Description: "Value portion of a key/value pair of the attribute sent from the Identity Provider.",
							Computed:    true,
						},
						"id": schema.StringAttribute{
							Description: "ID of the AuthN Mapping.",
							Computed:    true,
						},
						"saml_assertion_attribute_id": schema.StringAttribute{
							Description: "The ID of the SAML assertion attribute.",
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *datadogAuthnMappingsDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogAuthnMappingsDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var optionalParams datadogV2.ListAuthNMappingsOptionalParameters
	if !state.Filter.IsNull() {
		optionalParams.Filter = state.Filter.ValueStringPointer()
	}
	if !state.PageNumber.IsNull() {
		optionalParams.PageNumber = state.PageNumber.ValueInt64Pointer()
	}
	if !state.PageSize.IsNull() {
		optionalParams.PageSize = state.PageSize.ValueInt64Pointer()
	}

	var items []datadogV2.AuthNMapping
	resp, _, err := d.Api.ListAuthNMappings(d.Auth, optionalParams)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "Error when calling `ListAuthNMappings`"))
		return
	}
	items = append(items, resp.Data...)

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogAuthnMappingsDataSource) updateState(state *datadogAuthnMappingsDataSourceModel, data *[]datadogV2.AuthNMapping) {
	results := make([]*AuthNMappingModel, 0, len(*data))
	for _, item := range *data {
		r := AuthNMappingModel{
			AttributeKey:             types.StringValue(item.Attributes.GetAttributeKey()),
			AttributeValue:           types.StringValue(item.Attributes.GetAttributeValue()),
			ID:                       types.StringValue(item.GetId()),
			SamlAssertionAttributeId: types.StringValue(item.Attributes.GetSamlAssertionAttributeId()),
		}
		results = append(results, &r)
	}

	hashingData := fmt.Sprintf("%s:%d:%d", state.Filter.ValueString(), state.PageNumber.ValueInt64(), state.PageSize.ValueInt64())
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.AuthnMappings = results
}
