// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogTeamsDataSource{}
)

type datadogTeamsDataSourceModel struct {
	// Query Parameters
	FilterKeyword types.String `tfsdk:"filter_keyword"`
	FilterMe      types.Bool   `tfsdk:"filter_me"`

	// Results
	ID    types.String `tfsdk:"id"`
	Teams []*TeamModel `tfsdk:"teams"`
}

type TeamModel struct {
	Avatar         types.String `tfsdk:"avatar"`
	Banner         types.Int64  `tfsdk:"banner"`
	CreatedAt      types.String `tfsdk:"created_at"`
	Description    types.String `tfsdk:"description"`
	Handle         types.String `tfsdk:"handle"`
	ID             types.String `tfsdk:"id"`
	IsManaged      types.Bool   `tfsdk:"is_managed"`
	LinkCount      types.Int64  `tfsdk:"link_count"`
	ModifiedAt     types.String `tfsdk:"modified_at"`
	Name           types.String `tfsdk:"name"`
	Summary        types.String `tfsdk:"summary"`
	UserCount      types.Int64  `tfsdk:"user_count"`
	HiddenModules  types.List   `tfsdk:"hidden_modules"`
	VisibleModules types.List   `tfsdk:"visible_modules"`
}

type datadogTeamsDataSource struct {
	Api  *datadogV2.TeamsApi
	Auth context.Context
}

func NewDatadogTeamsDataSource() datasource.DataSource {
	return &datadogTeamsDataSource{}
}

func (d *datadogTeamsDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetTeamsApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogTeamsDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "teams"
}

func (d *datadogTeamsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog teams.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"filter_keyword": schema.StringAttribute{
				Description: "Search query. Can be team name, team handle, or email of team member",
				Optional:    true,
			},
			"filter_me": schema.BoolAttribute{
				Description: "When true, only returns teams the current user belongs to",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"teams": schema.ListNestedBlock{
				Description: "Teams response data",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"avatar": schema.StringAttribute{
							Description: "Unicode representation of the avatar for the team, limited to a single grapheme",
							Computed:    true,
						},
						"banner": schema.Int64Attribute{
							Description: "Banner selection for the team",
							Computed:    true,
						},
						"created_at": schema.StringAttribute{
							Description: "Creation date of the team",
							Computed:    true,
						},
						"description": schema.StringAttribute{
							Description: "Free-form markdown description/content for the team's homepage",
							Computed:    true,
						},
						"handle": schema.StringAttribute{
							Description: "The team's identifier",
							Computed:    true,
						},
						"id": schema.StringAttribute{
							Description: "The team's identifier",
							Computed:    true,
						},
						"is_managed": schema.BoolAttribute{
							Description: "Whether the team is managed from an external source",
							Computed:    true,
						},
						"link_count": schema.Int64Attribute{
							Description: "The number of links belonging to the team",
							Computed:    true,
						},
						"modified_at": schema.StringAttribute{
							Description: "Modification date of the team",
							Computed:    true,
						},
						"name": schema.StringAttribute{
							Description: "The name of the team",
							Computed:    true,
						},
						"summary": schema.StringAttribute{
							Description: "A brief summary of the team, derived from the `description`",
							Computed:    true,
						},
						"user_count": schema.Int64Attribute{
							Description: "The number of users belonging to the team",
							Computed:    true,
						},
						"hidden_modules": schema.ListAttribute{
							Description: "Collection of hidden modules for the team",
							ElementType: types.StringType,
							Computed:    true,
						},
						"visible_modules": schema.ListAttribute{
							Description: "Collection of visible modules for the team",
							ElementType: types.StringType,
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *datadogTeamsDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogTeamsDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var optionalParams datadogV2.ListTeamsOptionalParameters
	if !state.FilterKeyword.IsNull() {
		optionalParams.FilterKeyword = state.FilterKeyword.ValueStringPointer()
	}
	if !state.FilterMe.IsNull() {
		optionalParams.FilterMe = state.FilterMe.ValueBoolPointer()
	}

	var items []datadogV2.Team
	result, cancel := d.Api.ListTeamsWithPagination(d.Auth, optionalParams)
	defer cancel()
	for paginationResult := range result {
		if paginationResult.Error != nil {
			response.Diagnostics.Append(utils.FrameworkErrorDiag(paginationResult.Error, "Error when calling `ListTeamsWithPagination`"))
			return
		}
		items = append(items, paginationResult.Item)
	}

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogTeamsDataSource) updateState(state *datadogTeamsDataSourceModel, data *[]datadogV2.Team) {
	results := make([]*TeamModel, 0, len(*data))
	for _, item := range *data {
		r := TeamModel{
			Avatar:      types.StringValue(item.Attributes.GetAvatar()),
			Banner:      types.Int64Value(int64(item.Attributes.GetBanner())),
			CreatedAt:   types.StringValue(item.Attributes.GetCreatedAt().String()),
			Description: types.StringValue(item.Attributes.GetDescription()),
			Handle:      types.StringValue(item.Attributes.GetHandle()),
			ID:          types.StringValue(item.GetId()),
			IsManaged:   types.BoolValue(item.Attributes.GetIsManaged()),
			LinkCount:   types.Int64Value(int64(item.Attributes.GetLinkCount())),
			ModifiedAt:  types.StringValue(item.Attributes.GetModifiedAt().String()),
			Name:        types.StringValue(item.Attributes.GetName()),
			Summary:     types.StringValue(item.Attributes.GetSummary()),
			UserCount:   types.Int64Value(int64(item.Attributes.GetUserCount())),
		}
		if hiddenModules, ok := item.Attributes.GetHiddenModulesOk(); ok && hiddenModules != nil {
			r.HiddenModules, _ = types.ListValueFrom(context.Background(), types.StringType, *hiddenModules)
		} else {
			r.HiddenModules = types.ListNull(types.StringType)
		}
		if visibleModules, ok := item.Attributes.GetVisibleModulesOk(); ok && visibleModules != nil {
			r.VisibleModules, _ = types.ListValueFrom(context.Background(), types.StringType, *visibleModules)
		} else {
			r.VisibleModules = types.ListNull(types.StringType)
		}
		results = append(results, &r)
	}

	hashingData := fmt.Sprintf("%s:%t", state.FilterKeyword.ValueString(), state.FilterMe.ValueBool())
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.Teams = results
}
