// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogIncidentTypeDataSource{}
)

type datadogIncidentTypeDataSourceModel struct {
	ID             types.String `tfsdk:"id"`
	CreatedAt      types.String `tfsdk:"created_at"`
	CreatedBy      types.String `tfsdk:"created_by"`
	Description    types.String `tfsdk:"description"`
	IsDefault      types.Bool   `tfsdk:"is_default"`
	LastModifiedBy types.String `tfsdk:"last_modified_by"`
	ModifiedAt     types.String `tfsdk:"modified_at"`
	Name           types.String `tfsdk:"name"`
	Prefix         types.String `tfsdk:"prefix"`
}

type datadogIncidentTypeDataSource struct {
	Api  *datadogV2.IncidentsApi
	Auth context.Context
}

func NewDatadogIncidentTypeDataSource() datasource.DataSource {
	return &datadogIncidentTypeDataSource{}
}

func (d *datadogIncidentTypeDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetIncidentsApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogIncidentTypeDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "incident_type"
}

func (d *datadogIncidentTypeDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about an existing Datadog incident type.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The ID of this incident_type data source.",
				Required:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "Timestamp when the incident type was created.",
				Computed:    true,
			},
			"created_by": schema.StringAttribute{
				Description: "A unique identifier that represents the user that created the incident type.",
				Computed:    true,
			},
			"description": schema.StringAttribute{
				Description: "Text that describes the incident type.",
				Computed:    true,
			},
			"is_default": schema.BoolAttribute{
				Description: "If true, this incident type will be used as the default incident type if a type is not specified during the creation of incident resources.",
				Computed:    true,
			},
			"last_modified_by": schema.StringAttribute{
				Description: "A unique identifier that represents the user that last modified the incident type.",
				Computed:    true,
			},
			"modified_at": schema.StringAttribute{
				Description: "Timestamp when the incident type was last modified.",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "The name of the incident type.",
				Computed:    true,
			},
			"prefix": schema.StringAttribute{
				Description: "The string that will be prepended to the incident title across the Datadog app.",
				Computed:    true,
			},
		},
	}
}

func (d *datadogIncidentTypeDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogIncidentTypeDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	resp, httpResp, err := d.Api.GetIncidentType(d.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			response.Diagnostics.AddError(
				"incident_type not found",
				fmt.Sprintf("incident_type with ID %s not found", state.ID.ValueString()),
			)
			return
		}
		response.Diagnostics.AddError(
			"Error reading incident_type",
			"Could not read incident_type, unexpected error: "+err.Error(),
		)
		return
	}

	d.updateState(&state, &resp)

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogIncidentTypeDataSource) updateState(state *datadogIncidentTypeDataSourceModel, resp *datadogV2.IncidentTypeResponse) {
	attributes := resp.Data.GetAttributes()
	if id, ok := resp.Data.GetIdOk(); ok && id != nil {
		state.ID = types.StringValue(*id)
	}
	if createdAt, ok := attributes.GetCreatedAtOk(); ok && createdAt != nil {
		state.CreatedAt = types.StringValue(createdAt.String())
	}
	if createdBy, ok := attributes.GetCreatedByOk(); ok && createdBy != nil {
		state.CreatedBy = types.StringValue(*createdBy)
	}
	if description, ok := attributes.GetDescriptionOk(); ok && description != nil {
		state.Description = types.StringValue(*description)
	}
	if isDefault, ok := attributes.GetIsDefaultOk(); ok && isDefault != nil {
		state.IsDefault = types.BoolValue(*isDefault)
	}
	if lastModifiedBy, ok := attributes.GetLastModifiedByOk(); ok && lastModifiedBy != nil {
		state.LastModifiedBy = types.StringValue(*lastModifiedBy)
	}
	if modifiedAt, ok := attributes.GetModifiedAtOk(); ok && modifiedAt != nil {
		state.ModifiedAt = types.StringValue(modifiedAt.String())
	}
	if name, ok := attributes.GetNameOk(); ok && name != nil {
		state.Name = types.StringValue(*name)
	}
	if prefix, ok := attributes.GetPrefixOk(); ok && prefix != nil {
		state.Prefix = types.StringValue(*prefix)
	}
}
