// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogAuthnMappingDataSource{}
)

type datadogAuthnMappingDataSourceModel struct {
	// Datasource ID
	ID types.String `tfsdk:"id"`

	// Query Parameters
	Filter     types.String `tfsdk:"filter"`
	PageNumber types.Int64  `tfsdk:"page_number"`
	PageSize   types.Int64  `tfsdk:"page_size"`

	// Computed values
	AttributeKey             types.String `tfsdk:"attribute_key"`
	AttributeValue           types.String `tfsdk:"attribute_value"`
	ModifiedAt               types.String `tfsdk:"modified_at"`
	SamlAssertionAttributeId types.String `tfsdk:"saml_assertion_attribute_id"`
}

type datadogAuthnMappingDataSource struct {
	Api  *datadogV2.AuthNMappingsApi
	Auth context.Context
}

func NewDatadogAuthnMappingDataSource() datasource.DataSource {
	return &datadogAuthnMappingDataSource{}
}

func (d *datadogAuthnMappingDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetAuthNMappingsApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogAuthnMappingDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "authn_mapping"
}

func (d *datadogAuthnMappingDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about an existing Datadog authn mapping.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The ID of this authn_mapping data source.",
				Optional:    true,
				Computed:    true,
			},
			"filter": schema.StringAttribute{
				Description: "Filter all mappings by the given string.",
				Optional:    true,
			},
			"page_number": schema.Int64Attribute{
				Description: "Specific page number to return.",
				Optional:    true,
			},
			"page_size": schema.Int64Attribute{
				Description: "Size for a given page. The maximum allowed value is 100.",
				Optional:    true,
			},
			"attribute_key": schema.StringAttribute{
				Description: "Key portion of a key/value pair of the attribute sent from the Identity Provider.",
				Computed:    true,
			},
			"attribute_value": schema.StringAttribute{
				Description: "Value portion of a key/value pair of the attribute sent from the Identity Provider.",
				Computed:    true,
			},
			"modified_at": schema.StringAttribute{
				Description: "Time of last AuthN Mapping modification.",
				Computed:    true,
			},
			"saml_assertion_attribute_id": schema.StringAttribute{
				Description: "The ID of the SAML assertion attribute.",
				Computed:    true,
			},
		},
	}
}

func (d *datadogAuthnMappingDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogAuthnMappingDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	if !state.ID.IsNull() {
		resp, _, err := d.Api.GetAuthNMapping(d.Auth, state.ID.ValueString())
		if err != nil {
			response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error reading authn_mapping"))
			return
		}

		d.updateState(&state, resp.GetData())
	} else {
		var optionalParams datadogV2.ListAuthNMappingsOptionalParameters
		if !state.Filter.IsNull() {
			optionalParams.Filter = state.Filter.ValueStringPointer()
		}
		if !state.PageNumber.IsNull() {
			optionalParams.PageNumber = state.PageNumber.ValueInt64Pointer()
		}
		if !state.PageSize.IsNull() {
			optionalParams.PageSize = state.PageSize.ValueInt64Pointer()
		}

		var items []datadogV2.AuthNMapping
		listResp, _, err := d.Api.ListAuthNMappings(d.Auth, optionalParams)
		if err != nil {
			response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "Error when calling `ListAuthNMappings`"))
			return
		}
		items = append(items, listResp.Data...)

		if len(items) == 0 {
			response.Diagnostics.AddError("filters returned no results", "")
			return
		}
		if len(items) > 1 {
			response.Diagnostics.AddError("filters returned more than one result, use more specific search criteria", "")
			return
		}
		d.updateState(&state, items[0])
	}

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogAuthnMappingDataSource) updateState(state *datadogAuthnMappingDataSourceModel, data datadogV2.AuthNMapping) {
	attributes := data.GetAttributes()
	if id, ok := data.GetIdOk(); ok && id != nil {
		state.ID = types.StringValue(*id)
	}
	if attributeKey, ok := attributes.GetAttributeKeyOk(); ok && attributeKey != nil {
		state.AttributeKey = types.StringValue(*attributeKey)
	}
	if attributeValue, ok := attributes.GetAttributeValueOk(); ok && attributeValue != nil {
		state.AttributeValue = types.StringValue(*attributeValue)
	}
	if modifiedAt, ok := attributes.GetModifiedAtOk(); ok && modifiedAt != nil {
		state.ModifiedAt = types.StringValue(modifiedAt.String())
	}
	if samlAssertionAttributeId, ok := attributes.GetSamlAssertionAttributeIdOk(); ok && samlAssertionAttributeId != nil {
		state.SamlAssertionAttributeId = types.StringValue(*samlAssertionAttributeId)
	}
}
