// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogApiKeyDataSource{}
)

type datadogApiKeyDataSourceModel struct {
	ID                      types.String `tfsdk:"id"`
	Category                types.String `tfsdk:"category"`
	CreatedAt               types.String `tfsdk:"created_at"`
	DateLastUsed            types.String `tfsdk:"date_last_used"`
	Key                     types.String `tfsdk:"key"`
	Last4                   types.String `tfsdk:"last4"`
	ModifiedAt              types.String `tfsdk:"modified_at"`
	Name                    types.String `tfsdk:"name"`
	RemoteConfigReadEnabled types.Bool   `tfsdk:"remote_config_read_enabled"`
}

type datadogApiKeyDataSource struct {
	Api  *datadogV2.KeyManagementApi
	Auth context.Context
}

func NewDatadogApiKeyDataSource() datasource.DataSource {
	return &datadogApiKeyDataSource{}
}

func (d *datadogApiKeyDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetKeyManagementApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogApiKeyDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "api_key"
}

func (d *datadogApiKeyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about an existing Datadog api key.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The ID of this api_key data source.",
				Required:    true,
			},
			"category": schema.StringAttribute{
				Description: "The category of the API key.",
				Computed:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "Creation date of the API key.",
				Computed:    true,
			},
			"date_last_used": schema.StringAttribute{
				Description: "Date the API Key was last used",
				Computed:    true,
			},
			"key": schema.StringAttribute{
				Description: "The API key.",
				Computed:    true,
			},
			"last4": schema.StringAttribute{
				Description: "The last four characters of the API key.",
				Computed:    true,
			},
			"modified_at": schema.StringAttribute{
				Description: "Date the API key was last modified.",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "Name of the API key.",
				Computed:    true,
			},
			"remote_config_read_enabled": schema.BoolAttribute{
				Description: "The remote config read enabled status.",
				Computed:    true,
			},
		},
	}
}

func (d *datadogApiKeyDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogApiKeyDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	resp, httpResp, err := d.Api.GetAPIKey(d.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			response.Diagnostics.AddError(
				"api_key not found",
				fmt.Sprintf("api_key with ID %s not found", state.ID.ValueString()),
			)
			return
		}
		response.Diagnostics.AddError(
			"Error reading api_key",
			"Could not read api_key, unexpected error: "+err.Error(),
		)
		return
	}

	d.updateState(&state, &resp)

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogApiKeyDataSource) updateState(state *datadogApiKeyDataSourceModel, resp *datadogV2.APIKeyResponse) {
	attributes := resp.Data.GetAttributes()
	if id, ok := resp.Data.GetIdOk(); ok && id != nil {
		state.ID = types.StringValue(*id)
	}
	if category, ok := attributes.GetCategoryOk(); ok && category != nil {
		state.Category = types.StringValue(*category)
	}
	if createdAt, ok := attributes.GetCreatedAtOk(); ok && createdAt != nil {
		state.CreatedAt = types.StringValue(createdAt.String())
	}
	if dateLastUsed, ok := attributes.GetDateLastUsedOk(); ok && dateLastUsed != nil {
		state.DateLastUsed = types.StringValue(dateLastUsed.String())
	}
	if key, ok := attributes.GetKeyOk(); ok && key != nil {
		state.Key = types.StringValue(*key)
	}
	if last4, ok := attributes.GetLast4Ok(); ok && last4 != nil {
		state.Last4 = types.StringValue(*last4)
	}
	if modifiedAt, ok := attributes.GetModifiedAtOk(); ok && modifiedAt != nil {
		state.ModifiedAt = types.StringValue(modifiedAt.String())
	}
	if name, ok := attributes.GetNameOk(); ok && name != nil {
		state.Name = types.StringValue(*name)
	}
	if remoteConfigReadEnabled, ok := attributes.GetRemoteConfigReadEnabledOk(); ok && remoteConfigReadEnabled != nil {
		state.RemoteConfigReadEnabled = types.BoolValue(*remoteConfigReadEnabled)
	}
}
