// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogTeamDataSource{}
)

type datadogTeamDataSourceModel struct {
	// Datasource ID
	ID types.String `tfsdk:"id"`

	// Query Parameters
	FilterKeyword types.String `tfsdk:"filter_keyword"`
	FilterMe      types.Bool   `tfsdk:"filter_me"`

	// Computed values
	Avatar         types.String `tfsdk:"avatar"`
	Banner         types.Int64  `tfsdk:"banner"`
	CreatedAt      types.String `tfsdk:"created_at"`
	Description    types.String `tfsdk:"description"`
	Handle         types.String `tfsdk:"handle"`
	HiddenModules  types.List   `tfsdk:"hidden_modules"`
	IsManaged      types.Bool   `tfsdk:"is_managed"`
	LinkCount      types.Int64  `tfsdk:"link_count"`
	ModifiedAt     types.String `tfsdk:"modified_at"`
	Name           types.String `tfsdk:"name"`
	Summary        types.String `tfsdk:"summary"`
	UserCount      types.Int64  `tfsdk:"user_count"`
	VisibleModules types.List   `tfsdk:"visible_modules"`
}

type datadogTeamDataSource struct {
	Api  *datadogV2.TeamsApi
	Auth context.Context
}

func NewDatadogTeamDataSource() datasource.DataSource {
	return &datadogTeamDataSource{}
}

func (d *datadogTeamDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetTeamsApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogTeamDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "team"
}

func (d *datadogTeamDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about an existing Datadog team.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The ID of this team data source.",
				Optional:    true,
				Computed:    true,
			},
			"filter_keyword": schema.StringAttribute{
				Description: "Search query. Can be team name, team handle, or email of team member",
				Optional:    true,
			},
			"filter_me": schema.BoolAttribute{
				Description: "When true, only returns teams the current user belongs to",
				Optional:    true,
			},
			"avatar": schema.StringAttribute{
				Description: "Unicode representation of the avatar for the team, limited to a single grapheme",
				Computed:    true,
			},
			"banner": schema.Int64Attribute{
				Description: "Banner selection for the team",
				Computed:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "Creation date of the team",
				Computed:    true,
			},
			"description": schema.StringAttribute{
				Description: "Free-form markdown description/content for the team's homepage",
				Computed:    true,
			},
			"handle": schema.StringAttribute{
				Description: "The team's identifier",
				Computed:    true,
			},
			"hidden_modules": schema.ListAttribute{
				Description: "Collection of hidden modules for the team",
				ElementType: types.StringType,
				Computed:    true,
			},
			"is_managed": schema.BoolAttribute{
				Description: "Whether the team is managed from an external source",
				Computed:    true,
			},
			"link_count": schema.Int64Attribute{
				Description: "The number of links belonging to the team",
				Computed:    true,
			},
			"modified_at": schema.StringAttribute{
				Description: "Modification date of the team",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "The name of the team",
				Computed:    true,
			},
			"summary": schema.StringAttribute{
				Description: "A brief summary of the team, derived from the `description`",
				Computed:    true,
			},
			"user_count": schema.Int64Attribute{
				Description: "The number of users belonging to the team",
				Computed:    true,
			},
			"visible_modules": schema.ListAttribute{
				Description: "Collection of visible modules for the team",
				ElementType: types.StringType,
				Computed:    true,
			},
		},
	}
}

func (d *datadogTeamDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogTeamDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	if !state.ID.IsNull() {
		resp, _, err := d.Api.GetTeam(d.Auth, state.ID.ValueString())
		if err != nil {
			response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error reading team"))
			return
		}

		d.updateState(&state, resp.GetData())
	} else {
		var optionalParams datadogV2.ListTeamsOptionalParameters
		if !state.FilterKeyword.IsNull() {
			optionalParams.FilterKeyword = state.FilterKeyword.ValueStringPointer()
		}
		if !state.FilterMe.IsNull() {
			optionalParams.FilterMe = state.FilterMe.ValueBoolPointer()
		}

		var items []datadogV2.Team
		result, cancel := d.Api.ListTeamsWithPagination(d.Auth, optionalParams)
		defer cancel()
		for paginationResult := range result {
			if paginationResult.Error != nil {
				response.Diagnostics.Append(utils.FrameworkErrorDiag(paginationResult.Error, "Error when calling `ListTeamsWithPagination`"))
				return
			}
			items = append(items, paginationResult.Item)
		}

		if len(items) == 0 {
			response.Diagnostics.AddError("filters returned no results", "")
			return
		}
		if len(items) > 1 {
			response.Diagnostics.AddError("filters returned more than one result, use more specific search criteria", "")
			return
		}
		d.updateState(&state, items[0])
	}

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogTeamDataSource) updateState(state *datadogTeamDataSourceModel, data datadogV2.Team) {
	attributes := data.GetAttributes()
	if id, ok := data.GetIdOk(); ok && id != nil {
		state.ID = types.StringValue(*id)
	}
	if avatar, ok := attributes.GetAvatarOk(); ok && avatar != nil {
		state.Avatar = types.StringValue(*avatar)
	}
	if banner, ok := attributes.GetBannerOk(); ok && banner != nil {
		state.Banner = types.Int64Value(int64(*banner))
	}
	if createdAt, ok := attributes.GetCreatedAtOk(); ok && createdAt != nil {
		state.CreatedAt = types.StringValue(createdAt.String())
	}
	if description, ok := attributes.GetDescriptionOk(); ok && description != nil {
		state.Description = types.StringValue(*description)
	}
	if handle, ok := attributes.GetHandleOk(); ok && handle != nil {
		state.Handle = types.StringValue(*handle)
	}
	if isManaged, ok := attributes.GetIsManagedOk(); ok && isManaged != nil {
		state.IsManaged = types.BoolValue(*isManaged)
	}
	if linkCount, ok := attributes.GetLinkCountOk(); ok && linkCount != nil {
		state.LinkCount = types.Int64Value(int64(*linkCount))
	}
	if modifiedAt, ok := attributes.GetModifiedAtOk(); ok && modifiedAt != nil {
		state.ModifiedAt = types.StringValue(modifiedAt.String())
	}
	if name, ok := attributes.GetNameOk(); ok && name != nil {
		state.Name = types.StringValue(*name)
	}
	if summary, ok := attributes.GetSummaryOk(); ok && summary != nil {
		state.Summary = types.StringValue(*summary)
	}
	if userCount, ok := attributes.GetUserCountOk(); ok && userCount != nil {
		state.UserCount = types.Int64Value(int64(*userCount))
	}
	if hiddenModules, ok := attributes.GetHiddenModulesOk(); ok && hiddenModules != nil {
		state.HiddenModules, _ = types.ListValueFrom(context.Background(), types.StringType, *hiddenModules)
	}
	if visibleModules, ok := attributes.GetVisibleModulesOk(); ok && visibleModules != nil {
		state.VisibleModules, _ = types.ListValueFrom(context.Background(), types.StringType, *visibleModules)
	}
}
