// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogUsersDataSource{}
)

type datadogUsersDataSourceModel struct {
	// Query Parameters
	Filter       types.String `tfsdk:"filter"`
	FilterStatus types.String `tfsdk:"filter_status"`
	Sort         types.String `tfsdk:"sort"`

	// Results
	ID    types.String `tfsdk:"id"`
	Users []*UserModel `tfsdk:"users"`
}

type UserModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	Disabled       types.Bool   `tfsdk:"disabled"`
	Email          types.String `tfsdk:"email"`
	Handle         types.String `tfsdk:"handle"`
	Icon           types.String `tfsdk:"icon"`
	ID             types.String `tfsdk:"id"`
	LastLoginTime  types.String `tfsdk:"last_login_time"`
	MfaEnabled     types.Bool   `tfsdk:"mfa_enabled"`
	ModifiedAt     types.String `tfsdk:"modified_at"`
	Name           types.String `tfsdk:"name"`
	ServiceAccount types.Bool   `tfsdk:"service_account"`
	Status         types.String `tfsdk:"status"`
	Title          types.String `tfsdk:"title"`
	Uuid           types.String `tfsdk:"uuid"`
	Verified       types.Bool   `tfsdk:"verified"`
}

type datadogUsersDataSource struct {
	Api  *datadogV2.UsersApi
	Auth context.Context
}

func NewDatadogUsersDataSource() datasource.DataSource {
	return &datadogUsersDataSource{}
}

func (d *datadogUsersDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetUsersApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogUsersDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "users"
}

func (d *datadogUsersDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog users.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"filter": schema.StringAttribute{
				Description: "Filter all users by the given string. Defaults to no filtering.",
				Optional:    true,
			},
			"filter_status": schema.StringAttribute{
				Description: "Filter on status attribute.\nComma separated list, with possible values `Active`, `Pending`, and `Disabled`.\nDefaults to no filtering.",
				Optional:    true,
			},
			"sort": schema.StringAttribute{
				Description: "User attribute to order results by. Sort order is ascending by default.\nSort order is descending if the field\nis prefixed by a negative sign, for example `sort=-name`. Options: `name`,\n`modified_at`, `user_count`.",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"users": schema.ListNestedBlock{
				Description: "Array of returned users.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Description: "The ISO 8601 timestamp of when the user account was created.",
							Computed:    true,
						},
						"disabled": schema.BoolAttribute{
							Description: "Whether the user account is deactivated. Disabled users cannot log in.",
							Computed:    true,
						},
						"email": schema.StringAttribute{
							Description: "The email address of the user, used for login and notifications.",
							Computed:    true,
						},
						"handle": schema.StringAttribute{
							Description: "The unique handle (username) of the user, typically matching their email prefix.",
							Computed:    true,
						},
						"icon": schema.StringAttribute{
							Description: "URL of the user's profile icon, typically a Gravatar URL derived from the email address.",
							Computed:    true,
						},
						"id": schema.StringAttribute{
							Description: "ID of the user.",
							Computed:    true,
						},
						"last_login_time": schema.StringAttribute{
							Description: "The ISO 8601 timestamp of the user's most recent login, or null if the user has never logged in.",
							Computed:    true,
						},
						"mfa_enabled": schema.BoolAttribute{
							Description: "Whether multi-factor authentication (MFA) is enabled for the user's account.",
							Computed:    true,
						},
						"modified_at": schema.StringAttribute{
							Description: "The ISO 8601 timestamp of when the user account was last modified.",
							Computed:    true,
						},
						"name": schema.StringAttribute{
							Description: "The full display name of the user as shown in the Datadog UI.",
							Computed:    true,
						},
						"service_account": schema.BoolAttribute{
							Description: "Whether this is a service account rather than a human user.\nService accounts are used for programmatic API access.",
							Computed:    true,
						},
						"status": schema.StringAttribute{
							Description: "The current status of the user account (for example, `Active`, `Pending`, or `Disabled`).",
							Computed:    true,
						},
						"title": schema.StringAttribute{
							Description: "The job title of the user (for example, \"Senior Engineer\" or \"Product Manager\").",
							Computed:    true,
						},
						"uuid": schema.StringAttribute{
							Description: "The globally unique identifier (UUID) of the user.",
							Computed:    true,
						},
						"verified": schema.BoolAttribute{
							Description: "Whether the user's email address has been verified.",
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *datadogUsersDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogUsersDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var optionalParams datadogV2.ListUsersOptionalParameters
	if !state.Filter.IsNull() {
		optionalParams.Filter = state.Filter.ValueStringPointer()
	}
	if !state.FilterStatus.IsNull() {
		optionalParams.FilterStatus = state.FilterStatus.ValueStringPointer()
	}
	if !state.Sort.IsNull() {
		optionalParams.Sort = state.Sort.ValueStringPointer()
	}

	var items []datadogV2.User
	result, cancel := d.Api.ListUsersWithPagination(d.Auth, optionalParams)
	defer cancel()
	for paginationResult := range result {
		if paginationResult.Error != nil {
			response.Diagnostics.Append(utils.FrameworkErrorDiag(paginationResult.Error, "Error when calling `ListUsersWithPagination`"))
			return
		}
		items = append(items, paginationResult.Item)
	}

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogUsersDataSource) updateState(state *datadogUsersDataSourceModel, data *[]datadogV2.User) {
	results := make([]*UserModel, 0, len(*data))
	for _, item := range *data {
		r := UserModel{
			CreatedAt:      types.StringValue(item.Attributes.GetCreatedAt().String()),
			Disabled:       types.BoolValue(item.Attributes.GetDisabled()),
			Email:          types.StringValue(item.Attributes.GetEmail()),
			Handle:         types.StringValue(item.Attributes.GetHandle()),
			Icon:           types.StringValue(item.Attributes.GetIcon()),
			ID:             types.StringValue(item.GetId()),
			LastLoginTime:  types.StringValue(item.Attributes.GetLastLoginTime().String()),
			MfaEnabled:     types.BoolValue(item.Attributes.GetMfaEnabled()),
			ModifiedAt:     types.StringValue(item.Attributes.GetModifiedAt().String()),
			Name:           types.StringValue(item.Attributes.GetName()),
			ServiceAccount: types.BoolValue(item.Attributes.GetServiceAccount()),
			Status:         types.StringValue(item.Attributes.GetStatus()),
			Title:          types.StringValue(item.Attributes.GetTitle()),
			Uuid:           types.StringValue(item.Attributes.GetUuid()),
			Verified:       types.BoolValue(item.Attributes.GetVerified()),
		}
		results = append(results, &r)
	}

	hashingData := fmt.Sprintf("%s:%s:%s", state.Filter.ValueString(), state.FilterStatus.ValueString(), state.Sort.ValueString())
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.Users = results
}
