// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogGcpUcConfigsDataSource{}
)

type datadogGcpUcConfigsDataSourceModel struct {
	// Results
	ID           types.String               `tfsdk:"id"`
	GcpUcConfigs []*GcpUsageCostConfigModel `tfsdk:"gcp_uc_configs"`
}

type GcpUsageCostConfigModel struct {
	AccountId         types.String `tfsdk:"account_id"`
	BucketName        types.String `tfsdk:"bucket_name"`
	Dataset           types.String `tfsdk:"dataset"`
	ExportPrefix      types.String `tfsdk:"export_prefix"`
	ExportProjectName types.String `tfsdk:"export_project_name"`
	ID                types.String `tfsdk:"id"`
	Months            types.Int64  `tfsdk:"months"`
	ProjectId         types.String `tfsdk:"project_id"`
	ServiceAccount    types.String `tfsdk:"service_account"`
	Status            types.String `tfsdk:"status"`
	StatusUpdatedAt   types.String `tfsdk:"status_updated_at"`
	ErrorMessages     types.List   `tfsdk:"error_messages"`
}

type datadogGcpUcConfigsDataSource struct {
	Api  *datadogV2.CloudCostManagementApi
	Auth context.Context
}

func NewDatadogGcpUcConfigsDataSource() datasource.DataSource {
	return &datadogGcpUcConfigsDataSource{}
}

func (d *datadogGcpUcConfigsDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetCloudCostManagementApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogGcpUcConfigsDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "gcp_uc_configs"
}

func (d *datadogGcpUcConfigsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog gcp uc configs.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
		},
		Blocks: map[string]schema.Block{
			"gcp_uc_configs": schema.ListNestedBlock{
				Description: "A Google Cloud Usage Cost config.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"account_id": schema.StringAttribute{
							Description: "The Google Cloud account ID.",
							Computed:    true,
						},
						"bucket_name": schema.StringAttribute{
							Description: "The Google Cloud bucket name used to store the Usage Cost export.",
							Computed:    true,
						},
						"dataset": schema.StringAttribute{
							Description: "The export dataset name used for the Google Cloud Usage Cost Report.",
							Computed:    true,
						},
						"export_prefix": schema.StringAttribute{
							Description: "The export prefix used for the Google Cloud Usage Cost Report.",
							Computed:    true,
						},
						"export_project_name": schema.StringAttribute{
							Description: "The name of the Google Cloud Usage Cost Report.",
							Computed:    true,
						},
						"id": schema.StringAttribute{
							Description: "The ID of the Google Cloud Usage Cost config.",
							Computed:    true,
						},
						"months": schema.Int64Attribute{
							Description: "The number of months the report has been backfilled.",
							Computed:    true,
						},
						"project_id": schema.StringAttribute{
							Description: "The `project_id` of the Google Cloud Usage Cost report.",
							Computed:    true,
						},
						"service_account": schema.StringAttribute{
							Description: "The unique Google Cloud service account email.",
							Computed:    true,
						},
						"status": schema.StringAttribute{
							Description: "The status of the Google Cloud Usage Cost config.",
							Computed:    true,
						},
						"status_updated_at": schema.StringAttribute{
							Description: "The timestamp when the Google Cloud Usage Cost config status was updated.",
							Computed:    true,
						},
						"error_messages": schema.ListAttribute{
							Description: "The error messages for the Google Cloud Usage Cost config.",
							ElementType: types.StringType,
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *datadogGcpUcConfigsDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogGcpUcConfigsDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var items []datadogV2.GCPUsageCostConfig
	resp, _, err := d.Api.ListCostGCPUsageCostConfigs(d.Auth)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "Error when calling `ListCostGCPUsageCostConfigs`"))
		return
	}
	items = append(items, resp.Data...)

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogGcpUcConfigsDataSource) updateState(state *datadogGcpUcConfigsDataSourceModel, data *[]datadogV2.GCPUsageCostConfig) {
	results := make([]*GcpUsageCostConfigModel, 0, len(*data))
	for _, item := range *data {
		r := GcpUsageCostConfigModel{
			AccountId:         types.StringValue(item.Attributes.GetAccountId()),
			BucketName:        types.StringValue(item.Attributes.GetBucketName()),
			Dataset:           types.StringValue(item.Attributes.GetDataset()),
			ExportPrefix:      types.StringValue(item.Attributes.GetExportPrefix()),
			ExportProjectName: types.StringValue(item.Attributes.GetExportProjectName()),
			ID:                types.StringValue(item.GetId()),
			Months:            types.Int64Value(int64(item.Attributes.GetMonths())),
			ProjectId:         types.StringValue(item.Attributes.GetProjectId()),
			ServiceAccount:    types.StringValue(item.Attributes.GetServiceAccount()),
			Status:            types.StringValue(item.Attributes.GetStatus()),
			StatusUpdatedAt:   types.StringValue(item.Attributes.GetStatusUpdatedAt()),
		}
		if errorMessages, ok := item.Attributes.GetErrorMessagesOk(); ok && errorMessages != nil {
			r.ErrorMessages, _ = types.ListValueFrom(context.Background(), types.StringType, *errorMessages)
		} else {
			r.ErrorMessages = types.ListNull(types.StringType)
		}
		results = append(results, &r)
	}

	hashingData := "gcp_uc_configs"
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.GcpUcConfigs = results
}
