// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogApiKeysDataSource{}
)

type datadogApiKeysDataSourceModel struct {
	// Query Parameters
	Filter                        types.String `tfsdk:"filter"`
	FilterCategory                types.String `tfsdk:"filter_category"`
	FilterCreatedAtEnd            types.String `tfsdk:"filter_created_at_end"`
	FilterCreatedAtStart          types.String `tfsdk:"filter_created_at_start"`
	FilterModifiedAtEnd           types.String `tfsdk:"filter_modified_at_end"`
	FilterModifiedAtStart         types.String `tfsdk:"filter_modified_at_start"`
	FilterRemoteConfigReadEnabled types.Bool   `tfsdk:"filter_remote_config_read_enabled"`
	Include                       types.String `tfsdk:"include"`
	PageNumber                    types.Int64  `tfsdk:"page_number"`
	PageSize                      types.Int64  `tfsdk:"page_size"`

	// Results
	ID      types.String          `tfsdk:"id"`
	ApiKeys []*PartialApiKeyModel `tfsdk:"api_keys"`
}

type PartialApiKeyModel struct {
	Category                types.String `tfsdk:"category"`
	DateLastUsed            types.String `tfsdk:"date_last_used"`
	ID                      types.String `tfsdk:"id"`
	Last4                   types.String `tfsdk:"last4"`
	Name                    types.String `tfsdk:"name"`
	RemoteConfigReadEnabled types.Bool   `tfsdk:"remote_config_read_enabled"`
}

type datadogApiKeysDataSource struct {
	Api  *datadogV2.KeyManagementApi
	Auth context.Context
}

func NewDatadogApiKeysDataSource() datasource.DataSource {
	return &datadogApiKeysDataSource{}
}

func (d *datadogApiKeysDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetKeyManagementApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogApiKeysDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "api_keys"
}

func (d *datadogApiKeysDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog API keys.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"filter": schema.StringAttribute{
				Description: "Filter API keys by the specified string.",
				Optional:    true,
			},
			"filter_category": schema.StringAttribute{
				Description: "Filter API keys by category.",
				Optional:    true,
			},
			"filter_created_at_end": schema.StringAttribute{
				Description: "Only include API keys created on or before the specified date.",
				Optional:    true,
			},
			"filter_created_at_start": schema.StringAttribute{
				Description: "Only include API keys created on or after the specified date.",
				Optional:    true,
			},
			"filter_modified_at_end": schema.StringAttribute{
				Description: "Only include API keys modified on or before the specified date.",
				Optional:    true,
			},
			"filter_modified_at_start": schema.StringAttribute{
				Description: "Only include API keys modified on or after the specified date.",
				Optional:    true,
			},
			"filter_remote_config_read_enabled": schema.BoolAttribute{
				Description: "Filter API keys by remote config read enabled status.",
				Optional:    true,
			},
			"include": schema.StringAttribute{
				Description: "Comma separated list of resource paths for related resources to include in the response. Supported resource paths are `created_by` and `modified_by`.",
				Optional:    true,
			},
			"page_number": schema.Int64Attribute{
				Description: "Specific page number to return.",
				Optional:    true,
			},
			"page_size": schema.Int64Attribute{
				Description: "Size for a given page. The maximum allowed value is 100.",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"api_keys": schema.ListNestedBlock{
				Description: "Array of API keys.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"category": schema.StringAttribute{
							Description: "The category of the API key.",
							Computed:    true,
						},
						"date_last_used": schema.StringAttribute{
							Description: "Date the API Key was last used.",
							Computed:    true,
						},
						"id": schema.StringAttribute{
							Description: "ID of the API key.",
							Computed:    true,
						},
						"last4": schema.StringAttribute{
							Description: "The last four characters of the API key.",
							Computed:    true,
						},
						"name": schema.StringAttribute{
							Description: "Name of the API key.",
							Computed:    true,
						},
						"remote_config_read_enabled": schema.BoolAttribute{
							Description: "The remote config read enabled status.",
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *datadogApiKeysDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogApiKeysDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var optionalParams datadogV2.ListAPIKeysOptionalParameters
	if !state.Filter.IsNull() {
		optionalParams.Filter = state.Filter.ValueStringPointer()
	}
	if !state.FilterCategory.IsNull() {
		optionalParams.FilterCategory = state.FilterCategory.ValueStringPointer()
	}
	if !state.FilterCreatedAtEnd.IsNull() {
		optionalParams.FilterCreatedAtEnd = state.FilterCreatedAtEnd.ValueStringPointer()
	}
	if !state.FilterCreatedAtStart.IsNull() {
		optionalParams.FilterCreatedAtStart = state.FilterCreatedAtStart.ValueStringPointer()
	}
	if !state.FilterModifiedAtEnd.IsNull() {
		optionalParams.FilterModifiedAtEnd = state.FilterModifiedAtEnd.ValueStringPointer()
	}
	if !state.FilterModifiedAtStart.IsNull() {
		optionalParams.FilterModifiedAtStart = state.FilterModifiedAtStart.ValueStringPointer()
	}
	if !state.FilterRemoteConfigReadEnabled.IsNull() {
		optionalParams.FilterRemoteConfigReadEnabled = state.FilterRemoteConfigReadEnabled.ValueBoolPointer()
	}
	if !state.Include.IsNull() {
		optionalParams.Include = state.Include.ValueStringPointer()
	}
	if !state.PageNumber.IsNull() {
		optionalParams.PageNumber = state.PageNumber.ValueInt64Pointer()
	}
	if !state.PageSize.IsNull() {
		optionalParams.PageSize = state.PageSize.ValueInt64Pointer()
	}

	var items []datadogV2.PartialAPIKey
	resp, _, err := d.Api.ListAPIKeys(d.Auth, optionalParams)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "Error when calling `ListAPIKeys`"))
		return
	}
	items = append(items, resp.Data...)

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogApiKeysDataSource) updateState(state *datadogApiKeysDataSourceModel, data *[]datadogV2.PartialAPIKey) {
	results := make([]*PartialApiKeyModel, 0, len(*data))
	for _, item := range *data {
		r := PartialApiKeyModel{
			Category:                types.StringValue(item.Attributes.GetCategory()),
			DateLastUsed:            types.StringValue(item.Attributes.GetDateLastUsed().String()),
			ID:                      types.StringValue(item.GetId()),
			Last4:                   types.StringValue(item.Attributes.GetLast4()),
			Name:                    types.StringValue(item.Attributes.GetName()),
			RemoteConfigReadEnabled: types.BoolValue(item.Attributes.GetRemoteConfigReadEnabled()),
		}
		results = append(results, &r)
	}

	hashingData := fmt.Sprintf("%s:%s:%s:%s:%s:%s:%t:%s:%d:%d", state.Filter.ValueString(), state.FilterCategory.ValueString(), state.FilterCreatedAtEnd.ValueString(), state.FilterCreatedAtStart.ValueString(), state.FilterModifiedAtEnd.ValueString(), state.FilterModifiedAtStart.ValueString(), state.FilterRemoteConfigReadEnabled.ValueBool(), state.Include.ValueString(), state.PageNumber.ValueInt64(), state.PageSize.ValueInt64())
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.ApiKeys = results
}
