// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ datasource.DataSourceWithConfigure = &datastoreDataSource{}
)

type datastoreDataSourceModel struct {
	ID                           types.String `tfsdk:"id"`
	CreatedAt                    types.String `tfsdk:"created_at"`
	CreatorUserId                types.Int64  `tfsdk:"creator_user_id"`
	CreatorUserUuid              types.String `tfsdk:"creator_user_uuid"`
	Description                  types.String `tfsdk:"description"`
	ModifiedAt                   types.String `tfsdk:"modified_at"`
	Name                         types.String `tfsdk:"name"`
	OrgId                        types.Int64  `tfsdk:"org_id"`
	PrimaryColumnName            types.String `tfsdk:"primary_column_name"`
	PrimaryKeyGenerationStrategy types.String `tfsdk:"primary_key_generation_strategy"`
}

type datastoreDataSource struct {
	Api  *datadogV2.ActionsDatastoresApi
	Auth context.Context
}

func NewDatadogDatastoreDataSource() datasource.DataSource {
	return &datastoreDataSource{}
}

func (d *datastoreDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetActionsDatastoresApiV2()
	d.Auth = providerData.Auth
}

func (d *datastoreDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "datastore"
}

func (d *datastoreDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about an existing Datadog datastore.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The ID of this datastore data source.",
				Required:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "Timestamp when the datastore was created.",
				Computed:    true,
			},
			"creator_user_id": schema.Int64Attribute{
				Description: "The numeric ID of the user who created the datastore.",
				Computed:    true,
			},
			"creator_user_uuid": schema.StringAttribute{
				Description: "The UUID of the user who created the datastore.",
				Computed:    true,
			},
			"description": schema.StringAttribute{
				Description: "A human-readable description about the datastore.",
				Computed:    true,
			},
			"modified_at": schema.StringAttribute{
				Description: "Timestamp when the datastore was last modified.",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "The display name of the datastore.",
				Computed:    true,
			},
			"org_id": schema.Int64Attribute{
				Description: "The ID of the organization that owns this datastore.",
				Computed:    true,
			},
			"primary_column_name": schema.StringAttribute{
				Description: "The name of the primary key column for this datastore. Primary column names:\n  - Must abide by both [PostgreSQL naming conventions](https://www.postgresql.org/docs/7.0/syntax525.htm)\n  - Cannot exceed 63 characters",
				Computed:    true,
			},
			"primary_key_generation_strategy": schema.StringAttribute{
				Description: "Can be set to `uuid` to automatically generate primary keys when new items are added. Default value is `none`, which requires you to supply a primary key for each new item.",
				Computed:    true,
			},
		},
	}
}

func (d *datastoreDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datastoreDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	resp, httpResp, err := d.Api.GetDatastore(d.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			response.Diagnostics.AddError(
				"datastore not found",
				fmt.Sprintf("datastore with ID %s not found", state.ID.ValueString()),
			)
			return
		}
		response.Diagnostics.AddError(
			"Error reading datastore",
			"Could not read datastore, unexpected error: "+err.Error(),
		)
		return
	}

	d.updateState(&state, &resp)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datastoreDataSource) updateState(state *datastoreDataSourceModel, resp *datadogV2.Datastore) {
	attributes := resp.Data.GetAttributes()
	state.ID = types.StringValue(resp.Data.GetId())
	state.CreatedAt = types.StringValue(attributes.GetCreatedAt().String())
	state.CreatorUserId = types.Int64Value(int64(attributes.GetCreatorUserId()))
	state.CreatorUserUuid = types.StringValue(attributes.GetCreatorUserUuid())
	state.Description = types.StringValue(attributes.GetDescription())
	state.ModifiedAt = types.StringValue(attributes.GetModifiedAt().String())
	state.Name = types.StringValue(attributes.GetName())
	state.OrgId = types.Int64Value(int64(attributes.GetOrgId()))
	state.PrimaryColumnName = types.StringValue(attributes.GetPrimaryColumnName())
	state.PrimaryKeyGenerationStrategy = types.StringValue(string(attributes.GetPrimaryKeyGenerationStrategy()))
}
