// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogDowntimesDataSource{}
)

type datadogDowntimesDataSourceModel struct {
	// Query Parameters
	CurrentOnly types.Bool   `tfsdk:"current_only"`
	Include     types.String `tfsdk:"include"`
	PageOffset  types.Int64  `tfsdk:"page_offset"`

	// Results
	ID        types.String                 `tfsdk:"id"`
	Downtimes []*DowntimeResponseDataModel `tfsdk:"downtimes"`
}

type DowntimeResponseDataModel struct {
	Canceled                      types.String `tfsdk:"canceled"`
	Created                       types.String `tfsdk:"created"`
	DisplayTimezone               types.String `tfsdk:"display_timezone"`
	ID                            types.String `tfsdk:"id"`
	Message                       types.String `tfsdk:"message"`
	Modified                      types.String `tfsdk:"modified"`
	MuteFirstRecoveryNotification types.Bool   `tfsdk:"mute_first_recovery_notification"`
	Scope                         types.String `tfsdk:"scope"`
	Status                        types.String `tfsdk:"status"`
	NotifyEndStates               types.List   `tfsdk:"notify_end_states"`
	NotifyEndTypes                types.List   `tfsdk:"notify_end_types"`
}

type datadogDowntimesDataSource struct {
	Api  *datadogV2.DowntimesApi
	Auth context.Context
}

func NewDatadogDowntimesDataSource() datasource.DataSource {
	return &datadogDowntimesDataSource{}
}

func (d *datadogDowntimesDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetDowntimesApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogDowntimesDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "downtimes"
}

func (d *datadogDowntimesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog downtimes.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"current_only": schema.BoolAttribute{
				Description: "Only return downtimes that are active when the request is made.",
				Optional:    true,
			},
			"include": schema.StringAttribute{
				Description: "Comma-separated list of resource paths for related resources to include in the response. Supported resource\npaths are `created_by` and `monitor`.",
				Optional:    true,
			},
			"page_offset": schema.Int64Attribute{
				Description: "Specific offset to use as the beginning of the returned page.",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"downtimes": schema.ListNestedBlock{
				Description: "An array of downtimes.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"canceled": schema.StringAttribute{
							Description: "Time that the downtime was canceled.",
							Computed:    true,
						},
						"created": schema.StringAttribute{
							Description: "Creation time of the downtime.",
							Computed:    true,
						},
						"display_timezone": schema.StringAttribute{
							Description: "The timezone in which to display the downtime's start and end times in Datadog applications. This is not used\nas an offset for scheduling.",
							Computed:    true,
						},
						"id": schema.StringAttribute{
							Description: "The downtime ID.",
							Computed:    true,
						},
						"message": schema.StringAttribute{
							Description: "A message to include with notifications for this downtime. Email notifications can be sent to specific users\nby using the same `@username` notation as events.",
							Computed:    true,
						},
						"modified": schema.StringAttribute{
							Description: "Time that the downtime was last modified.",
							Computed:    true,
						},
						"mute_first_recovery_notification": schema.BoolAttribute{
							Description: "If the first recovery notification during a downtime should be muted.",
							Computed:    true,
						},
						"scope": schema.StringAttribute{
							Description: "The scope to which the downtime applies. Must follow the [common search syntax](https://docs.datadoghq.com/logs/explorer/search_syntax/).",
							Computed:    true,
						},
						"status": schema.StringAttribute{
							Description: "The current status of the downtime.",
							Computed:    true,
						},
						"notify_end_states": schema.ListAttribute{
							Description: "States that will trigger a monitor notification when the `notify_end_types` action occurs.",
							ElementType: types.StringType,
							Computed:    true,
						},
						"notify_end_types": schema.ListAttribute{
							Description: "Actions that will trigger a monitor notification if the downtime is in the `notify_end_types` state.",
							ElementType: types.StringType,
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *datadogDowntimesDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogDowntimesDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var optionalParams datadogV2.ListDowntimesOptionalParameters
	if !state.CurrentOnly.IsNull() {
		optionalParams.CurrentOnly = state.CurrentOnly.ValueBoolPointer()
	}
	if !state.Include.IsNull() {
		optionalParams.Include = state.Include.ValueStringPointer()
	}
	if !state.PageOffset.IsNull() {
		optionalParams.PageOffset = state.PageOffset.ValueInt64Pointer()
	}

	var items []datadogV2.DowntimeResponseData
	result, cancel := d.Api.ListDowntimesWithPagination(d.Auth, optionalParams)
	defer cancel()
	for paginationResult := range result {
		if paginationResult.Error != nil {
			response.Diagnostics.Append(utils.FrameworkErrorDiag(paginationResult.Error, "Error when calling `ListDowntimesWithPagination`"))
			return
		}
		items = append(items, paginationResult.Item)
	}

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogDowntimesDataSource) updateState(state *datadogDowntimesDataSourceModel, data *[]datadogV2.DowntimeResponseData) {
	results := make([]*DowntimeResponseDataModel, 0, len(*data))
	for _, item := range *data {
		r := DowntimeResponseDataModel{
			Canceled:                      types.StringValue(item.Attributes.GetCanceled().String()),
			Created:                       types.StringValue(item.Attributes.GetCreated().String()),
			DisplayTimezone:               types.StringValue(item.Attributes.GetDisplayTimezone()),
			ID:                            types.StringValue(item.GetId()),
			Message:                       types.StringValue(item.Attributes.GetMessage()),
			Modified:                      types.StringValue(item.Attributes.GetModified().String()),
			MuteFirstRecoveryNotification: types.BoolValue(item.Attributes.GetMuteFirstRecoveryNotification()),
			Scope:                         types.StringValue(item.Attributes.GetScope()),
			Status:                        types.StringValue(string(item.Attributes.GetStatus())),
		}
		if notifyEndStates, ok := item.Attributes.GetNotifyEndStatesOk(); ok && notifyEndStates != nil {
			r.NotifyEndStates, _ = types.ListValueFrom(context.Background(), types.StringType, *notifyEndStates)
		} else {
			r.NotifyEndStates = types.ListNull(types.StringType)
		}
		if notifyEndTypes, ok := item.Attributes.GetNotifyEndTypesOk(); ok && notifyEndTypes != nil {
			r.NotifyEndTypes, _ = types.ListValueFrom(context.Background(), types.StringType, *notifyEndTypes)
		} else {
			r.NotifyEndTypes = types.ListNull(types.StringType)
		}
		results = append(results, &r)
	}

	hashingData := fmt.Sprintf("%t:%s:%d", state.CurrentOnly.ValueBool(), state.Include.ValueString(), state.PageOffset.ValueInt64())
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.Downtimes = results
}
