// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ datasource.DataSourceWithConfigure = &datadogAzureUcConfigsDataSource{}
)

type datadogAzureUcConfigsDataSourceModel struct {
	// Results
	ID             types.String              `tfsdk:"id"`
	AzureUcConfigs []*AzureUcConfigPairModel `tfsdk:"azure_uc_configs"`
}

type AzureUcConfigPairModel struct {
	ID      types.String    `tfsdk:"id"`
	Configs []*ConfigsModel `tfsdk:"configs"`
}

type ConfigsModel struct {
	AccountId        types.String `tfsdk:"account_id"`
	ClientId         types.String `tfsdk:"client_id"`
	CreatedAt        types.String `tfsdk:"created_at"`
	DatasetType      types.String `tfsdk:"dataset_type"`
	ErrorMessages    types.List   `tfsdk:"error_messages"`
	ExportName       types.String `tfsdk:"export_name"`
	ExportPath       types.String `tfsdk:"export_path"`
	Id               types.String `tfsdk:"id"`
	Months           types.Int64  `tfsdk:"months"`
	Scope            types.String `tfsdk:"scope"`
	Status           types.String `tfsdk:"status"`
	StatusUpdatedAt  types.String `tfsdk:"status_updated_at"`
	StorageAccount   types.String `tfsdk:"storage_account"`
	StorageContainer types.String `tfsdk:"storage_container"`
	UpdatedAt        types.String `tfsdk:"updated_at"`
}

type datadogAzureUcConfigsDataSource struct {
	Api  *datadogV2.CloudCostManagementApi
	Auth context.Context
}

func NewDatadogAzureUcConfigsDataSource() datasource.DataSource {
	return &datadogAzureUcConfigsDataSource{}
}

func (d *datadogAzureUcConfigsDataSource) Configure(_ context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	d.Api = providerData.DatadogApiInstances.GetCloudCostManagementApiV2()
	d.Auth = providerData.Auth
}

func (d *datadogAzureUcConfigsDataSource) Metadata(_ context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = "azure_uc_configs"
}

func (d *datadogAzureUcConfigsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Use this data source to retrieve information about existing Datadog Azure Usage Cost configurations.",
		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
		},
		Blocks: map[string]schema.Block{
			"azure_uc_configs": schema.ListNestedBlock{
				Description: "An Azure config pair.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description: "The ID of Cloud Cost Management account.",
							Computed:    true,
						},
					},
					Blocks: map[string]schema.Block{
						"configs": schema.ListNestedBlock{
							Description: "An Azure config.",
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"account_id": schema.StringAttribute{
										Description: "The tenant ID of the Azure account.",
										Computed:    true,
									},
									"client_id": schema.StringAttribute{
										Description: "The client ID of the Azure account.",
										Computed:    true,
									},
									"created_at": schema.StringAttribute{
										Description: "The timestamp when the Azure config was created.",
										Computed:    true,
									},
									"dataset_type": schema.StringAttribute{
										Description: "The dataset type of the Azure config.",
										Computed:    true,
									},
									"error_messages": schema.ListAttribute{
										Description: "The error messages for the Azure config.",
										ElementType: types.StringType,
										Computed:    true,
									},
									"export_name": schema.StringAttribute{
										Description: "The name of the configured Azure Export.",
										Computed:    true,
									},
									"export_path": schema.StringAttribute{
										Description: "The path where the Azure Export is saved.",
										Computed:    true,
									},
									"id": schema.StringAttribute{
										Description: "The ID of the Azure config.",
										Computed:    true,
									},
									"months": schema.Int64Attribute{
										Description: "The number of months the report has been backfilled.",
										Computed:    true,
									},
									"scope": schema.StringAttribute{
										Description: "The scope of your observed subscription.",
										Computed:    true,
									},
									"status": schema.StringAttribute{
										Description: "The status of the Azure config.",
										Computed:    true,
									},
									"status_updated_at": schema.StringAttribute{
										Description: "The timestamp when the Azure config status was last updated.",
										Computed:    true,
									},
									"storage_account": schema.StringAttribute{
										Description: "The name of the storage account where the Azure Export is saved.",
										Computed:    true,
									},
									"storage_container": schema.StringAttribute{
										Description: "The name of the storage container where the Azure Export is saved.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "The timestamp when the Azure config was last updated.",
										Computed:    true,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (d *datadogAzureUcConfigsDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var state datadogAzureUcConfigsDataSourceModel
	response.Diagnostics.Append(request.Config.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	var items []datadogV2.AzureUCConfigPair
	resp, _, err := d.Api.ListCostAzureUCConfigs(d.Auth)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "Error when calling `ListCostAzureUCConfigs`"))
		return
	}
	items = append(items, resp.Data...)

	d.updateState(&state, &items)
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (d *datadogAzureUcConfigsDataSource) updateState(state *datadogAzureUcConfigsDataSourceModel, data *[]datadogV2.AzureUCConfigPair) {
	results := make([]*AzureUcConfigPairModel, 0, len(*data))
	for _, item := range *data {
		r := AzureUcConfigPairModel{
			ID: types.StringValue(item.GetId()),
		}
		if configs, ok := item.Attributes.GetConfigsOk(); ok && configs != nil {
			for _, configsItem := range *configs {
				configsModel := &ConfigsModel{}
				if accountId, ok := configsItem.GetAccountIdOk(); ok && accountId != nil {
					configsModel.AccountId = types.StringValue(*accountId)
				}
				if clientId, ok := configsItem.GetClientIdOk(); ok && clientId != nil {
					configsModel.ClientId = types.StringValue(*clientId)
				}
				if createdAt, ok := configsItem.GetCreatedAtOk(); ok && createdAt != nil {
					configsModel.CreatedAt = types.StringValue(*createdAt)
				}
				if datasetType, ok := configsItem.GetDatasetTypeOk(); ok && datasetType != nil {
					configsModel.DatasetType = types.StringValue(*datasetType)
				}
				if exportName, ok := configsItem.GetExportNameOk(); ok && exportName != nil {
					configsModel.ExportName = types.StringValue(*exportName)
				}
				if exportPath, ok := configsItem.GetExportPathOk(); ok && exportPath != nil {
					configsModel.ExportPath = types.StringValue(*exportPath)
				}
				if id, ok := configsItem.GetIdOk(); ok && id != nil {
					configsModel.Id = types.StringValue(*id)
				}
				if months, ok := configsItem.GetMonthsOk(); ok && months != nil {
					configsModel.Months = types.Int64Value(int64(*months))
				}
				if scope, ok := configsItem.GetScopeOk(); ok && scope != nil {
					configsModel.Scope = types.StringValue(*scope)
				}
				if status, ok := configsItem.GetStatusOk(); ok && status != nil {
					configsModel.Status = types.StringValue(*status)
				}
				if statusUpdatedAt, ok := configsItem.GetStatusUpdatedAtOk(); ok && statusUpdatedAt != nil {
					configsModel.StatusUpdatedAt = types.StringValue(*statusUpdatedAt)
				}
				if storageAccount, ok := configsItem.GetStorageAccountOk(); ok && storageAccount != nil {
					configsModel.StorageAccount = types.StringValue(*storageAccount)
				}
				if storageContainer, ok := configsItem.GetStorageContainerOk(); ok && storageContainer != nil {
					configsModel.StorageContainer = types.StringValue(*storageContainer)
				}
				if updatedAt, ok := configsItem.GetUpdatedAtOk(); ok && updatedAt != nil {
					configsModel.UpdatedAt = types.StringValue(*updatedAt)
				}
				if errorMessages, ok := configsItem.GetErrorMessagesOk(); ok && errorMessages != nil {
					configsModel.ErrorMessages, _ = types.ListValueFrom(context.Background(), types.StringType, *errorMessages)
				} else {
					configsModel.ErrorMessages = types.ListNull(types.StringType)
				}
				r.Configs = append(r.Configs, configsModel)
			}
		}
		results = append(results, &r)
	}

	hashingData := "azure_uc_configs"
	state.ID = types.StringValue(utils.ConvertToSha256(hashingData))
	state.AzureUcConfigs = results
}
