// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/fwutils"
	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ resource.ResourceWithConfigure   = &datadogIntegrationTwilioAccountResource{}
	_ resource.ResourceWithImportState = &datadogIntegrationTwilioAccountResource{}
)
var datadogIntegrationTwilioAccountAuthenticationTwilioIntegrationAccountBasicAuthPasswordWriteOnlySecretConfig = fwutils.WriteOnlySecretConfig{OriginalAttr: "password", WriteOnlyAttr: "password_wo", TriggerAttr: "password_wo_version", WriteOnlyDescription: "Secret password or private key. This write-only value is not stored in Terraform state.", TriggerDescription: "Version trigger for password_wo rotation.", ParentBlocks: []string{"authentication", "twilio_integration_account_basic_auth"}, Mode: fwutils.WriteOnlySecretModeOnly, Required: true}

type datadogIntegrationTwilioAccountResourceModel struct {
	ID             types.String                                                                  `tfsdk:"id"`
	Authentication *datadogIntegrationTwilioAccountTwilioIntegrationAccountAuthenticationModel   `tfsdk:"authentication"`
	Dataflows      *datadogIntegrationTwilioAccountTwilioIntegrationDataflowsResponseModel       `tfsdk:"dataflows"`
	Name           types.String                                                                  `tfsdk:"name"`
	Settings       *datadogIntegrationTwilioAccountTwilioIntegrationAccountSettingsResponseModel `tfsdk:"settings"`
}

type datadogIntegrationTwilioAccountTwilioIntegrationAccountAuthenticationModel struct {
	TwilioIntegrationAccountBasicAuth *datadogIntegrationTwilioAccountTwilioIntegrationAccountAuthenticationTwilioIntegrationAccountBasicAuthModel `tfsdk:"twilio_integration_account_basic_auth"`
}

type datadogIntegrationTwilioAccountTwilioIntegrationAccountAuthenticationTwilioIntegrationAccountBasicAuthModel struct {
	AuthType          types.String `tfsdk:"auth_type"`
	PasswordWo        types.String `tfsdk:"password_wo"`
	PasswordWoVersion types.String `tfsdk:"password_wo_version"`
	Username          types.String `tfsdk:"username"`
}

type datadogIntegrationTwilioAccountTwilioIntegrationDataflowsResponseModel struct {
	TwilioAlertsLogs        *datadogIntegrationTwilioAccountTwilioAlertsLogsIntegrationDataflowResponseModel        `tfsdk:"twilio_alerts_logs"`
	TwilioCallSummariesLogs *datadogIntegrationTwilioAccountTwilioCallSummariesLogsIntegrationDataflowResponseModel `tfsdk:"twilio_call_summaries_logs"`
	TwilioCloudCostMetrics  *datadogIntegrationTwilioAccountTwilioCloudCostMetricsIntegrationDataflowResponseModel  `tfsdk:"twilio_cloud_cost_metrics"`
	TwilioEventsLogs        *datadogIntegrationTwilioAccountTwilioEventsLogsIntegrationDataflowResponseModel        `tfsdk:"twilio_events_logs"`
	TwilioMessagesLogs      *datadogIntegrationTwilioAccountTwilioMessagesLogsIntegrationDataflowResponseModel      `tfsdk:"twilio_messages_logs"`
}

type datadogIntegrationTwilioAccountTwilioAlertsLogsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                            `tfsdk:"enabled"`
	Status  *datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel struct {
	Health    types.String `tfsdk:"health"`
	Message   types.String `tfsdk:"message"`
	UpdatedAt types.String `tfsdk:"updated_at"`
}

type datadogIntegrationTwilioAccountTwilioCallSummariesLogsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                            `tfsdk:"enabled"`
	Status  *datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationTwilioAccountTwilioCloudCostMetricsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                            `tfsdk:"enabled"`
	Status  *datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationTwilioAccountTwilioEventsLogsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                            `tfsdk:"enabled"`
	Status  *datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationTwilioAccountTwilioMessagesLogsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                            `tfsdk:"enabled"`
	Status  *datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationTwilioAccountTwilioIntegrationAccountSettingsResponseModel struct {
	AccountSid types.String `tfsdk:"account_sid"`
	CensorLogs types.Bool   `tfsdk:"censor_logs"`
}

type datadogIntegrationTwilioAccountResource struct {
	Api  *datadogV2.TwilioIntegrationApi
	Auth context.Context
}

func NewDatadogIntegrationTwilioAccountResource() resource.Resource {
	return &datadogIntegrationTwilioAccountResource{}
}

func (r *datadogIntegrationTwilioAccountResource) Configure(_ context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	r.Api = datadogV2.NewTwilioIntegrationApi(providerData.DatadogApiInstances.HttpClient)
	r.Auth = providerData.Auth
}

func (r *datadogIntegrationTwilioAccountResource) Metadata(_ context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = "integration_twilio_account"
}

func (r *datadogIntegrationTwilioAccountResource) Schema(_ context.Context, _ resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Provides a Datadog Twilio integration account resource.",

		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"name": schema.StringAttribute{
				Description: "Human-readable name of the Twilio integration account.",
				Required:    true,
			},

			"authentication": schema.SingleNestedAttribute{
				Description: "Authentication configured on the Twilio integration account.",

				Attributes: map[string]schema.Attribute{
					"twilio_integration_account_basic_auth": schema.SingleNestedAttribute{
						Description: "The basic authentication method and username configured on the account.",

						Attributes: fwutils.MergeAttributes(
							map[string]schema.Attribute{
								"auth_type": schema.StringAttribute{
									Description: "The authentication method type.",
									Default:     stringdefault.StaticString("basic"),
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOf("basic"),
									},

									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"username": schema.StringAttribute{
									Description: "Non-secret username or public identifier for the credential pair.",
									Required:    true,
								},
							},
							fwutils.CreateWriteOnlySecretAttributes(datadogIntegrationTwilioAccountAuthenticationTwilioIntegrationAccountBasicAuthPasswordWriteOnlySecretConfig),
						),
						Optional: true,

						Validators: []validator.Object{
							objectvalidator.ExactlyOneOf(),
						},
					},
				},
				Required: true,
			},

			"dataflows": schema.SingleNestedAttribute{
				Description: "Data Datadog collects from Twilio, keyed by dataflow id.",

				Attributes: map[string]schema.Attribute{
					"twilio_alerts_logs": schema.SingleNestedAttribute{
						Description: "Twilio Alert resource logs, which detail the errors and warnings raised when Twilio makes a webhook request to your server or when your application calls the Twilio REST API.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"twilio_call_summaries_logs": schema.SingleNestedAttribute{
						Description: "Twilio Call Summary resource logs, covering the metadata and performance of the calls made from your Twilio account. Requires Voice Insights Advanced Features to be enabled on the Twilio account; without it this dataflow collects no data.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"twilio_cloud_cost_metrics": schema.SingleNestedAttribute{
						Description: "Your Twilio cost data, so that Twilio spend can be broken down and attributed in [Cloud Cost Management](https://docs.datadoghq.com/cloud_cost_management/).",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"twilio_events_logs": schema.SingleNestedAttribute{
						Description: "Twilio Event resource logs, which record virtually every action taken in your Twilio account, such as provisioning a phone number, changing account security settings, or deleting a recording. Actions are recorded whether they came from the REST API, a user in the Twilio Console, or Twilio itself. [Cloud SIEM](https://docs.datadoghq.com/security/cloud_siem/) analyzes and correlates these logs to detect threats in real time.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"twilio_messages_logs": schema.SingleNestedAttribute{
						Description: "Twilio Message resource logs for inbound and outbound messages, used to track delivery and troubleshoot message errors. A log is produced when you send a message through the REST API, when Twilio executes a TwiML instruction, and when someone messages one of your Twilio numbers or channel addresses. Message bodies are never collected.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},
				},
				Optional: true,
				Computed: true,

				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
			},

			"settings": schema.SingleNestedAttribute{
				Description: "Settings configured on the Twilio integration account.",

				Attributes: map[string]schema.Attribute{
					"account_sid": schema.StringAttribute{
						Description: "Twilio Account SID that uniquely identifies your Twilio account.",
						Required:    true,
					},
					"censor_logs": schema.BoolAttribute{
						Description: "When enabled, Twilio phone numbers in the `to` field and SMS message bodies are censored for privacy.",
						Optional:    true,
						Computed:    true,

						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
				},
				Required: true,
			},
		},
	}
}

func (r *datadogIntegrationTwilioAccountResource) ImportState(ctx context.Context, request resource.ImportStateRequest, response *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), request, response)
}

func (r *datadogIntegrationTwilioAccountResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var state datadogIntegrationTwilioAccountResourceModel
	var plan types.Object
	response.Diagnostics.Append(request.Plan.Get(ctx, &plan)...)
	if response.Diagnostics.HasError() {
		return
	}
	response.Diagnostics.Append(plan.As(ctx, &state, basetypes.ObjectAsOptions{UnhandledUnknownAsEmpty: true})...)
	if response.Diagnostics.HasError() {
		return
	}

	authenticationTwilioIntegrationAccountBasicAuthPasswordWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationTwilioAccountAuthenticationTwilioIntegrationAccountBasicAuthPasswordWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	authenticationTwilioIntegrationAccountBasicAuthPasswordSecretResult := authenticationTwilioIntegrationAccountBasicAuthPasswordWriteOnlySecretHandler.GetSecretForCreate(ctx, &request.Config)
	response.Diagnostics.Append(authenticationTwilioIntegrationAccountBasicAuthPasswordSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}

	bodyAttributes := datadogV2.NewTwilioIntegrationAccountCreateAttributesWithDefaults()

	if state.Authentication != nil {
		var authenticationUnion datadogV2.TwilioIntegrationAccountAuthenticationRequest
		authenticationMatches := 0
		if state.Authentication.TwilioIntegrationAccountBasicAuth != nil {
			twilioIntegrationAccountBasicAuthVariant := datadogV2.NewTwilioIntegrationAccountBasicAuthRequestWithDefaults()

			if !state.Authentication.TwilioIntegrationAccountBasicAuth.AuthType.IsNull() && !state.Authentication.TwilioIntegrationAccountBasicAuth.AuthType.IsUnknown() {
				twilioIntegrationAccountBasicAuthVariant.SetAuthType(datadogV2.TwilioIntegrationAccountBasicAuthType(state.Authentication.TwilioIntegrationAccountBasicAuth.AuthType.ValueString()))
			}

			if authenticationTwilioIntegrationAccountBasicAuthPasswordSecretResult.ShouldSetValue {
				twilioIntegrationAccountBasicAuthVariant.SetPassword(authenticationTwilioIntegrationAccountBasicAuthPasswordSecretResult.Value)
			}

			twilioIntegrationAccountBasicAuthVariant.SetUsername(state.Authentication.TwilioIntegrationAccountBasicAuth.Username.ValueString())
			authenticationUnion = datadogV2.TwilioIntegrationAccountBasicAuthRequestAsTwilioIntegrationAccountAuthenticationRequest(twilioIntegrationAccountBasicAuthVariant)
			authenticationMatches++
		}
		if authenticationMatches != 1 {
			response.Diagnostics.AddError(
				"Invalid authentication",
				fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"twilio_integration_account_basic_auth\" must be set, got %d", authenticationMatches),
			)
			return
		}
		bodyAttributes.SetAuthentication(authenticationUnion)
	} else {
		response.Diagnostics.AddError(
			"Invalid authentication",
			fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"twilio_integration_account_basic_auth\" must be set, got %d", 0),
		)
		return
	}

	if state.Dataflows != nil {
		dataflowsValue := datadogV2.NewTwilioIntegrationDataflowsRequestWithDefaults()

		if state.Dataflows.TwilioAlertsLogs != nil {
			twilioAlertsLogsValue := datadogV2.NewTwilioAlertsLogsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioAlertsLogs.Enabled.IsNull() && !state.Dataflows.TwilioAlertsLogs.Enabled.IsUnknown() {
				twilioAlertsLogsValue.SetEnabled(state.Dataflows.TwilioAlertsLogs.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioAlertsLogs(*twilioAlertsLogsValue)
		}

		if state.Dataflows.TwilioCallSummariesLogs != nil {
			twilioCallSummariesLogsValue := datadogV2.NewTwilioCallSummariesLogsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioCallSummariesLogs.Enabled.IsNull() && !state.Dataflows.TwilioCallSummariesLogs.Enabled.IsUnknown() {
				twilioCallSummariesLogsValue.SetEnabled(state.Dataflows.TwilioCallSummariesLogs.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioCallSummariesLogs(*twilioCallSummariesLogsValue)
		}

		if state.Dataflows.TwilioCloudCostMetrics != nil {
			twilioCloudCostMetricsValue := datadogV2.NewTwilioCloudCostMetricsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioCloudCostMetrics.Enabled.IsNull() && !state.Dataflows.TwilioCloudCostMetrics.Enabled.IsUnknown() {
				twilioCloudCostMetricsValue.SetEnabled(state.Dataflows.TwilioCloudCostMetrics.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioCloudCostMetrics(*twilioCloudCostMetricsValue)
		}

		if state.Dataflows.TwilioEventsLogs != nil {
			twilioEventsLogsValue := datadogV2.NewTwilioEventsLogsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioEventsLogs.Enabled.IsNull() && !state.Dataflows.TwilioEventsLogs.Enabled.IsUnknown() {
				twilioEventsLogsValue.SetEnabled(state.Dataflows.TwilioEventsLogs.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioEventsLogs(*twilioEventsLogsValue)
		}

		if state.Dataflows.TwilioMessagesLogs != nil {
			twilioMessagesLogsValue := datadogV2.NewTwilioMessagesLogsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioMessagesLogs.Enabled.IsNull() && !state.Dataflows.TwilioMessagesLogs.Enabled.IsUnknown() {
				twilioMessagesLogsValue.SetEnabled(state.Dataflows.TwilioMessagesLogs.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioMessagesLogs(*twilioMessagesLogsValue)
		}
		bodyAttributes.SetDataflows(*dataflowsValue)
	}

	bodyAttributes.SetName(state.Name.ValueString())

	settingsValue := datadogV2.NewTwilioIntegrationAccountSettingsRequestWithDefaults()

	settingsValue.SetAccountSid(state.Settings.AccountSid.ValueString())

	if !state.Settings.CensorLogs.IsNull() && !state.Settings.CensorLogs.IsUnknown() {
		settingsValue.SetCensorLogs(state.Settings.CensorLogs.ValueBool())
	}
	bodyAttributes.SetSettings(*settingsValue)
	bodyData := datadogV2.NewTwilioIntegrationAccountCreateDataWithDefaults()
	bodyData.SetType(datadogV2.IntegrationAccountType("integration-account"))
	bodyData.SetAttributes(*bodyAttributes)
	body := datadogV2.NewTwilioIntegrationAccountCreateRequestWithDefaults()
	body.SetData(*bodyData)
	resp, _, err := r.Api.CreateTwilioIntegrationAccount(r.Auth, *body)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error creating integration_twilio_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	if state.Authentication != nil {
		if state.Authentication.TwilioIntegrationAccountBasicAuth != nil {
			if state.Authentication.TwilioIntegrationAccountBasicAuth.AuthType.IsUnknown() {
				state.Authentication.TwilioIntegrationAccountBasicAuth.AuthType = types.StringNull()
			}
		}
	}
	if state.Dataflows != nil {
		if state.Dataflows.TwilioAlertsLogs != nil {
			if state.Dataflows.TwilioAlertsLogs.Enabled.IsUnknown() {
				state.Dataflows.TwilioAlertsLogs.Enabled = types.BoolNull()
			}
			if state.Dataflows.TwilioAlertsLogs.Status != nil {
				if state.Dataflows.TwilioAlertsLogs.Status.Health.IsUnknown() {
					state.Dataflows.TwilioAlertsLogs.Status.Health = types.StringNull()
				}
				if state.Dataflows.TwilioAlertsLogs.Status.Message.IsUnknown() {
					state.Dataflows.TwilioAlertsLogs.Status.Message = types.StringNull()
				}
				if state.Dataflows.TwilioAlertsLogs.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.TwilioAlertsLogs.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.TwilioCallSummariesLogs != nil {
			if state.Dataflows.TwilioCallSummariesLogs.Enabled.IsUnknown() {
				state.Dataflows.TwilioCallSummariesLogs.Enabled = types.BoolNull()
			}
			if state.Dataflows.TwilioCallSummariesLogs.Status != nil {
				if state.Dataflows.TwilioCallSummariesLogs.Status.Health.IsUnknown() {
					state.Dataflows.TwilioCallSummariesLogs.Status.Health = types.StringNull()
				}
				if state.Dataflows.TwilioCallSummariesLogs.Status.Message.IsUnknown() {
					state.Dataflows.TwilioCallSummariesLogs.Status.Message = types.StringNull()
				}
				if state.Dataflows.TwilioCallSummariesLogs.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.TwilioCallSummariesLogs.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.TwilioCloudCostMetrics != nil {
			if state.Dataflows.TwilioCloudCostMetrics.Enabled.IsUnknown() {
				state.Dataflows.TwilioCloudCostMetrics.Enabled = types.BoolNull()
			}
			if state.Dataflows.TwilioCloudCostMetrics.Status != nil {
				if state.Dataflows.TwilioCloudCostMetrics.Status.Health.IsUnknown() {
					state.Dataflows.TwilioCloudCostMetrics.Status.Health = types.StringNull()
				}
				if state.Dataflows.TwilioCloudCostMetrics.Status.Message.IsUnknown() {
					state.Dataflows.TwilioCloudCostMetrics.Status.Message = types.StringNull()
				}
				if state.Dataflows.TwilioCloudCostMetrics.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.TwilioCloudCostMetrics.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.TwilioEventsLogs != nil {
			if state.Dataflows.TwilioEventsLogs.Enabled.IsUnknown() {
				state.Dataflows.TwilioEventsLogs.Enabled = types.BoolNull()
			}
			if state.Dataflows.TwilioEventsLogs.Status != nil {
				if state.Dataflows.TwilioEventsLogs.Status.Health.IsUnknown() {
					state.Dataflows.TwilioEventsLogs.Status.Health = types.StringNull()
				}
				if state.Dataflows.TwilioEventsLogs.Status.Message.IsUnknown() {
					state.Dataflows.TwilioEventsLogs.Status.Message = types.StringNull()
				}
				if state.Dataflows.TwilioEventsLogs.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.TwilioEventsLogs.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.TwilioMessagesLogs != nil {
			if state.Dataflows.TwilioMessagesLogs.Enabled.IsUnknown() {
				state.Dataflows.TwilioMessagesLogs.Enabled = types.BoolNull()
			}
			if state.Dataflows.TwilioMessagesLogs.Status != nil {
				if state.Dataflows.TwilioMessagesLogs.Status.Health.IsUnknown() {
					state.Dataflows.TwilioMessagesLogs.Status.Health = types.StringNull()
				}
				if state.Dataflows.TwilioMessagesLogs.Status.Message.IsUnknown() {
					state.Dataflows.TwilioMessagesLogs.Status.Message = types.StringNull()
				}
				if state.Dataflows.TwilioMessagesLogs.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.TwilioMessagesLogs.Status.UpdatedAt = types.StringNull()
				}
			}
		}
	}
	if state.Settings != nil {
		if state.Settings.CensorLogs.IsUnknown() {
			state.Settings.CensorLogs = types.BoolNull()
		}
	}
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationTwilioAccountResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var state datadogIntegrationTwilioAccountResourceModel
	response.Diagnostics.Append(request.State.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	resp, httpResp, err := r.Api.GetTwilioIntegrationAccount(r.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			response.State.RemoveResource(ctx)
			return
		}
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error reading integration_twilio_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationTwilioAccountResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var state datadogIntegrationTwilioAccountResourceModel
	var plan types.Object
	response.Diagnostics.Append(request.Plan.Get(ctx, &plan)...)
	if response.Diagnostics.HasError() {
		return
	}
	response.Diagnostics.Append(plan.As(ctx, &state, basetypes.ObjectAsOptions{UnhandledUnknownAsEmpty: true})...)
	if response.Diagnostics.HasError() {
		return
	}

	authenticationTwilioIntegrationAccountBasicAuthPasswordWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationTwilioAccountAuthenticationTwilioIntegrationAccountBasicAuthPasswordWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	authenticationTwilioIntegrationAccountBasicAuthPasswordSecretResult := authenticationTwilioIntegrationAccountBasicAuthPasswordWriteOnlySecretHandler.GetSecretForUpdate(ctx, &request.Config, &request)
	response.Diagnostics.Append(authenticationTwilioIntegrationAccountBasicAuthPasswordSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}

	bodyAttributes := datadogV2.NewTwilioIntegrationAccountUpdateAttributesWithDefaults()

	if state.Authentication != nil {
		var authenticationUnion datadogV2.TwilioIntegrationAccountAuthenticationUpdate
		authenticationMatches := 0
		if state.Authentication.TwilioIntegrationAccountBasicAuth != nil {
			twilioIntegrationAccountBasicAuthVariant := datadogV2.NewTwilioIntegrationAccountBasicAuthUpdateWithDefaults()

			if !state.Authentication.TwilioIntegrationAccountBasicAuth.AuthType.IsNull() && !state.Authentication.TwilioIntegrationAccountBasicAuth.AuthType.IsUnknown() {
				twilioIntegrationAccountBasicAuthVariant.SetAuthType(datadogV2.TwilioIntegrationAccountBasicAuthType(state.Authentication.TwilioIntegrationAccountBasicAuth.AuthType.ValueString()))
			}

			if authenticationTwilioIntegrationAccountBasicAuthPasswordSecretResult.ShouldSetValue {
				twilioIntegrationAccountBasicAuthVariant.SetPassword(authenticationTwilioIntegrationAccountBasicAuthPasswordSecretResult.Value)
			}

			twilioIntegrationAccountBasicAuthVariant.SetUsername(state.Authentication.TwilioIntegrationAccountBasicAuth.Username.ValueString())
			authenticationUnion = datadogV2.TwilioIntegrationAccountBasicAuthUpdateAsTwilioIntegrationAccountAuthenticationUpdate(twilioIntegrationAccountBasicAuthVariant)
			authenticationMatches++
		}
		if authenticationMatches != 1 {
			response.Diagnostics.AddError(
				"Invalid authentication",
				fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"twilio_integration_account_basic_auth\" must be set, got %d", authenticationMatches),
			)
			return
		}
		bodyAttributes.SetAuthentication(authenticationUnion)
	} else {
		response.Diagnostics.AddError(
			"Invalid authentication",
			fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"twilio_integration_account_basic_auth\" must be set, got %d", 0),
		)
		return
	}

	if state.Dataflows != nil {
		dataflowsValue := datadogV2.NewTwilioIntegrationDataflowsRequestWithDefaults()

		if state.Dataflows.TwilioAlertsLogs != nil {
			twilioAlertsLogsValue := datadogV2.NewTwilioAlertsLogsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioAlertsLogs.Enabled.IsNull() && !state.Dataflows.TwilioAlertsLogs.Enabled.IsUnknown() {
				twilioAlertsLogsValue.SetEnabled(state.Dataflows.TwilioAlertsLogs.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioAlertsLogs(*twilioAlertsLogsValue)
		}

		if state.Dataflows.TwilioCallSummariesLogs != nil {
			twilioCallSummariesLogsValue := datadogV2.NewTwilioCallSummariesLogsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioCallSummariesLogs.Enabled.IsNull() && !state.Dataflows.TwilioCallSummariesLogs.Enabled.IsUnknown() {
				twilioCallSummariesLogsValue.SetEnabled(state.Dataflows.TwilioCallSummariesLogs.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioCallSummariesLogs(*twilioCallSummariesLogsValue)
		}

		if state.Dataflows.TwilioCloudCostMetrics != nil {
			twilioCloudCostMetricsValue := datadogV2.NewTwilioCloudCostMetricsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioCloudCostMetrics.Enabled.IsNull() && !state.Dataflows.TwilioCloudCostMetrics.Enabled.IsUnknown() {
				twilioCloudCostMetricsValue.SetEnabled(state.Dataflows.TwilioCloudCostMetrics.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioCloudCostMetrics(*twilioCloudCostMetricsValue)
		}

		if state.Dataflows.TwilioEventsLogs != nil {
			twilioEventsLogsValue := datadogV2.NewTwilioEventsLogsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioEventsLogs.Enabled.IsNull() && !state.Dataflows.TwilioEventsLogs.Enabled.IsUnknown() {
				twilioEventsLogsValue.SetEnabled(state.Dataflows.TwilioEventsLogs.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioEventsLogs(*twilioEventsLogsValue)
		}

		if state.Dataflows.TwilioMessagesLogs != nil {
			twilioMessagesLogsValue := datadogV2.NewTwilioMessagesLogsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.TwilioMessagesLogs.Enabled.IsNull() && !state.Dataflows.TwilioMessagesLogs.Enabled.IsUnknown() {
				twilioMessagesLogsValue.SetEnabled(state.Dataflows.TwilioMessagesLogs.Enabled.ValueBool())
			}
			dataflowsValue.SetTwilioMessagesLogs(*twilioMessagesLogsValue)
		}
		bodyAttributes.SetDataflows(*dataflowsValue)
	}

	bodyAttributes.SetName(state.Name.ValueString())

	settingsValue := datadogV2.NewTwilioIntegrationAccountSettingsUpdateWithDefaults()

	settingsValue.SetAccountSid(state.Settings.AccountSid.ValueString())

	if !state.Settings.CensorLogs.IsNull() && !state.Settings.CensorLogs.IsUnknown() {
		settingsValue.SetCensorLogs(state.Settings.CensorLogs.ValueBool())
	}
	bodyAttributes.SetSettings(*settingsValue)
	bodyData := datadogV2.NewTwilioIntegrationAccountUpdateDataWithDefaults()
	bodyData.SetType(datadogV2.IntegrationAccountType("integration-account"))
	bodyData.SetId(state.ID.ValueString())
	bodyData.SetAttributes(*bodyAttributes)
	body := datadogV2.NewTwilioIntegrationAccountUpdateRequestWithDefaults()
	body.SetData(*bodyData)
	resp, _, err := r.Api.UpdateTwilioIntegrationAccount(r.Auth, state.ID.ValueString(), *body)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error updating integration_twilio_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationTwilioAccountResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var state datadogIntegrationTwilioAccountResourceModel
	response.Diagnostics.Append(request.State.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.Api.DeleteTwilioIntegrationAccount(r.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			return
		}
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error deleting integration_twilio_account"))
	}
}

// updateState maps *datadogV2.TwilioIntegrationAccountResponse into state, returning diagnostics
// rather than writing them so it stays free of the resource request/response
// types and can fail at a specific schema path. Shared by Create, Read and
// Update, which all resolve the same response type.
func (r *datadogIntegrationTwilioAccountResource) updateState(ctx context.Context, state *datadogIntegrationTwilioAccountResourceModel, resp *datadogV2.TwilioIntegrationAccountResponse) diag.Diagnostics {
	var diags diag.Diagnostics
	attributes := resp.Data.GetAttributes()
	if id, ok := resp.Data.GetIdOk(); ok && id != nil {
		state.ID = types.StringValue(*id)
	}
	if name, ok := attributes.GetNameOk(); ok && name != nil {
		state.Name = types.StringValue(*name)
	}
	if authentication, ok := attributes.GetAuthenticationOk(); ok && authentication != nil {
		authenticationEnvelope := &datadogIntegrationTwilioAccountTwilioIntegrationAccountAuthenticationModel{}
		authenticationMatches := 0
		if twilioIntegrationAccountBasicAuthVariant := authentication.TwilioIntegrationAccountBasicAuthResponse; twilioIntegrationAccountBasicAuthVariant != nil {
			twilioIntegrationAccountBasicAuthModel := &datadogIntegrationTwilioAccountTwilioIntegrationAccountAuthenticationTwilioIntegrationAccountBasicAuthModel{}
			if state.Authentication != nil && state.Authentication.TwilioIntegrationAccountBasicAuth != nil {
				twilioIntegrationAccountBasicAuthModel = state.Authentication.TwilioIntegrationAccountBasicAuth
			}
			if authType, ok := twilioIntegrationAccountBasicAuthVariant.GetAuthTypeOk(); ok && authType != nil {
				twilioIntegrationAccountBasicAuthModel.AuthType = types.StringValue(string(*authType))
			}
			if username, ok := twilioIntegrationAccountBasicAuthVariant.GetUsernameOk(); ok && username != nil {
				twilioIntegrationAccountBasicAuthModel.Username = types.StringValue(*username)
			}
			authenticationEnvelope.TwilioIntegrationAccountBasicAuth = twilioIntegrationAccountBasicAuthModel
			authenticationMatches++
		}
		switch {
		case authentication.UnparsedObject != nil:
			diags.AddError(
				"unexpected TwilioIntegrationAccountAuthenticationResponse in the API response",
				"resource.data.attributes.authentication: the Datadog API returned a value none of the TwilioIntegrationAccountAuthenticationResponse alternatives could parse",
			)
		case authenticationMatches > 1:
			diags.AddError(
				"ambiguous TwilioIntegrationAccountAuthenticationResponse in the API response",
				fmt.Sprintf("resource.data.attributes.authentication: the Datadog API response matched %d TwilioIntegrationAccountAuthenticationResponse alternatives, expected exactly one", authenticationMatches),
			)
		case authenticationMatches == 1:
			state.Authentication = authenticationEnvelope
		}
	}
	if dataflows, ok := attributes.GetDataflowsOk(); ok && dataflows != nil {
		dataflowsModel := state.Dataflows
		if dataflowsModel == nil {
			dataflowsModel = &datadogIntegrationTwilioAccountTwilioIntegrationDataflowsResponseModel{}
		}
		if twilioAlertsLogs, ok := dataflows.GetTwilioAlertsLogsOk(); ok && twilioAlertsLogs != nil {
			twilioAlertsLogsModel := dataflowsModel.TwilioAlertsLogs
			if twilioAlertsLogsModel == nil {
				twilioAlertsLogsModel = &datadogIntegrationTwilioAccountTwilioAlertsLogsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := twilioAlertsLogs.GetEnabledOk(); ok && enabled != nil {
				twilioAlertsLogsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := twilioAlertsLogs.GetStatusOk(); ok && status != nil {
				statusModel := twilioAlertsLogsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				twilioAlertsLogsModel.Status = statusModel
			}
			dataflowsModel.TwilioAlertsLogs = twilioAlertsLogsModel
		}
		if twilioCallSummariesLogs, ok := dataflows.GetTwilioCallSummariesLogsOk(); ok && twilioCallSummariesLogs != nil {
			twilioCallSummariesLogsModel := dataflowsModel.TwilioCallSummariesLogs
			if twilioCallSummariesLogsModel == nil {
				twilioCallSummariesLogsModel = &datadogIntegrationTwilioAccountTwilioCallSummariesLogsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := twilioCallSummariesLogs.GetEnabledOk(); ok && enabled != nil {
				twilioCallSummariesLogsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := twilioCallSummariesLogs.GetStatusOk(); ok && status != nil {
				statusModel := twilioCallSummariesLogsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				twilioCallSummariesLogsModel.Status = statusModel
			}
			dataflowsModel.TwilioCallSummariesLogs = twilioCallSummariesLogsModel
		}
		if twilioCloudCostMetrics, ok := dataflows.GetTwilioCloudCostMetricsOk(); ok && twilioCloudCostMetrics != nil {
			twilioCloudCostMetricsModel := dataflowsModel.TwilioCloudCostMetrics
			if twilioCloudCostMetricsModel == nil {
				twilioCloudCostMetricsModel = &datadogIntegrationTwilioAccountTwilioCloudCostMetricsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := twilioCloudCostMetrics.GetEnabledOk(); ok && enabled != nil {
				twilioCloudCostMetricsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := twilioCloudCostMetrics.GetStatusOk(); ok && status != nil {
				statusModel := twilioCloudCostMetricsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				twilioCloudCostMetricsModel.Status = statusModel
			}
			dataflowsModel.TwilioCloudCostMetrics = twilioCloudCostMetricsModel
		}
		if twilioEventsLogs, ok := dataflows.GetTwilioEventsLogsOk(); ok && twilioEventsLogs != nil {
			twilioEventsLogsModel := dataflowsModel.TwilioEventsLogs
			if twilioEventsLogsModel == nil {
				twilioEventsLogsModel = &datadogIntegrationTwilioAccountTwilioEventsLogsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := twilioEventsLogs.GetEnabledOk(); ok && enabled != nil {
				twilioEventsLogsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := twilioEventsLogs.GetStatusOk(); ok && status != nil {
				statusModel := twilioEventsLogsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				twilioEventsLogsModel.Status = statusModel
			}
			dataflowsModel.TwilioEventsLogs = twilioEventsLogsModel
		}
		if twilioMessagesLogs, ok := dataflows.GetTwilioMessagesLogsOk(); ok && twilioMessagesLogs != nil {
			twilioMessagesLogsModel := dataflowsModel.TwilioMessagesLogs
			if twilioMessagesLogsModel == nil {
				twilioMessagesLogsModel = &datadogIntegrationTwilioAccountTwilioMessagesLogsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := twilioMessagesLogs.GetEnabledOk(); ok && enabled != nil {
				twilioMessagesLogsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := twilioMessagesLogs.GetStatusOk(); ok && status != nil {
				statusModel := twilioMessagesLogsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationTwilioAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				twilioMessagesLogsModel.Status = statusModel
			}
			dataflowsModel.TwilioMessagesLogs = twilioMessagesLogsModel
		}
		state.Dataflows = dataflowsModel
	}
	if settings, ok := attributes.GetSettingsOk(); ok && settings != nil {
		settingsModel := state.Settings
		if settingsModel == nil {
			settingsModel = &datadogIntegrationTwilioAccountTwilioIntegrationAccountSettingsResponseModel{}
		}
		if accountSid, ok := settings.GetAccountSidOk(); ok && accountSid != nil {
			settingsModel.AccountSid = types.StringValue(*accountSid)
		}
		if censorLogs, ok := settings.GetCensorLogsOk(); ok && censorLogs != nil {
			settingsModel.CensorLogs = types.BoolValue(*censorLogs)
		}
		state.Settings = settingsModel
	}
	return diags
}
