// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/fwutils"
	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ resource.ResourceWithConfigure   = &datadogIntegrationElasticCloudAccountResource{}
	_ resource.ResourceWithImportState = &datadogIntegrationElasticCloudAccountResource{}
)
var datadogIntegrationElasticCloudAccountAuthenticationElasticCloudIntegrationAccountBasicAuthPasswordWriteOnlySecretConfig = fwutils.WriteOnlySecretConfig{OriginalAttr: "password", WriteOnlyAttr: "password_wo", TriggerAttr: "password_wo_version", WriteOnlyDescription: "Secret password or private key. This write-only value is not stored in Terraform state.", TriggerDescription: "Version trigger for password_wo rotation.", ParentBlocks: []string{"authentication", "elastic_cloud_integration_account_basic_auth"}, Mode: fwutils.WriteOnlySecretModeOnly, Required: true}

type datadogIntegrationElasticCloudAccountResourceModel struct {
	ID             types.String                                                                              `tfsdk:"id"`
	Authentication *datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountAuthenticationModel   `tfsdk:"authentication"`
	Dataflows      *datadogIntegrationElasticCloudAccountElasticCloudIntegrationDataflowsResponseModel       `tfsdk:"dataflows"`
	Name           types.String                                                                              `tfsdk:"name"`
	Settings       *datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountSettingsResponseModel `tfsdk:"settings"`
}

type datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountAuthenticationModel struct {
	ElasticCloudIntegrationAccountBasicAuth *datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountAuthenticationElasticCloudIntegrationAccountBasicAuthModel `tfsdk:"elastic_cloud_integration_account_basic_auth"`
}

type datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountAuthenticationElasticCloudIntegrationAccountBasicAuthModel struct {
	AuthType          types.String `tfsdk:"auth_type"`
	PasswordWo        types.String `tfsdk:"password_wo"`
	PasswordWoVersion types.String `tfsdk:"password_wo_version"`
	Username          types.String `tfsdk:"username"`
}

type datadogIntegrationElasticCloudAccountElasticCloudIntegrationDataflowsResponseModel struct {
	ElasticCloudDetailedIndexStats          *datadogIntegrationElasticCloudAccountElasticCloudDetailedIndexStatsIntegrationDataflowResponseModel          `tfsdk:"elastic_cloud_detailed_index_stats"`
	ElasticCloudIndexStats                  *datadogIntegrationElasticCloudAccountElasticCloudIndexStatsIntegrationDataflowResponseModel                  `tfsdk:"elastic_cloud_index_stats"`
	ElasticCloudMetrics                     *datadogIntegrationElasticCloudAccountElasticCloudMetricsIntegrationDataflowResponseModel                     `tfsdk:"elastic_cloud_metrics"`
	ElasticCloudPendingTaskStats            *datadogIntegrationElasticCloudAccountElasticCloudPendingTaskStatsIntegrationDataflowResponseModel            `tfsdk:"elastic_cloud_pending_task_stats"`
	ElasticCloudPrimaryShardGracefulTimeout *datadogIntegrationElasticCloudAccountElasticCloudPrimaryShardGracefulTimeoutIntegrationDataflowResponseModel `tfsdk:"elastic_cloud_primary_shard_graceful_timeout"`
	ElasticCloudPrimaryShardStats           *datadogIntegrationElasticCloudAccountElasticCloudPrimaryShardStatsIntegrationDataflowResponseModel           `tfsdk:"elastic_cloud_primary_shard_stats"`
	ElasticCloudShardAllocationStats        *datadogIntegrationElasticCloudAccountElasticCloudShardAllocationStatsIntegrationDataflowResponseModel        `tfsdk:"elastic_cloud_shard_allocation_stats"`
	ElasticCloudSlmStats                    *datadogIntegrationElasticCloudAccountElasticCloudSlmStatsIntegrationDataflowResponseModel                    `tfsdk:"elastic_cloud_slm_stats"`
}

type datadogIntegrationElasticCloudAccountElasticCloudDetailedIndexStatsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                                  `tfsdk:"enabled"`
	Status  *datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel struct {
	Health    types.String `tfsdk:"health"`
	Message   types.String `tfsdk:"message"`
	UpdatedAt types.String `tfsdk:"updated_at"`
}

type datadogIntegrationElasticCloudAccountElasticCloudIndexStatsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                                  `tfsdk:"enabled"`
	Status  *datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationElasticCloudAccountElasticCloudMetricsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                                  `tfsdk:"enabled"`
	Status  *datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationElasticCloudAccountElasticCloudPendingTaskStatsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                                  `tfsdk:"enabled"`
	Status  *datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationElasticCloudAccountElasticCloudPrimaryShardGracefulTimeoutIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                                  `tfsdk:"enabled"`
	Status  *datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationElasticCloudAccountElasticCloudPrimaryShardStatsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                                  `tfsdk:"enabled"`
	Status  *datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationElasticCloudAccountElasticCloudShardAllocationStatsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                                  `tfsdk:"enabled"`
	Status  *datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationElasticCloudAccountElasticCloudSlmStatsIntegrationDataflowResponseModel struct {
	Enabled types.Bool                                                                  `tfsdk:"enabled"`
	Status  *datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel `tfsdk:"status"`
}

type datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountSettingsResponseModel struct {
	Tags types.String `tfsdk:"tags"`
	Url  types.String `tfsdk:"url"`
}

type datadogIntegrationElasticCloudAccountResource struct {
	Api  *datadogV2.ElasticCloudIntegrationApi
	Auth context.Context
}

func NewDatadogIntegrationElasticCloudAccountResource() resource.Resource {
	return &datadogIntegrationElasticCloudAccountResource{}
}

func (r *datadogIntegrationElasticCloudAccountResource) Configure(_ context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	r.Api = datadogV2.NewElasticCloudIntegrationApi(providerData.DatadogApiInstances.HttpClient)
	r.Auth = providerData.Auth
}

func (r *datadogIntegrationElasticCloudAccountResource) Metadata(_ context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = "integration_elastic_cloud_account"
}

func (r *datadogIntegrationElasticCloudAccountResource) Schema(_ context.Context, _ resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Provides a Datadog Elastic Cloud integration account resource.",

		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"name": schema.StringAttribute{
				Description: "Human-readable name of the Elastic Cloud integration account.",
				Required:    true,
			},

			"authentication": schema.SingleNestedAttribute{
				Description: "Authentication configured on the Elastic Cloud integration account.",

				Attributes: map[string]schema.Attribute{
					"elastic_cloud_integration_account_basic_auth": schema.SingleNestedAttribute{
						Description: "The basic authentication method and username configured on the account.",

						Attributes: fwutils.MergeAttributes(
							map[string]schema.Attribute{
								"auth_type": schema.StringAttribute{
									Description: "The authentication method type.",
									Default:     stringdefault.StaticString("basic"),
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOf("basic"),
									},

									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"username": schema.StringAttribute{
									Description: "Non-secret username or public identifier for the credential pair.",
									Required:    true,
								},
							},
							fwutils.CreateWriteOnlySecretAttributes(datadogIntegrationElasticCloudAccountAuthenticationElasticCloudIntegrationAccountBasicAuthPasswordWriteOnlySecretConfig),
						),
						Optional: true,

						Validators: []validator.Object{
							objectvalidator.ExactlyOneOf(),
						},
					},
				},
				Required: true,
			},

			"dataflows": schema.SingleNestedAttribute{
				Description: "Data Datadog collects from Elastic Cloud, keyed by dataflow id.",

				Attributes: map[string]schema.Attribute{
					"elastic_cloud_detailed_index_stats": schema.SingleNestedAttribute{
						Description: "Primary shard metrics broken down per index, rather than aggregated across the cluster.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"elastic_cloud_index_stats": schema.SingleNestedAttribute{
						Description: "Metrics for individual indices. Only the indices granted to the role of the user in `authentication` are collected.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"elastic_cloud_metrics": schema.SingleNestedAttribute{
						Description: "Node-level statistics for the clusters in your deployment, such as the number of nodes and the number of documents on each node. This is the integration's baseline collection: it is always on and cannot be turned off, which is why it appears in responses only.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data. Always `true`, because this collection cannot be turned off.",
								Computed:    true,
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Computed: true,
					},

					"elastic_cloud_pending_task_stats": schema.SingleNestedAttribute{
						Description: "Metrics for cluster-level changes that have been submitted but not yet executed.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"elastic_cloud_primary_shard_graceful_timeout": schema.SingleNestedAttribute{
						Description: "Tolerance for slow primary shard requests, keeping the rest of the collection running when a primary shard request times out instead of failing the run. Only has an effect alongside `elastic-cloud-primary-shard-stats`.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether this tolerance is applied.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"elastic_cloud_primary_shard_stats": schema.SingleNestedAttribute{
						Description: "Metrics covering only the cluster's primary shards.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"elastic_cloud_shard_allocation_stats": schema.SingleNestedAttribute{
						Description: "Metrics for how many shards are allocated to each data node, and the disk space they use.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"elastic_cloud_slm_stats": schema.SingleNestedAttribute{
						Description: "Metrics about the actions taken by snapshot lifecycle management. Requires the `read_slm` Elasticsearch cluster privilege on the role of the user in `authentication`; without it this dataflow collects no data.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"status": schema.SingleNestedAttribute{
								Description: "Read-only collection status of a dataflow.",

								Attributes: map[string]schema.Attribute{
									"health": schema.StringAttribute{
										Description: "Collection health of a single dataflow.",
										Computed:    true,
									},
									"message": schema.StringAttribute{
										Description: "Human-readable detail, populated when the dataflow is not healthy.",
										Computed:    true,
									},
									"updated_at": schema.StringAttribute{
										Description: "Time the status was last computed.",
										Computed:    true,
									},
								},
								Computed: true,
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},
				},
				Optional: true,
				Computed: true,

				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
			},

			"settings": schema.SingleNestedAttribute{
				Description: "Settings configured on the Elastic Cloud integration account.",

				Attributes: map[string]schema.Attribute{
					"tags": schema.StringAttribute{
						Description: "Comma-separated list of custom tags for this Elastic Cloud deployment.",
						Optional:    true,
						Computed:    true,

						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"url": schema.StringAttribute{
						Description: "Elastic Cloud deployment URL.",
						Required:    true,
					},
				},
				Required: true,
			},
		},
	}
}

func (r *datadogIntegrationElasticCloudAccountResource) ImportState(ctx context.Context, request resource.ImportStateRequest, response *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), request, response)
}

func (r *datadogIntegrationElasticCloudAccountResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var state datadogIntegrationElasticCloudAccountResourceModel
	var plan types.Object
	response.Diagnostics.Append(request.Plan.Get(ctx, &plan)...)
	if response.Diagnostics.HasError() {
		return
	}
	response.Diagnostics.Append(plan.As(ctx, &state, basetypes.ObjectAsOptions{UnhandledUnknownAsEmpty: true})...)
	if response.Diagnostics.HasError() {
		return
	}

	authenticationElasticCloudIntegrationAccountBasicAuthPasswordWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationElasticCloudAccountAuthenticationElasticCloudIntegrationAccountBasicAuthPasswordWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	authenticationElasticCloudIntegrationAccountBasicAuthPasswordSecretResult := authenticationElasticCloudIntegrationAccountBasicAuthPasswordWriteOnlySecretHandler.GetSecretForCreate(ctx, &request.Config)
	response.Diagnostics.Append(authenticationElasticCloudIntegrationAccountBasicAuthPasswordSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}

	bodyAttributes := datadogV2.NewElasticCloudIntegrationAccountCreateAttributesWithDefaults()

	if state.Authentication != nil {
		var authenticationUnion datadogV2.ElasticCloudIntegrationAccountAuthenticationRequest
		authenticationMatches := 0
		if state.Authentication.ElasticCloudIntegrationAccountBasicAuth != nil {
			elasticCloudIntegrationAccountBasicAuthVariant := datadogV2.NewElasticCloudIntegrationAccountBasicAuthRequestWithDefaults()

			if !state.Authentication.ElasticCloudIntegrationAccountBasicAuth.AuthType.IsNull() && !state.Authentication.ElasticCloudIntegrationAccountBasicAuth.AuthType.IsUnknown() {
				elasticCloudIntegrationAccountBasicAuthVariant.SetAuthType(datadogV2.ElasticCloudIntegrationAccountBasicAuthType(state.Authentication.ElasticCloudIntegrationAccountBasicAuth.AuthType.ValueString()))
			}

			if authenticationElasticCloudIntegrationAccountBasicAuthPasswordSecretResult.ShouldSetValue {
				elasticCloudIntegrationAccountBasicAuthVariant.SetPassword(authenticationElasticCloudIntegrationAccountBasicAuthPasswordSecretResult.Value)
			}

			elasticCloudIntegrationAccountBasicAuthVariant.SetUsername(state.Authentication.ElasticCloudIntegrationAccountBasicAuth.Username.ValueString())
			authenticationUnion = datadogV2.ElasticCloudIntegrationAccountBasicAuthRequestAsElasticCloudIntegrationAccountAuthenticationRequest(elasticCloudIntegrationAccountBasicAuthVariant)
			authenticationMatches++
		}
		if authenticationMatches != 1 {
			response.Diagnostics.AddError(
				"Invalid authentication",
				fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"elastic_cloud_integration_account_basic_auth\" must be set, got %d", authenticationMatches),
			)
			return
		}
		bodyAttributes.SetAuthentication(authenticationUnion)
	} else {
		response.Diagnostics.AddError(
			"Invalid authentication",
			fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"elastic_cloud_integration_account_basic_auth\" must be set, got %d", 0),
		)
		return
	}

	if state.Dataflows != nil {
		dataflowsValue := datadogV2.NewElasticCloudIntegrationDataflowsRequestWithDefaults()

		if state.Dataflows.ElasticCloudDetailedIndexStats != nil {
			elasticCloudDetailedIndexStatsValue := datadogV2.NewElasticCloudDetailedIndexStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudDetailedIndexStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudDetailedIndexStats.Enabled.IsUnknown() {
				elasticCloudDetailedIndexStatsValue.SetEnabled(state.Dataflows.ElasticCloudDetailedIndexStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudDetailedIndexStats(*elasticCloudDetailedIndexStatsValue)
		}

		if state.Dataflows.ElasticCloudIndexStats != nil {
			elasticCloudIndexStatsValue := datadogV2.NewElasticCloudIndexStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudIndexStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudIndexStats.Enabled.IsUnknown() {
				elasticCloudIndexStatsValue.SetEnabled(state.Dataflows.ElasticCloudIndexStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudIndexStats(*elasticCloudIndexStatsValue)
		}

		if state.Dataflows.ElasticCloudPendingTaskStats != nil {
			elasticCloudPendingTaskStatsValue := datadogV2.NewElasticCloudPendingTaskStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudPendingTaskStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudPendingTaskStats.Enabled.IsUnknown() {
				elasticCloudPendingTaskStatsValue.SetEnabled(state.Dataflows.ElasticCloudPendingTaskStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudPendingTaskStats(*elasticCloudPendingTaskStatsValue)
		}

		if state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout != nil {
			elasticCloudPrimaryShardGracefulTimeoutValue := datadogV2.NewElasticCloudPrimaryShardGracefulTimeoutIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Enabled.IsNull() && !state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Enabled.IsUnknown() {
				elasticCloudPrimaryShardGracefulTimeoutValue.SetEnabled(state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudPrimaryShardGracefulTimeout(*elasticCloudPrimaryShardGracefulTimeoutValue)
		}

		if state.Dataflows.ElasticCloudPrimaryShardStats != nil {
			elasticCloudPrimaryShardStatsValue := datadogV2.NewElasticCloudPrimaryShardStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudPrimaryShardStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudPrimaryShardStats.Enabled.IsUnknown() {
				elasticCloudPrimaryShardStatsValue.SetEnabled(state.Dataflows.ElasticCloudPrimaryShardStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudPrimaryShardStats(*elasticCloudPrimaryShardStatsValue)
		}

		if state.Dataflows.ElasticCloudShardAllocationStats != nil {
			elasticCloudShardAllocationStatsValue := datadogV2.NewElasticCloudShardAllocationStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudShardAllocationStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudShardAllocationStats.Enabled.IsUnknown() {
				elasticCloudShardAllocationStatsValue.SetEnabled(state.Dataflows.ElasticCloudShardAllocationStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudShardAllocationStats(*elasticCloudShardAllocationStatsValue)
		}

		if state.Dataflows.ElasticCloudSlmStats != nil {
			elasticCloudSlmStatsValue := datadogV2.NewElasticCloudSlmStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudSlmStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudSlmStats.Enabled.IsUnknown() {
				elasticCloudSlmStatsValue.SetEnabled(state.Dataflows.ElasticCloudSlmStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudSlmStats(*elasticCloudSlmStatsValue)
		}
		bodyAttributes.SetDataflows(*dataflowsValue)
	}

	bodyAttributes.SetName(state.Name.ValueString())

	settingsValue := datadogV2.NewElasticCloudIntegrationAccountSettingsRequestWithDefaults()

	if !state.Settings.Tags.IsNull() && !state.Settings.Tags.IsUnknown() {
		settingsValue.SetTags(state.Settings.Tags.ValueString())
	}

	settingsValue.SetUrl(state.Settings.Url.ValueString())
	bodyAttributes.SetSettings(*settingsValue)
	bodyData := datadogV2.NewElasticCloudIntegrationAccountCreateDataWithDefaults()
	bodyData.SetType(datadogV2.IntegrationAccountType("integration-account"))
	bodyData.SetAttributes(*bodyAttributes)
	body := datadogV2.NewElasticCloudIntegrationAccountCreateRequestWithDefaults()
	body.SetData(*bodyData)
	resp, _, err := r.Api.CreateElasticCloudIntegrationAccount(r.Auth, *body)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error creating integration_elastic_cloud_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	if state.Authentication != nil {
		if state.Authentication.ElasticCloudIntegrationAccountBasicAuth != nil {
			if state.Authentication.ElasticCloudIntegrationAccountBasicAuth.AuthType.IsUnknown() {
				state.Authentication.ElasticCloudIntegrationAccountBasicAuth.AuthType = types.StringNull()
			}
		}
	}
	if state.Dataflows != nil {
		if state.Dataflows.ElasticCloudDetailedIndexStats != nil {
			if state.Dataflows.ElasticCloudDetailedIndexStats.Enabled.IsUnknown() {
				state.Dataflows.ElasticCloudDetailedIndexStats.Enabled = types.BoolNull()
			}
			if state.Dataflows.ElasticCloudDetailedIndexStats.Status != nil {
				if state.Dataflows.ElasticCloudDetailedIndexStats.Status.Health.IsUnknown() {
					state.Dataflows.ElasticCloudDetailedIndexStats.Status.Health = types.StringNull()
				}
				if state.Dataflows.ElasticCloudDetailedIndexStats.Status.Message.IsUnknown() {
					state.Dataflows.ElasticCloudDetailedIndexStats.Status.Message = types.StringNull()
				}
				if state.Dataflows.ElasticCloudDetailedIndexStats.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.ElasticCloudDetailedIndexStats.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.ElasticCloudIndexStats != nil {
			if state.Dataflows.ElasticCloudIndexStats.Enabled.IsUnknown() {
				state.Dataflows.ElasticCloudIndexStats.Enabled = types.BoolNull()
			}
			if state.Dataflows.ElasticCloudIndexStats.Status != nil {
				if state.Dataflows.ElasticCloudIndexStats.Status.Health.IsUnknown() {
					state.Dataflows.ElasticCloudIndexStats.Status.Health = types.StringNull()
				}
				if state.Dataflows.ElasticCloudIndexStats.Status.Message.IsUnknown() {
					state.Dataflows.ElasticCloudIndexStats.Status.Message = types.StringNull()
				}
				if state.Dataflows.ElasticCloudIndexStats.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.ElasticCloudIndexStats.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.ElasticCloudMetrics != nil {
			if state.Dataflows.ElasticCloudMetrics.Enabled.IsUnknown() {
				state.Dataflows.ElasticCloudMetrics.Enabled = types.BoolNull()
			}
			if state.Dataflows.ElasticCloudMetrics.Status != nil {
				if state.Dataflows.ElasticCloudMetrics.Status.Health.IsUnknown() {
					state.Dataflows.ElasticCloudMetrics.Status.Health = types.StringNull()
				}
				if state.Dataflows.ElasticCloudMetrics.Status.Message.IsUnknown() {
					state.Dataflows.ElasticCloudMetrics.Status.Message = types.StringNull()
				}
				if state.Dataflows.ElasticCloudMetrics.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.ElasticCloudMetrics.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.ElasticCloudPendingTaskStats != nil {
			if state.Dataflows.ElasticCloudPendingTaskStats.Enabled.IsUnknown() {
				state.Dataflows.ElasticCloudPendingTaskStats.Enabled = types.BoolNull()
			}
			if state.Dataflows.ElasticCloudPendingTaskStats.Status != nil {
				if state.Dataflows.ElasticCloudPendingTaskStats.Status.Health.IsUnknown() {
					state.Dataflows.ElasticCloudPendingTaskStats.Status.Health = types.StringNull()
				}
				if state.Dataflows.ElasticCloudPendingTaskStats.Status.Message.IsUnknown() {
					state.Dataflows.ElasticCloudPendingTaskStats.Status.Message = types.StringNull()
				}
				if state.Dataflows.ElasticCloudPendingTaskStats.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.ElasticCloudPendingTaskStats.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout != nil {
			if state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Enabled.IsUnknown() {
				state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Enabled = types.BoolNull()
			}
			if state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Status != nil {
				if state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Status.Health.IsUnknown() {
					state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Status.Health = types.StringNull()
				}
				if state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Status.Message.IsUnknown() {
					state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Status.Message = types.StringNull()
				}
				if state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.ElasticCloudPrimaryShardStats != nil {
			if state.Dataflows.ElasticCloudPrimaryShardStats.Enabled.IsUnknown() {
				state.Dataflows.ElasticCloudPrimaryShardStats.Enabled = types.BoolNull()
			}
			if state.Dataflows.ElasticCloudPrimaryShardStats.Status != nil {
				if state.Dataflows.ElasticCloudPrimaryShardStats.Status.Health.IsUnknown() {
					state.Dataflows.ElasticCloudPrimaryShardStats.Status.Health = types.StringNull()
				}
				if state.Dataflows.ElasticCloudPrimaryShardStats.Status.Message.IsUnknown() {
					state.Dataflows.ElasticCloudPrimaryShardStats.Status.Message = types.StringNull()
				}
				if state.Dataflows.ElasticCloudPrimaryShardStats.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.ElasticCloudPrimaryShardStats.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.ElasticCloudShardAllocationStats != nil {
			if state.Dataflows.ElasticCloudShardAllocationStats.Enabled.IsUnknown() {
				state.Dataflows.ElasticCloudShardAllocationStats.Enabled = types.BoolNull()
			}
			if state.Dataflows.ElasticCloudShardAllocationStats.Status != nil {
				if state.Dataflows.ElasticCloudShardAllocationStats.Status.Health.IsUnknown() {
					state.Dataflows.ElasticCloudShardAllocationStats.Status.Health = types.StringNull()
				}
				if state.Dataflows.ElasticCloudShardAllocationStats.Status.Message.IsUnknown() {
					state.Dataflows.ElasticCloudShardAllocationStats.Status.Message = types.StringNull()
				}
				if state.Dataflows.ElasticCloudShardAllocationStats.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.ElasticCloudShardAllocationStats.Status.UpdatedAt = types.StringNull()
				}
			}
		}
		if state.Dataflows.ElasticCloudSlmStats != nil {
			if state.Dataflows.ElasticCloudSlmStats.Enabled.IsUnknown() {
				state.Dataflows.ElasticCloudSlmStats.Enabled = types.BoolNull()
			}
			if state.Dataflows.ElasticCloudSlmStats.Status != nil {
				if state.Dataflows.ElasticCloudSlmStats.Status.Health.IsUnknown() {
					state.Dataflows.ElasticCloudSlmStats.Status.Health = types.StringNull()
				}
				if state.Dataflows.ElasticCloudSlmStats.Status.Message.IsUnknown() {
					state.Dataflows.ElasticCloudSlmStats.Status.Message = types.StringNull()
				}
				if state.Dataflows.ElasticCloudSlmStats.Status.UpdatedAt.IsUnknown() {
					state.Dataflows.ElasticCloudSlmStats.Status.UpdatedAt = types.StringNull()
				}
			}
		}
	}
	if state.Settings != nil {
		if state.Settings.Tags.IsUnknown() {
			state.Settings.Tags = types.StringNull()
		}
	}
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationElasticCloudAccountResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var state datadogIntegrationElasticCloudAccountResourceModel
	response.Diagnostics.Append(request.State.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	resp, httpResp, err := r.Api.GetElasticCloudIntegrationAccount(r.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			response.State.RemoveResource(ctx)
			return
		}
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error reading integration_elastic_cloud_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationElasticCloudAccountResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var state datadogIntegrationElasticCloudAccountResourceModel
	var plan types.Object
	response.Diagnostics.Append(request.Plan.Get(ctx, &plan)...)
	if response.Diagnostics.HasError() {
		return
	}
	response.Diagnostics.Append(plan.As(ctx, &state, basetypes.ObjectAsOptions{UnhandledUnknownAsEmpty: true})...)
	if response.Diagnostics.HasError() {
		return
	}

	authenticationElasticCloudIntegrationAccountBasicAuthPasswordWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationElasticCloudAccountAuthenticationElasticCloudIntegrationAccountBasicAuthPasswordWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	authenticationElasticCloudIntegrationAccountBasicAuthPasswordSecretResult := authenticationElasticCloudIntegrationAccountBasicAuthPasswordWriteOnlySecretHandler.GetSecretForUpdate(ctx, &request.Config, &request)
	response.Diagnostics.Append(authenticationElasticCloudIntegrationAccountBasicAuthPasswordSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}

	bodyAttributes := datadogV2.NewElasticCloudIntegrationAccountUpdateAttributesWithDefaults()

	if state.Authentication != nil {
		var authenticationUnion datadogV2.ElasticCloudIntegrationAccountAuthenticationUpdate
		authenticationMatches := 0
		if state.Authentication.ElasticCloudIntegrationAccountBasicAuth != nil {
			elasticCloudIntegrationAccountBasicAuthVariant := datadogV2.NewElasticCloudIntegrationAccountBasicAuthUpdateWithDefaults()

			if !state.Authentication.ElasticCloudIntegrationAccountBasicAuth.AuthType.IsNull() && !state.Authentication.ElasticCloudIntegrationAccountBasicAuth.AuthType.IsUnknown() {
				elasticCloudIntegrationAccountBasicAuthVariant.SetAuthType(datadogV2.ElasticCloudIntegrationAccountBasicAuthType(state.Authentication.ElasticCloudIntegrationAccountBasicAuth.AuthType.ValueString()))
			}

			if authenticationElasticCloudIntegrationAccountBasicAuthPasswordSecretResult.ShouldSetValue {
				elasticCloudIntegrationAccountBasicAuthVariant.SetPassword(authenticationElasticCloudIntegrationAccountBasicAuthPasswordSecretResult.Value)
			}

			elasticCloudIntegrationAccountBasicAuthVariant.SetUsername(state.Authentication.ElasticCloudIntegrationAccountBasicAuth.Username.ValueString())
			authenticationUnion = datadogV2.ElasticCloudIntegrationAccountBasicAuthUpdateAsElasticCloudIntegrationAccountAuthenticationUpdate(elasticCloudIntegrationAccountBasicAuthVariant)
			authenticationMatches++
		}
		if authenticationMatches != 1 {
			response.Diagnostics.AddError(
				"Invalid authentication",
				fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"elastic_cloud_integration_account_basic_auth\" must be set, got %d", authenticationMatches),
			)
			return
		}
		bodyAttributes.SetAuthentication(authenticationUnion)
	} else {
		response.Diagnostics.AddError(
			"Invalid authentication",
			fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"elastic_cloud_integration_account_basic_auth\" must be set, got %d", 0),
		)
		return
	}

	if state.Dataflows != nil {
		dataflowsValue := datadogV2.NewElasticCloudIntegrationDataflowsRequestWithDefaults()

		if state.Dataflows.ElasticCloudDetailedIndexStats != nil {
			elasticCloudDetailedIndexStatsValue := datadogV2.NewElasticCloudDetailedIndexStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudDetailedIndexStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudDetailedIndexStats.Enabled.IsUnknown() {
				elasticCloudDetailedIndexStatsValue.SetEnabled(state.Dataflows.ElasticCloudDetailedIndexStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudDetailedIndexStats(*elasticCloudDetailedIndexStatsValue)
		}

		if state.Dataflows.ElasticCloudIndexStats != nil {
			elasticCloudIndexStatsValue := datadogV2.NewElasticCloudIndexStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudIndexStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudIndexStats.Enabled.IsUnknown() {
				elasticCloudIndexStatsValue.SetEnabled(state.Dataflows.ElasticCloudIndexStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudIndexStats(*elasticCloudIndexStatsValue)
		}

		if state.Dataflows.ElasticCloudPendingTaskStats != nil {
			elasticCloudPendingTaskStatsValue := datadogV2.NewElasticCloudPendingTaskStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudPendingTaskStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudPendingTaskStats.Enabled.IsUnknown() {
				elasticCloudPendingTaskStatsValue.SetEnabled(state.Dataflows.ElasticCloudPendingTaskStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudPendingTaskStats(*elasticCloudPendingTaskStatsValue)
		}

		if state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout != nil {
			elasticCloudPrimaryShardGracefulTimeoutValue := datadogV2.NewElasticCloudPrimaryShardGracefulTimeoutIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Enabled.IsNull() && !state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Enabled.IsUnknown() {
				elasticCloudPrimaryShardGracefulTimeoutValue.SetEnabled(state.Dataflows.ElasticCloudPrimaryShardGracefulTimeout.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudPrimaryShardGracefulTimeout(*elasticCloudPrimaryShardGracefulTimeoutValue)
		}

		if state.Dataflows.ElasticCloudPrimaryShardStats != nil {
			elasticCloudPrimaryShardStatsValue := datadogV2.NewElasticCloudPrimaryShardStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudPrimaryShardStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudPrimaryShardStats.Enabled.IsUnknown() {
				elasticCloudPrimaryShardStatsValue.SetEnabled(state.Dataflows.ElasticCloudPrimaryShardStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudPrimaryShardStats(*elasticCloudPrimaryShardStatsValue)
		}

		if state.Dataflows.ElasticCloudShardAllocationStats != nil {
			elasticCloudShardAllocationStatsValue := datadogV2.NewElasticCloudShardAllocationStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudShardAllocationStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudShardAllocationStats.Enabled.IsUnknown() {
				elasticCloudShardAllocationStatsValue.SetEnabled(state.Dataflows.ElasticCloudShardAllocationStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudShardAllocationStats(*elasticCloudShardAllocationStatsValue)
		}

		if state.Dataflows.ElasticCloudSlmStats != nil {
			elasticCloudSlmStatsValue := datadogV2.NewElasticCloudSlmStatsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.ElasticCloudSlmStats.Enabled.IsNull() && !state.Dataflows.ElasticCloudSlmStats.Enabled.IsUnknown() {
				elasticCloudSlmStatsValue.SetEnabled(state.Dataflows.ElasticCloudSlmStats.Enabled.ValueBool())
			}
			dataflowsValue.SetElasticCloudSlmStats(*elasticCloudSlmStatsValue)
		}
		bodyAttributes.SetDataflows(*dataflowsValue)
	}

	bodyAttributes.SetName(state.Name.ValueString())

	settingsValue := datadogV2.NewElasticCloudIntegrationAccountSettingsUpdateWithDefaults()

	if !state.Settings.Tags.IsNull() && !state.Settings.Tags.IsUnknown() {
		settingsValue.SetTags(state.Settings.Tags.ValueString())
	}

	settingsValue.SetUrl(state.Settings.Url.ValueString())
	bodyAttributes.SetSettings(*settingsValue)
	bodyData := datadogV2.NewElasticCloudIntegrationAccountUpdateDataWithDefaults()
	bodyData.SetType(datadogV2.IntegrationAccountType("integration-account"))
	bodyData.SetId(state.ID.ValueString())
	bodyData.SetAttributes(*bodyAttributes)
	body := datadogV2.NewElasticCloudIntegrationAccountUpdateRequestWithDefaults()
	body.SetData(*bodyData)
	resp, _, err := r.Api.UpdateElasticCloudIntegrationAccount(r.Auth, state.ID.ValueString(), *body)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error updating integration_elastic_cloud_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationElasticCloudAccountResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var state datadogIntegrationElasticCloudAccountResourceModel
	response.Diagnostics.Append(request.State.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.Api.DeleteElasticCloudIntegrationAccount(r.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			return
		}
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error deleting integration_elastic_cloud_account"))
	}
}

// updateState maps *datadogV2.ElasticCloudIntegrationAccountResponse into state, returning diagnostics
// rather than writing them so it stays free of the resource request/response
// types and can fail at a specific schema path. Shared by Create, Read and
// Update, which all resolve the same response type.
func (r *datadogIntegrationElasticCloudAccountResource) updateState(ctx context.Context, state *datadogIntegrationElasticCloudAccountResourceModel, resp *datadogV2.ElasticCloudIntegrationAccountResponse) diag.Diagnostics {
	var diags diag.Diagnostics
	attributes := resp.Data.GetAttributes()
	if id, ok := resp.Data.GetIdOk(); ok && id != nil {
		state.ID = types.StringValue(*id)
	}
	if name, ok := attributes.GetNameOk(); ok && name != nil {
		state.Name = types.StringValue(*name)
	}
	if authentication, ok := attributes.GetAuthenticationOk(); ok && authentication != nil {
		authenticationEnvelope := &datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountAuthenticationModel{}
		authenticationMatches := 0
		if elasticCloudIntegrationAccountBasicAuthVariant := authentication.ElasticCloudIntegrationAccountBasicAuthResponse; elasticCloudIntegrationAccountBasicAuthVariant != nil {
			elasticCloudIntegrationAccountBasicAuthModel := &datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountAuthenticationElasticCloudIntegrationAccountBasicAuthModel{}
			if state.Authentication != nil && state.Authentication.ElasticCloudIntegrationAccountBasicAuth != nil {
				elasticCloudIntegrationAccountBasicAuthModel = state.Authentication.ElasticCloudIntegrationAccountBasicAuth
			}
			if authType, ok := elasticCloudIntegrationAccountBasicAuthVariant.GetAuthTypeOk(); ok && authType != nil {
				elasticCloudIntegrationAccountBasicAuthModel.AuthType = types.StringValue(string(*authType))
			}
			if username, ok := elasticCloudIntegrationAccountBasicAuthVariant.GetUsernameOk(); ok && username != nil {
				elasticCloudIntegrationAccountBasicAuthModel.Username = types.StringValue(*username)
			}
			authenticationEnvelope.ElasticCloudIntegrationAccountBasicAuth = elasticCloudIntegrationAccountBasicAuthModel
			authenticationMatches++
		}
		switch {
		case authentication.UnparsedObject != nil:
			diags.AddError(
				"unexpected ElasticCloudIntegrationAccountAuthenticationResponse in the API response",
				"resource.data.attributes.authentication: the Datadog API returned a value none of the ElasticCloudIntegrationAccountAuthenticationResponse alternatives could parse",
			)
		case authenticationMatches > 1:
			diags.AddError(
				"ambiguous ElasticCloudIntegrationAccountAuthenticationResponse in the API response",
				fmt.Sprintf("resource.data.attributes.authentication: the Datadog API response matched %d ElasticCloudIntegrationAccountAuthenticationResponse alternatives, expected exactly one", authenticationMatches),
			)
		case authenticationMatches == 1:
			state.Authentication = authenticationEnvelope
		}
	}
	if dataflows, ok := attributes.GetDataflowsOk(); ok && dataflows != nil {
		dataflowsModel := state.Dataflows
		if dataflowsModel == nil {
			dataflowsModel = &datadogIntegrationElasticCloudAccountElasticCloudIntegrationDataflowsResponseModel{}
		}
		if elasticCloudDetailedIndexStats, ok := dataflows.GetElasticCloudDetailedIndexStatsOk(); ok && elasticCloudDetailedIndexStats != nil {
			elasticCloudDetailedIndexStatsModel := dataflowsModel.ElasticCloudDetailedIndexStats
			if elasticCloudDetailedIndexStatsModel == nil {
				elasticCloudDetailedIndexStatsModel = &datadogIntegrationElasticCloudAccountElasticCloudDetailedIndexStatsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := elasticCloudDetailedIndexStats.GetEnabledOk(); ok && enabled != nil {
				elasticCloudDetailedIndexStatsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := elasticCloudDetailedIndexStats.GetStatusOk(); ok && status != nil {
				statusModel := elasticCloudDetailedIndexStatsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				elasticCloudDetailedIndexStatsModel.Status = statusModel
			}
			dataflowsModel.ElasticCloudDetailedIndexStats = elasticCloudDetailedIndexStatsModel
		}
		if elasticCloudIndexStats, ok := dataflows.GetElasticCloudIndexStatsOk(); ok && elasticCloudIndexStats != nil {
			elasticCloudIndexStatsModel := dataflowsModel.ElasticCloudIndexStats
			if elasticCloudIndexStatsModel == nil {
				elasticCloudIndexStatsModel = &datadogIntegrationElasticCloudAccountElasticCloudIndexStatsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := elasticCloudIndexStats.GetEnabledOk(); ok && enabled != nil {
				elasticCloudIndexStatsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := elasticCloudIndexStats.GetStatusOk(); ok && status != nil {
				statusModel := elasticCloudIndexStatsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				elasticCloudIndexStatsModel.Status = statusModel
			}
			dataflowsModel.ElasticCloudIndexStats = elasticCloudIndexStatsModel
		}
		if elasticCloudMetrics, ok := dataflows.GetElasticCloudMetricsOk(); ok && elasticCloudMetrics != nil {
			elasticCloudMetricsModel := dataflowsModel.ElasticCloudMetrics
			if elasticCloudMetricsModel == nil {
				elasticCloudMetricsModel = &datadogIntegrationElasticCloudAccountElasticCloudMetricsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := elasticCloudMetrics.GetEnabledOk(); ok && enabled != nil {
				elasticCloudMetricsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := elasticCloudMetrics.GetStatusOk(); ok && status != nil {
				statusModel := elasticCloudMetricsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				elasticCloudMetricsModel.Status = statusModel
			}
			dataflowsModel.ElasticCloudMetrics = elasticCloudMetricsModel
		}
		if elasticCloudPendingTaskStats, ok := dataflows.GetElasticCloudPendingTaskStatsOk(); ok && elasticCloudPendingTaskStats != nil {
			elasticCloudPendingTaskStatsModel := dataflowsModel.ElasticCloudPendingTaskStats
			if elasticCloudPendingTaskStatsModel == nil {
				elasticCloudPendingTaskStatsModel = &datadogIntegrationElasticCloudAccountElasticCloudPendingTaskStatsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := elasticCloudPendingTaskStats.GetEnabledOk(); ok && enabled != nil {
				elasticCloudPendingTaskStatsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := elasticCloudPendingTaskStats.GetStatusOk(); ok && status != nil {
				statusModel := elasticCloudPendingTaskStatsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				elasticCloudPendingTaskStatsModel.Status = statusModel
			}
			dataflowsModel.ElasticCloudPendingTaskStats = elasticCloudPendingTaskStatsModel
		}
		if elasticCloudPrimaryShardGracefulTimeout, ok := dataflows.GetElasticCloudPrimaryShardGracefulTimeoutOk(); ok && elasticCloudPrimaryShardGracefulTimeout != nil {
			elasticCloudPrimaryShardGracefulTimeoutModel := dataflowsModel.ElasticCloudPrimaryShardGracefulTimeout
			if elasticCloudPrimaryShardGracefulTimeoutModel == nil {
				elasticCloudPrimaryShardGracefulTimeoutModel = &datadogIntegrationElasticCloudAccountElasticCloudPrimaryShardGracefulTimeoutIntegrationDataflowResponseModel{}
			}
			if enabled, ok := elasticCloudPrimaryShardGracefulTimeout.GetEnabledOk(); ok && enabled != nil {
				elasticCloudPrimaryShardGracefulTimeoutModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := elasticCloudPrimaryShardGracefulTimeout.GetStatusOk(); ok && status != nil {
				statusModel := elasticCloudPrimaryShardGracefulTimeoutModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				elasticCloudPrimaryShardGracefulTimeoutModel.Status = statusModel
			}
			dataflowsModel.ElasticCloudPrimaryShardGracefulTimeout = elasticCloudPrimaryShardGracefulTimeoutModel
		}
		if elasticCloudPrimaryShardStats, ok := dataflows.GetElasticCloudPrimaryShardStatsOk(); ok && elasticCloudPrimaryShardStats != nil {
			elasticCloudPrimaryShardStatsModel := dataflowsModel.ElasticCloudPrimaryShardStats
			if elasticCloudPrimaryShardStatsModel == nil {
				elasticCloudPrimaryShardStatsModel = &datadogIntegrationElasticCloudAccountElasticCloudPrimaryShardStatsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := elasticCloudPrimaryShardStats.GetEnabledOk(); ok && enabled != nil {
				elasticCloudPrimaryShardStatsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := elasticCloudPrimaryShardStats.GetStatusOk(); ok && status != nil {
				statusModel := elasticCloudPrimaryShardStatsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				elasticCloudPrimaryShardStatsModel.Status = statusModel
			}
			dataflowsModel.ElasticCloudPrimaryShardStats = elasticCloudPrimaryShardStatsModel
		}
		if elasticCloudShardAllocationStats, ok := dataflows.GetElasticCloudShardAllocationStatsOk(); ok && elasticCloudShardAllocationStats != nil {
			elasticCloudShardAllocationStatsModel := dataflowsModel.ElasticCloudShardAllocationStats
			if elasticCloudShardAllocationStatsModel == nil {
				elasticCloudShardAllocationStatsModel = &datadogIntegrationElasticCloudAccountElasticCloudShardAllocationStatsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := elasticCloudShardAllocationStats.GetEnabledOk(); ok && enabled != nil {
				elasticCloudShardAllocationStatsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := elasticCloudShardAllocationStats.GetStatusOk(); ok && status != nil {
				statusModel := elasticCloudShardAllocationStatsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				elasticCloudShardAllocationStatsModel.Status = statusModel
			}
			dataflowsModel.ElasticCloudShardAllocationStats = elasticCloudShardAllocationStatsModel
		}
		if elasticCloudSlmStats, ok := dataflows.GetElasticCloudSlmStatsOk(); ok && elasticCloudSlmStats != nil {
			elasticCloudSlmStatsModel := dataflowsModel.ElasticCloudSlmStats
			if elasticCloudSlmStatsModel == nil {
				elasticCloudSlmStatsModel = &datadogIntegrationElasticCloudAccountElasticCloudSlmStatsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := elasticCloudSlmStats.GetEnabledOk(); ok && enabled != nil {
				elasticCloudSlmStatsModel.Enabled = types.BoolValue(*enabled)
			}
			if status, ok := elasticCloudSlmStats.GetStatusOk(); ok && status != nil {
				statusModel := elasticCloudSlmStatsModel.Status
				if statusModel == nil {
					statusModel = &datadogIntegrationElasticCloudAccountIntegrationAccountDataflowStatusModel{}
				}
				if health, ok := status.GetHealthOk(); ok && health != nil {
					statusModel.Health = types.StringValue(string(*health))
				}
				if message, ok := status.GetMessageOk(); ok && message != nil {
					statusModel.Message = types.StringValue(*message)
				}
				if updatedAt, ok := status.GetUpdatedAtOk(); ok && updatedAt != nil {
					statusModel.UpdatedAt = types.StringValue(updatedAt.String())
				}
				elasticCloudSlmStatsModel.Status = statusModel
			}
			dataflowsModel.ElasticCloudSlmStats = elasticCloudSlmStatsModel
		}
		state.Dataflows = dataflowsModel
	}
	if settings, ok := attributes.GetSettingsOk(); ok && settings != nil {
		settingsModel := state.Settings
		if settingsModel == nil {
			settingsModel = &datadogIntegrationElasticCloudAccountElasticCloudIntegrationAccountSettingsResponseModel{}
		}
		if tags, ok := settings.GetTagsOk(); ok && tags != nil {
			settingsModel.Tags = types.StringValue(*tags)
		}
		if url, ok := settings.GetUrlOk(); ok && url != nil {
			settingsModel.Url = types.StringValue(*url)
		}
		state.Settings = settingsModel
	}
	return diags
}
