// Code generated by tfgen; DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/fwutils"
	"github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils"
)

var (
	_ resource.ResourceWithConfigure   = &datadogIntegrationDatabricksAccountResource{}
	_ resource.ResourceWithImportState = &datadogIntegrationDatabricksAccountResource{}
)
var datadogIntegrationDatabricksAccountAuthenticationDatabricksIntegrationAccountBearerTokenAuthTokenWriteOnlySecretConfig = fwutils.WriteOnlySecretConfig{OriginalAttr: "token", WriteOnlyAttr: "token_wo", TriggerAttr: "token_wo_version", WriteOnlyDescription: "Secret token used to authenticate with Databricks. This write-only value is not stored in Terraform state.", TriggerDescription: "Version trigger for token_wo rotation.", ParentBlocks: []string{"authentication", "databricks_integration_account_bearer_token_auth"}, Mode: fwutils.WriteOnlySecretModeOnly, Required: false}
var datadogIntegrationDatabricksAccountAuthenticationDatabricksIntegrationAccountOAuthAuthClientSecretWriteOnlySecretConfig = fwutils.WriteOnlySecretConfig{OriginalAttr: "client_secret", WriteOnlyAttr: "client_secret_wo", TriggerAttr: "client_secret_wo_version", WriteOnlyDescription: "Secret of the Databricks service principal. Generate it under User management > Service principals > Credentials & secrets in Databricks. This write-only value is not stored in Terraform state.", TriggerDescription: "Version trigger for client_secret_wo rotation.", ParentBlocks: []string{"authentication", "databricks_integration_account_o_auth_auth"}, Mode: fwutils.WriteOnlySecretModeOnly, Required: true}
var datadogIntegrationDatabricksAccountDataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretWriteOnlySecretConfig = fwutils.WriteOnlySecretConfig{OriginalAttr: "dd_api_key_secret", WriteOnlyAttr: "dd_api_key_secret_wo", TriggerAttr: "dd_api_key_secret_wo_version", WriteOnlyDescription: "Secret value of the Datadog API key identified by `dd_api_key_id`. This write-only value is not stored in Terraform state.", TriggerDescription: "Version trigger for dd_api_key_secret_wo rotation.", ParentBlocks: []string{"dataflows", "databricks_data_observability_jobs_monitoring", "settings"}, Mode: fwutils.WriteOnlySecretModeOnly, Required: false}

type datadogIntegrationDatabricksAccountResourceModel struct {
	ID             types.String                                                                          `tfsdk:"id"`
	Authentication *datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationModel   `tfsdk:"authentication"`
	Dataflows      *datadogIntegrationDatabricksAccountDatabricksIntegrationDataflowsResponseModel       `tfsdk:"dataflows"`
	Name           types.String                                                                          `tfsdk:"name"`
	Settings       *datadogIntegrationDatabricksAccountDatabricksIntegrationAccountSettingsResponseModel `tfsdk:"settings"`
}

type datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationModel struct {
	DatabricksIntegrationAccountBearerTokenAuth         *datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountBearerTokenAuthModel         `tfsdk:"databricks_integration_account_bearer_token_auth"`
	DatabricksIntegrationAccountOAuthAuth               *datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountOAuthAuthModel               `tfsdk:"databricks_integration_account_o_auth_auth"`
	DatabricksIntegrationAccountPrivateActionRunnerAuth *datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountPrivateActionRunnerAuthModel `tfsdk:"databricks_integration_account_private_action_runner_auth"`
}

type datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountBearerTokenAuthModel struct {
	AuthType       types.String `tfsdk:"auth_type"`
	TokenWo        types.String `tfsdk:"token_wo"`
	TokenWoVersion types.String `tfsdk:"token_wo_version"`
}

type datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountOAuthAuthModel struct {
	AuthType              types.String `tfsdk:"auth_type"`
	AzureTenantId         types.String `tfsdk:"azure_tenant_id"`
	ClientId              types.String `tfsdk:"client_id"`
	ClientSecretWo        types.String `tfsdk:"client_secret_wo"`
	ClientSecretWoVersion types.String `tfsdk:"client_secret_wo_version"`
}

type datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountPrivateActionRunnerAuthModel struct {
	AuthType     types.String `tfsdk:"auth_type"`
	ConnectionId types.String `tfsdk:"connection_id"`
	SecretPath   types.String `tfsdk:"secret_path"`
	UserUuid     types.String `tfsdk:"user_uuid"`
}

type datadogIntegrationDatabricksAccountDatabricksIntegrationDataflowsResponseModel struct {
	DatabricksCloudCostMetrics                   *datadogIntegrationDatabricksAccountDatabricksCloudCostMetricsIntegrationDataflowResponseModel                   `tfsdk:"databricks_cloud_cost_metrics"`
	DatabricksDataObservabilityJobsMonitoring    *datadogIntegrationDatabricksAccountDatabricksDataObservabilityJobsMonitoringIntegrationDataflowResponseModel    `tfsdk:"databricks_data_observability_jobs_monitoring"`
	DatabricksDataObservabilityQualityMonitoring *datadogIntegrationDatabricksAccountDatabricksDataObservabilityQualityMonitoringIntegrationDataflowResponseModel `tfsdk:"databricks_data_observability_quality_monitoring"`
	DatabricksModelServingMetrics                *datadogIntegrationDatabricksAccountDatabricksModelServingMetricsIntegrationDataflowResponseModel                `tfsdk:"databricks_model_serving_metrics"`
}

type datadogIntegrationDatabricksAccountDatabricksCloudCostMetricsIntegrationDataflowResponseModel struct {
	Enabled  types.Bool                                                                                             `tfsdk:"enabled"`
	Settings *datadogIntegrationDatabricksAccountDatabricksCloudCostMetricsIntegrationDataflowSettingsResponseModel `tfsdk:"settings"`
}

type datadogIntegrationDatabricksAccountDatabricksCloudCostMetricsIntegrationDataflowSettingsResponseModel struct {
	CcmCollectAllWorkspaces types.Bool `tfsdk:"ccm_collect_all_workspaces"`
}

type datadogIntegrationDatabricksAccountDatabricksDataObservabilityJobsMonitoringIntegrationDataflowResponseModel struct {
	Enabled  types.Bool                                                                                                            `tfsdk:"enabled"`
	Settings *datadogIntegrationDatabricksAccountDatabricksDataObservabilityJobsMonitoringIntegrationDataflowSettingsResponseModel `tfsdk:"settings"`
}

type datadogIntegrationDatabricksAccountDatabricksDataObservabilityJobsMonitoringIntegrationDataflowSettingsResponseModel struct {
	DdApiKeyId                 types.String `tfsdk:"dd_api_key_id"`
	DdApiKeySecretWo           types.String `tfsdk:"dd_api_key_secret_wo"`
	DdApiKeySecretWoVersion    types.String `tfsdk:"dd_api_key_secret_wo_version"`
	DjmGlobalInitScriptEnabled types.Bool   `tfsdk:"djm_global_init_script_enabled"`
	ScriptGpumEnabled          types.Bool   `tfsdk:"script_gpum_enabled"`
	ScriptLogsEnabled          types.Bool   `tfsdk:"script_logs_enabled"`
	ServerlessJobsEnabled      types.Bool   `tfsdk:"serverless_jobs_enabled"`
}

type datadogIntegrationDatabricksAccountDatabricksDataObservabilityQualityMonitoringIntegrationDataflowResponseModel struct {
	Enabled  types.Bool                                                                                                               `tfsdk:"enabled"`
	Settings *datadogIntegrationDatabricksAccountDatabricksDataObservabilityQualityMonitoringIntegrationDataflowSettingsResponseModel `tfsdk:"settings"`
}

type datadogIntegrationDatabricksAccountDatabricksDataObservabilityQualityMonitoringIntegrationDataflowSettingsResponseModel struct {
	DoCrawlersCron    types.String `tfsdk:"do_crawlers_cron"`
	SyncSystemCatalog types.Bool   `tfsdk:"sync_system_catalog"`
}

type datadogIntegrationDatabricksAccountDatabricksModelServingMetricsIntegrationDataflowResponseModel struct {
	Enabled types.Bool `tfsdk:"enabled"`
}

type datadogIntegrationDatabricksAccountDatabricksIntegrationAccountSettingsResponseModel struct {
	SystemTablesSqlWarehouseId types.String `tfsdk:"system_tables_sql_warehouse_id"`
	WorkspaceUrl               types.String `tfsdk:"workspace_url"`
}

type datadogIntegrationDatabricksAccountResource struct {
	Api  *datadogV2.DatabricksIntegrationApi
	Auth context.Context
}

func NewDatadogIntegrationDatabricksAccountResource() resource.Resource {
	return &datadogIntegrationDatabricksAccountResource{}
}

func (r *datadogIntegrationDatabricksAccountResource) Configure(_ context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	providerData, _ := request.ProviderData.(*FrameworkProvider)
	r.Api = datadogV2.NewDatabricksIntegrationApi(providerData.DatadogApiInstances.HttpClient)
	r.Auth = providerData.Auth
}

func (r *datadogIntegrationDatabricksAccountResource) Metadata(_ context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = "integration_databricks_account"
}

func (r *datadogIntegrationDatabricksAccountResource) Schema(_ context.Context, _ resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Provides a Datadog Databricks integration account resource.",

		Attributes: map[string]schema.Attribute{
			"id": utils.ResourceIDAttribute(),
			"name": schema.StringAttribute{
				Description: "Human-readable name of the Databricks integration account.",
				Required:    true,
			},

			"authentication": schema.SingleNestedAttribute{
				Description: "Authentication configured on the Databricks integration account. A `bearer_token` method indicates an account still on token authentication, which Databricks accepts only on accounts that already use it.",

				Attributes: map[string]schema.Attribute{
					"databricks_integration_account_bearer_token_auth": schema.SingleNestedAttribute{
						Description: "The bearer token authentication method configured on the account.",

						Attributes: fwutils.MergeAttributes(
							map[string]schema.Attribute{
								"auth_type": schema.StringAttribute{
									Description: "The authentication method type.",
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOf("bearer_token"),
									},

									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
							fwutils.CreateWriteOnlySecretAttributes(datadogIntegrationDatabricksAccountAuthenticationDatabricksIntegrationAccountBearerTokenAuthTokenWriteOnlySecretConfig),
						),
						Optional: true,

						Validators: []validator.Object{
							objectvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("databricks_integration_account_o_auth_auth"), path.MatchRelative().AtParent().AtName("databricks_integration_account_private_action_runner_auth")),
						},
					},

					"databricks_integration_account_o_auth_auth": schema.SingleNestedAttribute{
						Description: "The Databricks OAuth authentication method and service principal configured on the account.",

						Attributes: fwutils.MergeAttributes(
							map[string]schema.Attribute{
								"auth_type": schema.StringAttribute{
									Description: "The authentication method type.",
									Default:     stringdefault.StaticString("databricks_oauth"),
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOf("databricks_oauth"),
									},

									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"azure_tenant_id": schema.StringAttribute{
									Description: "Microsoft Entra ID tenant of the service principal, for Azure Databricks workspaces.",
									Optional:    true,
									Computed:    true,

									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"client_id": schema.StringAttribute{
									Description: "Client ID of the Databricks service principal.",
									Required:    true,
								},
							},
							fwutils.CreateWriteOnlySecretAttributes(datadogIntegrationDatabricksAccountAuthenticationDatabricksIntegrationAccountOAuthAuthClientSecretWriteOnlySecretConfig),
						),
						Optional: true,

						Validators: []validator.Object{
							objectvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("databricks_integration_account_bearer_token_auth"), path.MatchRelative().AtParent().AtName("databricks_integration_account_private_action_runner_auth")),
						},
					},

					"databricks_integration_account_private_action_runner_auth": schema.SingleNestedAttribute{
						Description: "The Private Action Runner authentication method configured on the account.",

						Attributes: map[string]schema.Attribute{
							"auth_type": schema.StringAttribute{
								Description: "The authentication method type.",
								Default:     stringdefault.StaticString("private_action_runner"),
								Optional:    true,
								Computed:    true,
								Validators: []validator.String{
									stringvalidator.OneOf("private_action_runner"),
								},

								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"connection_id": schema.StringAttribute{
								Description: "Unique identifier of the Private Action Runner connection holding the credentials.",
								Required:    true,
							},
							"secret_path": schema.StringAttribute{
								Description: "Path of the credential inside the secret backend configured on the runner.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"user_uuid": schema.StringAttribute{
								Description: "Unique identifier of the user the Private Action Runner connection belongs to.",
								Required:    true,
							},
						},
						Optional: true,
						Computed: true,

						Validators: []validator.Object{
							objectvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("databricks_integration_account_bearer_token_auth"), path.MatchRelative().AtParent().AtName("databricks_integration_account_o_auth_auth")),
						},
					},
				},
				Required: true,
			},

			"dataflows": schema.SingleNestedAttribute{
				Description: "Data Datadog collects from Databricks, keyed by dataflow id.",

				Attributes: map[string]schema.Attribute{
					"databricks_cloud_cost_metrics": schema.SingleNestedAttribute{
						Description: "Cost data collected from your Databricks system tables. Requires [Cloud Cost Management](https://docs.datadoghq.com/cloud_cost_management/) to be set up for your organization.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"settings": schema.SingleNestedAttribute{
								Description: "Settings of the Cloud Cost Management dataflow.",

								Attributes: map[string]schema.Attribute{
									"ccm_collect_all_workspaces": schema.BoolAttribute{
										Description: "Whether cost data is collected for every workspace in the Databricks account rather than this workspace only. This takes effect across the Databricks account: if any one workspace enables it, Datadog collects cost data for all of them regardless of their individual settings, and every covered workspace incurs Cloud Cost Management charges.",
										Optional:    true,
										Computed:    true,

										PlanModifiers: []planmodifier.Bool{
											boolplanmodifier.UseStateForUnknown(),
										},
									},
								},
								Optional: true,
								Computed: true,

								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"databricks_data_observability_jobs_monitoring": schema.SingleNestedAttribute{
						Description: "Data Jobs Monitoring, which collects performance, reliability, and cost data for your Databricks jobs.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"settings": schema.SingleNestedAttribute{
								Description: "Settings of the Data Jobs Monitoring dataflow.",

								Attributes: fwutils.MergeAttributes(
									map[string]schema.Attribute{
										"dd_api_key_id": schema.StringAttribute{
											Description: "ID of the Datadog API key the global init script uses to submit data.",
											Optional:    true,
											Computed:    true,

											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"djm_global_init_script_enabled": schema.BoolAttribute{
											Description: "Whether Datadog installs and manages the Agent on your Databricks clusters through a global init script. The script does not apply to clusters in Standard access mode. When `false`, the Agent is installed manually.",
											Optional:    true,
											Computed:    true,

											PlanModifiers: []planmodifier.Bool{
												boolplanmodifier.UseStateForUnknown(),
											},
										},
										"script_gpum_enabled": schema.BoolAttribute{
											Description: "Whether GPU metrics are collected from your Databricks clusters. The Agent installed by the global init script performs the collection, so this requires the dataflow to be enabled with `djm_global_init_script_enabled` set to `true`.",
											Optional:    true,
											Computed:    true,

											PlanModifiers: []planmodifier.Bool{
												boolplanmodifier.UseStateForUnknown(),
											},
										},
										"script_logs_enabled": schema.BoolAttribute{
											Description: "Whether driver and worker logs are collected from your Databricks clusters. The Agent installed by the global init script performs the collection, so this requires the dataflow to be enabled with `djm_global_init_script_enabled` set to `true`.",
											Optional:    true,
											Computed:    true,

											PlanModifiers: []planmodifier.Bool{
												boolplanmodifier.UseStateForUnknown(),
											},
										},
										"serverless_jobs_enabled": schema.BoolAttribute{
											Description: "Whether health and cost data is collected for jobs running on Serverless or SQL Warehouse compute. This compute has no clusters for the global init script to target, so collection reads the Databricks system tables and requires `system_tables_sql_warehouse_id`.",
											Optional:    true,
											Computed:    true,

											PlanModifiers: []planmodifier.Bool{
												boolplanmodifier.UseStateForUnknown(),
											},
										},
									},
									fwutils.CreateWriteOnlySecretAttributes(datadogIntegrationDatabricksAccountDataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretWriteOnlySecretConfig),
								),
								Optional: true,
							},
						},
						Optional: true,
					},

					"databricks_data_observability_quality_monitoring": schema.SingleNestedAttribute{
						Description: "Data Observability, which collects lineage and data quality information from your Databricks catalogs so you can explore how data flows and detect, resolve, and prevent quality issues.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},

							"settings": schema.SingleNestedAttribute{
								Description: "Settings of the Data Observability dataflow.",

								Attributes: map[string]schema.Attribute{
									"do_crawlers_cron": schema.StringAttribute{
										Description: "Cron expression setting how often Datadog connects to your Databricks warehouse to collect metadata. Currently, only hourly (`0 * * * *`) and daily (`0 0 * * *`) are supported.",
										Optional:    true,
										Computed:    true,

										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"sync_system_catalog": schema.BoolAttribute{
										Description: "Whether metadata from the Databricks `system` catalog is included in Data Observability alongside your data catalogs.",
										Optional:    true,
										Computed:    true,

										PlanModifiers: []planmodifier.Bool{
											boolplanmodifier.UseStateForUnknown(),
										},
									},
								},
								Optional: true,
								Computed: true,

								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},

					"databricks_model_serving_metrics": schema.SingleNestedAttribute{
						Description: "Health and usage metrics for your Databricks model serving endpoints. Not supported on accounts that authenticate with `private_action_runner`; on those accounts this dataflow collects no data.",

						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Description: "Whether Datadog collects this data.",
								Optional:    true,
								Computed:    true,

								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},
						},
						Optional: true,
						Computed: true,

						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
					},
				},
				Optional: true,
			},

			"settings": schema.SingleNestedAttribute{
				Description: "Settings configured on the Databricks integration account.",

				Attributes: map[string]schema.Attribute{
					"system_tables_sql_warehouse_id": schema.StringAttribute{
						Description: "ID of the SQL warehouse used to query the Databricks system tables.",
						Optional:    true,
						Computed:    true,

						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"workspace_url": schema.StringAttribute{
						Description: "URL of the Databricks workspace.",
						Required:    true,
					},
				},
				Required: true,
			},
		},
	}
}

func (r *datadogIntegrationDatabricksAccountResource) ImportState(ctx context.Context, request resource.ImportStateRequest, response *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), request, response)
}

func (r *datadogIntegrationDatabricksAccountResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var state datadogIntegrationDatabricksAccountResourceModel
	var plan types.Object
	response.Diagnostics.Append(request.Plan.Get(ctx, &plan)...)
	if response.Diagnostics.HasError() {
		return
	}
	response.Diagnostics.Append(plan.As(ctx, &state, basetypes.ObjectAsOptions{UnhandledUnknownAsEmpty: true})...)
	if response.Diagnostics.HasError() {
		return
	}

	authenticationDatabricksIntegrationAccountOAuthAuthClientSecretWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationDatabricksAccountAuthenticationDatabricksIntegrationAccountOAuthAuthClientSecretWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	authenticationDatabricksIntegrationAccountOAuthAuthClientSecretSecretResult := authenticationDatabricksIntegrationAccountOAuthAuthClientSecretWriteOnlySecretHandler.GetSecretForCreate(ctx, &request.Config)
	response.Diagnostics.Append(authenticationDatabricksIntegrationAccountOAuthAuthClientSecretSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}
	dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationDatabricksAccountDataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretSecretResult := dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretWriteOnlySecretHandler.GetSecretForCreate(ctx, &request.Config)
	response.Diagnostics.Append(dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}

	bodyAttributes := datadogV2.NewDatabricksIntegrationAccountCreateAttributesWithDefaults()

	if state.Authentication != nil {
		var authenticationUnion datadogV2.DatabricksIntegrationAccountAuthenticationRequest
		if state.Authentication.DatabricksIntegrationAccountBearerTokenAuth != nil {
			response.Diagnostics.AddError(
				"Invalid authentication",
				"resource.data.attributes.authentication: \"databricks_integration_account_bearer_token_auth\" cannot be set on create; set exactly one of \"databricks_integration_account_o_auth_auth\" or \"databricks_integration_account_private_action_runner_auth\" instead",
			)
			return
		}
		authenticationMatches := 0
		if state.Authentication.DatabricksIntegrationAccountOAuthAuth != nil {
			databricksIntegrationAccountOAuthAuthVariant := datadogV2.NewDatabricksIntegrationAccountOAuthAuthRequestWithDefaults()

			if !state.Authentication.DatabricksIntegrationAccountOAuthAuth.AuthType.IsNull() && !state.Authentication.DatabricksIntegrationAccountOAuthAuth.AuthType.IsUnknown() {
				databricksIntegrationAccountOAuthAuthVariant.SetAuthType(datadogV2.DatabricksIntegrationAccountOAuthAuthType(state.Authentication.DatabricksIntegrationAccountOAuthAuth.AuthType.ValueString()))
			}

			if !state.Authentication.DatabricksIntegrationAccountOAuthAuth.AzureTenantId.IsNull() && !state.Authentication.DatabricksIntegrationAccountOAuthAuth.AzureTenantId.IsUnknown() {
				databricksIntegrationAccountOAuthAuthVariant.SetAzureTenantId(state.Authentication.DatabricksIntegrationAccountOAuthAuth.AzureTenantId.ValueString())
			}

			databricksIntegrationAccountOAuthAuthVariant.SetClientId(state.Authentication.DatabricksIntegrationAccountOAuthAuth.ClientId.ValueString())

			if authenticationDatabricksIntegrationAccountOAuthAuthClientSecretSecretResult.ShouldSetValue {
				databricksIntegrationAccountOAuthAuthVariant.SetClientSecret(authenticationDatabricksIntegrationAccountOAuthAuthClientSecretSecretResult.Value)
			}
			authenticationUnion = datadogV2.DatabricksIntegrationAccountOAuthAuthRequestAsDatabricksIntegrationAccountAuthenticationRequest(databricksIntegrationAccountOAuthAuthVariant)
			authenticationMatches++
		}
		if state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth != nil {
			databricksIntegrationAccountPrivateActionRunnerAuthVariant := datadogV2.NewDatabricksIntegrationAccountPrivateActionRunnerAuthRequestWithDefaults()

			if !state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.AuthType.IsNull() && !state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.AuthType.IsUnknown() {
				databricksIntegrationAccountPrivateActionRunnerAuthVariant.SetAuthType(datadogV2.DatabricksIntegrationAccountPrivateActionRunnerAuthType(state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.AuthType.ValueString()))
			}

			connectionIdParsed, err := uuid.Parse(state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.ConnectionId.ValueString())
			if err != nil {
				response.Diagnostics.AddError("Invalid connection_id", err.Error())
				return
			}
			databricksIntegrationAccountPrivateActionRunnerAuthVariant.SetConnectionId(connectionIdParsed)

			if !state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.SecretPath.IsNull() && !state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.SecretPath.IsUnknown() {
				databricksIntegrationAccountPrivateActionRunnerAuthVariant.SetSecretPath(state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.SecretPath.ValueString())
			}

			userUuidParsed, err := uuid.Parse(state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.UserUuid.ValueString())
			if err != nil {
				response.Diagnostics.AddError("Invalid user_uuid", err.Error())
				return
			}
			databricksIntegrationAccountPrivateActionRunnerAuthVariant.SetUserUuid(userUuidParsed)
			authenticationUnion = datadogV2.DatabricksIntegrationAccountPrivateActionRunnerAuthRequestAsDatabricksIntegrationAccountAuthenticationRequest(databricksIntegrationAccountPrivateActionRunnerAuthVariant)
			authenticationMatches++
		}
		if authenticationMatches != 1 {
			response.Diagnostics.AddError(
				"Invalid authentication",
				fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"databricks_integration_account_o_auth_auth\" or \"databricks_integration_account_private_action_runner_auth\" must be set, got %d", authenticationMatches),
			)
			return
		}
		bodyAttributes.SetAuthentication(authenticationUnion)
	} else {
		response.Diagnostics.AddError(
			"Invalid authentication",
			fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"databricks_integration_account_o_auth_auth\" or \"databricks_integration_account_private_action_runner_auth\" must be set, got %d", 0),
		)
		return
	}

	if state.Dataflows != nil {
		dataflowsValue := datadogV2.NewDatabricksIntegrationDataflowsRequestWithDefaults()

		if state.Dataflows.DatabricksCloudCostMetrics != nil {
			databricksCloudCostMetricsValue := datadogV2.NewDatabricksCloudCostMetricsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.DatabricksCloudCostMetrics.Enabled.IsNull() && !state.Dataflows.DatabricksCloudCostMetrics.Enabled.IsUnknown() {
				databricksCloudCostMetricsValue.SetEnabled(state.Dataflows.DatabricksCloudCostMetrics.Enabled.ValueBool())
			}

			if state.Dataflows.DatabricksCloudCostMetrics.Settings != nil {
				settingsValue := datadogV2.NewDatabricksCloudCostMetricsIntegrationDataflowSettingsRequestWithDefaults()

				if !state.Dataflows.DatabricksCloudCostMetrics.Settings.CcmCollectAllWorkspaces.IsNull() && !state.Dataflows.DatabricksCloudCostMetrics.Settings.CcmCollectAllWorkspaces.IsUnknown() {
					settingsValue.SetCcmCollectAllWorkspaces(state.Dataflows.DatabricksCloudCostMetrics.Settings.CcmCollectAllWorkspaces.ValueBool())
				}
				databricksCloudCostMetricsValue.SetSettings(*settingsValue)
			}
			dataflowsValue.SetDatabricksCloudCostMetrics(*databricksCloudCostMetricsValue)
		}

		if state.Dataflows.DatabricksDataObservabilityJobsMonitoring != nil {
			databricksDataObservabilityJobsMonitoringValue := datadogV2.NewDatabricksDataObservabilityJobsMonitoringIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Enabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Enabled.IsUnknown() {
				databricksDataObservabilityJobsMonitoringValue.SetEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Enabled.ValueBool())
			}

			if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings != nil {
				settingsValue := datadogV2.NewDatabricksDataObservabilityJobsMonitoringIntegrationDataflowSettingsRequestWithDefaults()

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DdApiKeyId.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DdApiKeyId.IsUnknown() {
					settingsValue.SetDdApiKeyId(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DdApiKeyId.ValueString())
				}

				if dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretSecretResult.ShouldSetValue {
					settingsValue.SetDdApiKeySecret(dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretSecretResult.Value)
				}

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DjmGlobalInitScriptEnabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DjmGlobalInitScriptEnabled.IsUnknown() {
					settingsValue.SetDjmGlobalInitScriptEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DjmGlobalInitScriptEnabled.ValueBool())
				}

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptGpumEnabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptGpumEnabled.IsUnknown() {
					settingsValue.SetScriptGpumEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptGpumEnabled.ValueBool())
				}

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptLogsEnabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptLogsEnabled.IsUnknown() {
					settingsValue.SetScriptLogsEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptLogsEnabled.ValueBool())
				}

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ServerlessJobsEnabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ServerlessJobsEnabled.IsUnknown() {
					settingsValue.SetServerlessJobsEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ServerlessJobsEnabled.ValueBool())
				}
				databricksDataObservabilityJobsMonitoringValue.SetSettings(*settingsValue)
			}
			dataflowsValue.SetDatabricksDataObservabilityJobsMonitoring(*databricksDataObservabilityJobsMonitoringValue)
		}

		if state.Dataflows.DatabricksDataObservabilityQualityMonitoring != nil {
			databricksDataObservabilityQualityMonitoringValue := datadogV2.NewDatabricksDataObservabilityQualityMonitoringIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Enabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Enabled.IsUnknown() {
				databricksDataObservabilityQualityMonitoringValue.SetEnabled(state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Enabled.ValueBool())
			}

			if state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings != nil {
				settingsValue := datadogV2.NewDatabricksDataObservabilityQualityMonitoringIntegrationDataflowSettingsRequestWithDefaults()

				if !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.DoCrawlersCron.IsNull() && !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.DoCrawlersCron.IsUnknown() {
					settingsValue.SetDoCrawlersCron(state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.DoCrawlersCron.ValueString())
				}

				if !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.SyncSystemCatalog.IsNull() && !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.SyncSystemCatalog.IsUnknown() {
					settingsValue.SetSyncSystemCatalog(state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.SyncSystemCatalog.ValueBool())
				}
				databricksDataObservabilityQualityMonitoringValue.SetSettings(*settingsValue)
			}
			dataflowsValue.SetDatabricksDataObservabilityQualityMonitoring(*databricksDataObservabilityQualityMonitoringValue)
		}

		if state.Dataflows.DatabricksModelServingMetrics != nil {
			databricksModelServingMetricsValue := datadogV2.NewDatabricksModelServingMetricsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.DatabricksModelServingMetrics.Enabled.IsNull() && !state.Dataflows.DatabricksModelServingMetrics.Enabled.IsUnknown() {
				databricksModelServingMetricsValue.SetEnabled(state.Dataflows.DatabricksModelServingMetrics.Enabled.ValueBool())
			}
			dataflowsValue.SetDatabricksModelServingMetrics(*databricksModelServingMetricsValue)
		}
		bodyAttributes.SetDataflows(*dataflowsValue)
	}

	bodyAttributes.SetName(state.Name.ValueString())

	settingsValue := datadogV2.NewDatabricksIntegrationAccountSettingsRequestWithDefaults()

	if !state.Settings.SystemTablesSqlWarehouseId.IsNull() && !state.Settings.SystemTablesSqlWarehouseId.IsUnknown() {
		settingsValue.SetSystemTablesSqlWarehouseId(state.Settings.SystemTablesSqlWarehouseId.ValueString())
	}

	settingsValue.SetWorkspaceUrl(state.Settings.WorkspaceUrl.ValueString())
	bodyAttributes.SetSettings(*settingsValue)
	bodyData := datadogV2.NewDatabricksIntegrationAccountCreateDataWithDefaults()
	bodyData.SetType(datadogV2.IntegrationAccountType("integration-account"))
	bodyData.SetAttributes(*bodyAttributes)
	body := datadogV2.NewDatabricksIntegrationAccountCreateRequestWithDefaults()
	body.SetData(*bodyData)
	resp, _, err := r.Api.CreateDatabricksIntegrationAccount(r.Auth, *body)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error creating integration_databricks_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	if state.Authentication != nil {
		if state.Authentication.DatabricksIntegrationAccountBearerTokenAuth != nil {
			if state.Authentication.DatabricksIntegrationAccountBearerTokenAuth.AuthType.IsUnknown() {
				state.Authentication.DatabricksIntegrationAccountBearerTokenAuth.AuthType = types.StringNull()
			}
		}
		if state.Authentication.DatabricksIntegrationAccountOAuthAuth != nil {
			if state.Authentication.DatabricksIntegrationAccountOAuthAuth.AuthType.IsUnknown() {
				state.Authentication.DatabricksIntegrationAccountOAuthAuth.AuthType = types.StringNull()
			}
			if state.Authentication.DatabricksIntegrationAccountOAuthAuth.AzureTenantId.IsUnknown() {
				state.Authentication.DatabricksIntegrationAccountOAuthAuth.AzureTenantId = types.StringNull()
			}
		}
		if state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth != nil {
			if state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.AuthType.IsUnknown() {
				state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.AuthType = types.StringNull()
			}
			if state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.SecretPath.IsUnknown() {
				state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.SecretPath = types.StringNull()
			}
		}
	}
	if state.Dataflows != nil {
		if state.Dataflows.DatabricksCloudCostMetrics != nil {
			if state.Dataflows.DatabricksCloudCostMetrics.Enabled.IsUnknown() {
				state.Dataflows.DatabricksCloudCostMetrics.Enabled = types.BoolNull()
			}
			if state.Dataflows.DatabricksCloudCostMetrics.Settings != nil {
				if state.Dataflows.DatabricksCloudCostMetrics.Settings.CcmCollectAllWorkspaces.IsUnknown() {
					state.Dataflows.DatabricksCloudCostMetrics.Settings.CcmCollectAllWorkspaces = types.BoolNull()
				}
			}
		}
		if state.Dataflows.DatabricksDataObservabilityJobsMonitoring != nil {
			if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Enabled.IsUnknown() {
				state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Enabled = types.BoolNull()
			}
			if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings != nil {
				if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DdApiKeyId.IsUnknown() {
					state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DdApiKeyId = types.StringNull()
				}
				if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DjmGlobalInitScriptEnabled.IsUnknown() {
					state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DjmGlobalInitScriptEnabled = types.BoolNull()
				}
				if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptGpumEnabled.IsUnknown() {
					state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptGpumEnabled = types.BoolNull()
				}
				if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptLogsEnabled.IsUnknown() {
					state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptLogsEnabled = types.BoolNull()
				}
				if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ServerlessJobsEnabled.IsUnknown() {
					state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ServerlessJobsEnabled = types.BoolNull()
				}
			}
		}
		if state.Dataflows.DatabricksDataObservabilityQualityMonitoring != nil {
			if state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Enabled.IsUnknown() {
				state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Enabled = types.BoolNull()
			}
			if state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings != nil {
				if state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.DoCrawlersCron.IsUnknown() {
					state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.DoCrawlersCron = types.StringNull()
				}
				if state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.SyncSystemCatalog.IsUnknown() {
					state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.SyncSystemCatalog = types.BoolNull()
				}
			}
		}
		if state.Dataflows.DatabricksModelServingMetrics != nil {
			if state.Dataflows.DatabricksModelServingMetrics.Enabled.IsUnknown() {
				state.Dataflows.DatabricksModelServingMetrics.Enabled = types.BoolNull()
			}
		}
	}
	if state.Settings != nil {
		if state.Settings.SystemTablesSqlWarehouseId.IsUnknown() {
			state.Settings.SystemTablesSqlWarehouseId = types.StringNull()
		}
	}
	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationDatabricksAccountResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var state datadogIntegrationDatabricksAccountResourceModel
	response.Diagnostics.Append(request.State.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	resp, httpResp, err := r.Api.GetDatabricksIntegrationAccount(r.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			response.State.RemoveResource(ctx)
			return
		}
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error reading integration_databricks_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationDatabricksAccountResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var state datadogIntegrationDatabricksAccountResourceModel
	var plan types.Object
	response.Diagnostics.Append(request.Plan.Get(ctx, &plan)...)
	if response.Diagnostics.HasError() {
		return
	}
	response.Diagnostics.Append(plan.As(ctx, &state, basetypes.ObjectAsOptions{UnhandledUnknownAsEmpty: true})...)
	if response.Diagnostics.HasError() {
		return
	}

	authenticationDatabricksIntegrationAccountBearerTokenAuthTokenWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationDatabricksAccountAuthenticationDatabricksIntegrationAccountBearerTokenAuthTokenWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	authenticationDatabricksIntegrationAccountBearerTokenAuthTokenSecretResult := authenticationDatabricksIntegrationAccountBearerTokenAuthTokenWriteOnlySecretHandler.GetSecretForUpdate(ctx, &request.Config, &request)
	response.Diagnostics.Append(authenticationDatabricksIntegrationAccountBearerTokenAuthTokenSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}
	authenticationDatabricksIntegrationAccountOAuthAuthClientSecretWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationDatabricksAccountAuthenticationDatabricksIntegrationAccountOAuthAuthClientSecretWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	authenticationDatabricksIntegrationAccountOAuthAuthClientSecretSecretResult := authenticationDatabricksIntegrationAccountOAuthAuthClientSecretWriteOnlySecretHandler.GetSecretForUpdate(ctx, &request.Config, &request)
	response.Diagnostics.Append(authenticationDatabricksIntegrationAccountOAuthAuthClientSecretSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}
	dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretWriteOnlySecretHandler := fwutils.WriteOnlySecretHandler{
		Config:                 datadogIntegrationDatabricksAccountDataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretWriteOnlySecretConfig,
		SecretRequiredOnUpdate: false,
	}
	dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretSecretResult := dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretWriteOnlySecretHandler.GetSecretForUpdate(ctx, &request.Config, &request)
	response.Diagnostics.Append(dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretSecretResult.Diagnostics...)
	if response.Diagnostics.HasError() {
		return
	}

	bodyAttributes := datadogV2.NewDatabricksIntegrationAccountUpdateAttributesWithDefaults()

	if state.Authentication != nil {
		var authenticationUnion datadogV2.DatabricksIntegrationAccountAuthenticationUpdate
		authenticationMatches := 0
		if state.Authentication.DatabricksIntegrationAccountBearerTokenAuth != nil {
			databricksIntegrationAccountBearerTokenAuthVariant := datadogV2.NewDatabricksIntegrationAccountBearerTokenAuthUpdateWithDefaults()

			if !state.Authentication.DatabricksIntegrationAccountBearerTokenAuth.AuthType.IsNull() && !state.Authentication.DatabricksIntegrationAccountBearerTokenAuth.AuthType.IsUnknown() {
				databricksIntegrationAccountBearerTokenAuthVariant.SetAuthType(datadogV2.DatabricksIntegrationAccountBearerTokenAuthType(state.Authentication.DatabricksIntegrationAccountBearerTokenAuth.AuthType.ValueString()))
			}

			if authenticationDatabricksIntegrationAccountBearerTokenAuthTokenSecretResult.ShouldSetValue {
				databricksIntegrationAccountBearerTokenAuthVariant.SetToken(authenticationDatabricksIntegrationAccountBearerTokenAuthTokenSecretResult.Value)
			}
			authenticationUnion = datadogV2.DatabricksIntegrationAccountBearerTokenAuthUpdateAsDatabricksIntegrationAccountAuthenticationUpdate(databricksIntegrationAccountBearerTokenAuthVariant)
			authenticationMatches++
		}
		if state.Authentication.DatabricksIntegrationAccountOAuthAuth != nil {
			databricksIntegrationAccountOAuthAuthVariant := datadogV2.NewDatabricksIntegrationAccountOAuthAuthUpdateWithDefaults()

			if !state.Authentication.DatabricksIntegrationAccountOAuthAuth.AuthType.IsNull() && !state.Authentication.DatabricksIntegrationAccountOAuthAuth.AuthType.IsUnknown() {
				databricksIntegrationAccountOAuthAuthVariant.SetAuthType(datadogV2.DatabricksIntegrationAccountOAuthAuthType(state.Authentication.DatabricksIntegrationAccountOAuthAuth.AuthType.ValueString()))
			}

			if !state.Authentication.DatabricksIntegrationAccountOAuthAuth.AzureTenantId.IsNull() && !state.Authentication.DatabricksIntegrationAccountOAuthAuth.AzureTenantId.IsUnknown() {
				databricksIntegrationAccountOAuthAuthVariant.SetAzureTenantId(state.Authentication.DatabricksIntegrationAccountOAuthAuth.AzureTenantId.ValueString())
			}

			databricksIntegrationAccountOAuthAuthVariant.SetClientId(state.Authentication.DatabricksIntegrationAccountOAuthAuth.ClientId.ValueString())

			if authenticationDatabricksIntegrationAccountOAuthAuthClientSecretSecretResult.ShouldSetValue {
				databricksIntegrationAccountOAuthAuthVariant.SetClientSecret(authenticationDatabricksIntegrationAccountOAuthAuthClientSecretSecretResult.Value)
			}
			authenticationUnion = datadogV2.DatabricksIntegrationAccountOAuthAuthUpdateAsDatabricksIntegrationAccountAuthenticationUpdate(databricksIntegrationAccountOAuthAuthVariant)
			authenticationMatches++
		}
		if state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth != nil {
			databricksIntegrationAccountPrivateActionRunnerAuthVariant := datadogV2.NewDatabricksIntegrationAccountPrivateActionRunnerAuthUpdateWithDefaults()

			if !state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.AuthType.IsNull() && !state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.AuthType.IsUnknown() {
				databricksIntegrationAccountPrivateActionRunnerAuthVariant.SetAuthType(datadogV2.DatabricksIntegrationAccountPrivateActionRunnerAuthType(state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.AuthType.ValueString()))
			}

			connectionIdParsed, err := uuid.Parse(state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.ConnectionId.ValueString())
			if err != nil {
				response.Diagnostics.AddError("Invalid connection_id", err.Error())
				return
			}
			databricksIntegrationAccountPrivateActionRunnerAuthVariant.SetConnectionId(connectionIdParsed)

			if !state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.SecretPath.IsNull() && !state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.SecretPath.IsUnknown() {
				databricksIntegrationAccountPrivateActionRunnerAuthVariant.SetSecretPath(state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.SecretPath.ValueString())
			}

			userUuidParsed, err := uuid.Parse(state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth.UserUuid.ValueString())
			if err != nil {
				response.Diagnostics.AddError("Invalid user_uuid", err.Error())
				return
			}
			databricksIntegrationAccountPrivateActionRunnerAuthVariant.SetUserUuid(userUuidParsed)
			authenticationUnion = datadogV2.DatabricksIntegrationAccountPrivateActionRunnerAuthUpdateAsDatabricksIntegrationAccountAuthenticationUpdate(databricksIntegrationAccountPrivateActionRunnerAuthVariant)
			authenticationMatches++
		}
		if authenticationMatches != 1 {
			response.Diagnostics.AddError(
				"Invalid authentication",
				fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"databricks_integration_account_bearer_token_auth\" or \"databricks_integration_account_o_auth_auth\" or \"databricks_integration_account_private_action_runner_auth\" must be set, got %d", authenticationMatches),
			)
			return
		}
		bodyAttributes.SetAuthentication(authenticationUnion)
	} else {
		response.Diagnostics.AddError(
			"Invalid authentication",
			fmt.Sprintf("resource.data.attributes.authentication: exactly one of \"databricks_integration_account_bearer_token_auth\" or \"databricks_integration_account_o_auth_auth\" or \"databricks_integration_account_private_action_runner_auth\" must be set, got %d", 0),
		)
		return
	}

	if state.Dataflows != nil {
		dataflowsValue := datadogV2.NewDatabricksIntegrationDataflowsRequestWithDefaults()

		if state.Dataflows.DatabricksCloudCostMetrics != nil {
			databricksCloudCostMetricsValue := datadogV2.NewDatabricksCloudCostMetricsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.DatabricksCloudCostMetrics.Enabled.IsNull() && !state.Dataflows.DatabricksCloudCostMetrics.Enabled.IsUnknown() {
				databricksCloudCostMetricsValue.SetEnabled(state.Dataflows.DatabricksCloudCostMetrics.Enabled.ValueBool())
			}

			if state.Dataflows.DatabricksCloudCostMetrics.Settings != nil {
				settingsValue := datadogV2.NewDatabricksCloudCostMetricsIntegrationDataflowSettingsRequestWithDefaults()

				if !state.Dataflows.DatabricksCloudCostMetrics.Settings.CcmCollectAllWorkspaces.IsNull() && !state.Dataflows.DatabricksCloudCostMetrics.Settings.CcmCollectAllWorkspaces.IsUnknown() {
					settingsValue.SetCcmCollectAllWorkspaces(state.Dataflows.DatabricksCloudCostMetrics.Settings.CcmCollectAllWorkspaces.ValueBool())
				}
				databricksCloudCostMetricsValue.SetSettings(*settingsValue)
			}
			dataflowsValue.SetDatabricksCloudCostMetrics(*databricksCloudCostMetricsValue)
		}

		if state.Dataflows.DatabricksDataObservabilityJobsMonitoring != nil {
			databricksDataObservabilityJobsMonitoringValue := datadogV2.NewDatabricksDataObservabilityJobsMonitoringIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Enabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Enabled.IsUnknown() {
				databricksDataObservabilityJobsMonitoringValue.SetEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Enabled.ValueBool())
			}

			if state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings != nil {
				settingsValue := datadogV2.NewDatabricksDataObservabilityJobsMonitoringIntegrationDataflowSettingsRequestWithDefaults()

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DdApiKeyId.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DdApiKeyId.IsUnknown() {
					settingsValue.SetDdApiKeyId(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DdApiKeyId.ValueString())
				}

				if dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretSecretResult.ShouldSetValue {
					settingsValue.SetDdApiKeySecret(dataflowsDatabricksDataObservabilityJobsMonitoringSettingsDdApiKeySecretSecretResult.Value)
				}

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DjmGlobalInitScriptEnabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DjmGlobalInitScriptEnabled.IsUnknown() {
					settingsValue.SetDjmGlobalInitScriptEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.DjmGlobalInitScriptEnabled.ValueBool())
				}

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptGpumEnabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptGpumEnabled.IsUnknown() {
					settingsValue.SetScriptGpumEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptGpumEnabled.ValueBool())
				}

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptLogsEnabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptLogsEnabled.IsUnknown() {
					settingsValue.SetScriptLogsEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ScriptLogsEnabled.ValueBool())
				}

				if !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ServerlessJobsEnabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ServerlessJobsEnabled.IsUnknown() {
					settingsValue.SetServerlessJobsEnabled(state.Dataflows.DatabricksDataObservabilityJobsMonitoring.Settings.ServerlessJobsEnabled.ValueBool())
				}
				databricksDataObservabilityJobsMonitoringValue.SetSettings(*settingsValue)
			}
			dataflowsValue.SetDatabricksDataObservabilityJobsMonitoring(*databricksDataObservabilityJobsMonitoringValue)
		}

		if state.Dataflows.DatabricksDataObservabilityQualityMonitoring != nil {
			databricksDataObservabilityQualityMonitoringValue := datadogV2.NewDatabricksDataObservabilityQualityMonitoringIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Enabled.IsNull() && !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Enabled.IsUnknown() {
				databricksDataObservabilityQualityMonitoringValue.SetEnabled(state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Enabled.ValueBool())
			}

			if state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings != nil {
				settingsValue := datadogV2.NewDatabricksDataObservabilityQualityMonitoringIntegrationDataflowSettingsRequestWithDefaults()

				if !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.DoCrawlersCron.IsNull() && !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.DoCrawlersCron.IsUnknown() {
					settingsValue.SetDoCrawlersCron(state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.DoCrawlersCron.ValueString())
				}

				if !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.SyncSystemCatalog.IsNull() && !state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.SyncSystemCatalog.IsUnknown() {
					settingsValue.SetSyncSystemCatalog(state.Dataflows.DatabricksDataObservabilityQualityMonitoring.Settings.SyncSystemCatalog.ValueBool())
				}
				databricksDataObservabilityQualityMonitoringValue.SetSettings(*settingsValue)
			}
			dataflowsValue.SetDatabricksDataObservabilityQualityMonitoring(*databricksDataObservabilityQualityMonitoringValue)
		}

		if state.Dataflows.DatabricksModelServingMetrics != nil {
			databricksModelServingMetricsValue := datadogV2.NewDatabricksModelServingMetricsIntegrationDataflowRequestWithDefaults()

			if !state.Dataflows.DatabricksModelServingMetrics.Enabled.IsNull() && !state.Dataflows.DatabricksModelServingMetrics.Enabled.IsUnknown() {
				databricksModelServingMetricsValue.SetEnabled(state.Dataflows.DatabricksModelServingMetrics.Enabled.ValueBool())
			}
			dataflowsValue.SetDatabricksModelServingMetrics(*databricksModelServingMetricsValue)
		}
		bodyAttributes.SetDataflows(*dataflowsValue)
	}

	bodyAttributes.SetName(state.Name.ValueString())

	settingsValue := datadogV2.NewDatabricksIntegrationAccountSettingsUpdateWithDefaults()

	if !state.Settings.SystemTablesSqlWarehouseId.IsNull() && !state.Settings.SystemTablesSqlWarehouseId.IsUnknown() {
		settingsValue.SetSystemTablesSqlWarehouseId(state.Settings.SystemTablesSqlWarehouseId.ValueString())
	}

	settingsValue.SetWorkspaceUrl(state.Settings.WorkspaceUrl.ValueString())
	bodyAttributes.SetSettings(*settingsValue)
	bodyData := datadogV2.NewDatabricksIntegrationAccountUpdateDataWithDefaults()
	bodyData.SetType(datadogV2.IntegrationAccountType("integration-account"))
	bodyData.SetId(state.ID.ValueString())
	bodyData.SetAttributes(*bodyAttributes)
	body := datadogV2.NewDatabricksIntegrationAccountUpdateRequestWithDefaults()
	body.SetData(*bodyData)
	resp, _, err := r.Api.UpdateDatabricksIntegrationAccount(r.Auth, state.ID.ValueString(), *body)
	if err != nil {
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error updating integration_databricks_account"))
		return
	}
	response.Diagnostics.Append(r.updateState(ctx, &state, &resp)...)
	if response.Diagnostics.HasError() {
		return
	}

	response.Diagnostics.Append(response.State.Set(ctx, &state)...)
}

func (r *datadogIntegrationDatabricksAccountResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var state datadogIntegrationDatabricksAccountResourceModel
	response.Diagnostics.Append(request.State.Get(ctx, &state)...)
	if response.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.Api.DeleteDatabricksIntegrationAccount(r.Auth, state.ID.ValueString())
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			return
		}
		response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error deleting integration_databricks_account"))
	}
}

// updateState maps *datadogV2.DatabricksIntegrationAccountResponse into state, returning diagnostics
// rather than writing them so it stays free of the resource request/response
// types and can fail at a specific schema path. Shared by Create, Read and
// Update, which all resolve the same response type.
func (r *datadogIntegrationDatabricksAccountResource) updateState(ctx context.Context, state *datadogIntegrationDatabricksAccountResourceModel, resp *datadogV2.DatabricksIntegrationAccountResponse) diag.Diagnostics {
	var diags diag.Diagnostics
	attributes := resp.Data.GetAttributes()
	if id, ok := resp.Data.GetIdOk(); ok && id != nil {
		state.ID = types.StringValue(*id)
	}
	if name, ok := attributes.GetNameOk(); ok && name != nil {
		state.Name = types.StringValue(*name)
	}
	if authentication, ok := attributes.GetAuthenticationOk(); ok && authentication != nil {
		authenticationEnvelope := &datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationModel{}
		authenticationMatches := 0
		if databricksIntegrationAccountBearerTokenAuthVariant := authentication.DatabricksIntegrationAccountBearerTokenAuthResponse; databricksIntegrationAccountBearerTokenAuthVariant != nil {
			databricksIntegrationAccountBearerTokenAuthModel := &datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountBearerTokenAuthModel{}
			if state.Authentication != nil && state.Authentication.DatabricksIntegrationAccountBearerTokenAuth != nil {
				databricksIntegrationAccountBearerTokenAuthModel = state.Authentication.DatabricksIntegrationAccountBearerTokenAuth
			}
			if authType, ok := databricksIntegrationAccountBearerTokenAuthVariant.GetAuthTypeOk(); ok && authType != nil {
				databricksIntegrationAccountBearerTokenAuthModel.AuthType = types.StringValue(string(*authType))
			}
			authenticationEnvelope.DatabricksIntegrationAccountBearerTokenAuth = databricksIntegrationAccountBearerTokenAuthModel
			authenticationMatches++
		}
		if databricksIntegrationAccountOAuthAuthVariant := authentication.DatabricksIntegrationAccountOAuthAuthResponse; databricksIntegrationAccountOAuthAuthVariant != nil {
			databricksIntegrationAccountOAuthAuthModel := &datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountOAuthAuthModel{}
			if state.Authentication != nil && state.Authentication.DatabricksIntegrationAccountOAuthAuth != nil {
				databricksIntegrationAccountOAuthAuthModel = state.Authentication.DatabricksIntegrationAccountOAuthAuth
			}
			if authType, ok := databricksIntegrationAccountOAuthAuthVariant.GetAuthTypeOk(); ok && authType != nil {
				databricksIntegrationAccountOAuthAuthModel.AuthType = types.StringValue(string(*authType))
			}
			if azureTenantId, ok := databricksIntegrationAccountOAuthAuthVariant.GetAzureTenantIdOk(); ok && azureTenantId != nil {
				databricksIntegrationAccountOAuthAuthModel.AzureTenantId = types.StringValue(*azureTenantId)
			}
			if clientId, ok := databricksIntegrationAccountOAuthAuthVariant.GetClientIdOk(); ok && clientId != nil {
				databricksIntegrationAccountOAuthAuthModel.ClientId = types.StringValue(*clientId)
			}
			authenticationEnvelope.DatabricksIntegrationAccountOAuthAuth = databricksIntegrationAccountOAuthAuthModel
			authenticationMatches++
		}
		if databricksIntegrationAccountPrivateActionRunnerAuthVariant := authentication.DatabricksIntegrationAccountPrivateActionRunnerAuthResponse; databricksIntegrationAccountPrivateActionRunnerAuthVariant != nil {
			databricksIntegrationAccountPrivateActionRunnerAuthModel := &datadogIntegrationDatabricksAccountDatabricksIntegrationAccountAuthenticationDatabricksIntegrationAccountPrivateActionRunnerAuthModel{}
			if state.Authentication != nil && state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth != nil {
				databricksIntegrationAccountPrivateActionRunnerAuthModel = state.Authentication.DatabricksIntegrationAccountPrivateActionRunnerAuth
			}
			if authType, ok := databricksIntegrationAccountPrivateActionRunnerAuthVariant.GetAuthTypeOk(); ok && authType != nil {
				databricksIntegrationAccountPrivateActionRunnerAuthModel.AuthType = types.StringValue(string(*authType))
			}
			if connectionId, ok := databricksIntegrationAccountPrivateActionRunnerAuthVariant.GetConnectionIdOk(); ok && connectionId != nil {
				databricksIntegrationAccountPrivateActionRunnerAuthModel.ConnectionId = types.StringValue(connectionId.String())
			}
			if secretPath, ok := databricksIntegrationAccountPrivateActionRunnerAuthVariant.GetSecretPathOk(); ok && secretPath != nil {
				databricksIntegrationAccountPrivateActionRunnerAuthModel.SecretPath = types.StringValue(*secretPath)
			}
			if userUuid, ok := databricksIntegrationAccountPrivateActionRunnerAuthVariant.GetUserUuidOk(); ok && userUuid != nil {
				databricksIntegrationAccountPrivateActionRunnerAuthModel.UserUuid = types.StringValue(userUuid.String())
			}
			authenticationEnvelope.DatabricksIntegrationAccountPrivateActionRunnerAuth = databricksIntegrationAccountPrivateActionRunnerAuthModel
			authenticationMatches++
		}
		switch {
		case authentication.UnparsedObject != nil:
			diags.AddError(
				"unexpected DatabricksIntegrationAccountAuthenticationResponse in the API response",
				"resource.data.attributes.authentication: the Datadog API returned a value none of the DatabricksIntegrationAccountAuthenticationResponse alternatives could parse",
			)
		case authenticationMatches > 1:
			diags.AddError(
				"ambiguous DatabricksIntegrationAccountAuthenticationResponse in the API response",
				fmt.Sprintf("resource.data.attributes.authentication: the Datadog API response matched %d DatabricksIntegrationAccountAuthenticationResponse alternatives, expected exactly one", authenticationMatches),
			)
		case authenticationMatches == 1:
			state.Authentication = authenticationEnvelope
		}
	}
	if dataflows, ok := attributes.GetDataflowsOk(); ok && dataflows != nil && state.Dataflows != nil {
		dataflowsModel := state.Dataflows
		if dataflowsModel == nil {
			dataflowsModel = &datadogIntegrationDatabricksAccountDatabricksIntegrationDataflowsResponseModel{}
		}
		if databricksCloudCostMetrics, ok := dataflows.GetDatabricksCloudCostMetricsOk(); ok && databricksCloudCostMetrics != nil {
			databricksCloudCostMetricsModel := dataflowsModel.DatabricksCloudCostMetrics
			if databricksCloudCostMetricsModel == nil {
				databricksCloudCostMetricsModel = &datadogIntegrationDatabricksAccountDatabricksCloudCostMetricsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := databricksCloudCostMetrics.GetEnabledOk(); ok && enabled != nil {
				databricksCloudCostMetricsModel.Enabled = types.BoolValue(*enabled)
			}
			if settings, ok := databricksCloudCostMetrics.GetSettingsOk(); ok && settings != nil {
				settingsModel := databricksCloudCostMetricsModel.Settings
				if settingsModel == nil {
					settingsModel = &datadogIntegrationDatabricksAccountDatabricksCloudCostMetricsIntegrationDataflowSettingsResponseModel{}
				}
				if ccmCollectAllWorkspaces, ok := settings.GetCcmCollectAllWorkspacesOk(); ok && ccmCollectAllWorkspaces != nil {
					settingsModel.CcmCollectAllWorkspaces = types.BoolValue(*ccmCollectAllWorkspaces)
				}
				databricksCloudCostMetricsModel.Settings = settingsModel
			}
			dataflowsModel.DatabricksCloudCostMetrics = databricksCloudCostMetricsModel
		}
		if databricksDataObservabilityJobsMonitoring, ok := dataflows.GetDatabricksDataObservabilityJobsMonitoringOk(); ok && databricksDataObservabilityJobsMonitoring != nil && dataflowsModel.DatabricksDataObservabilityJobsMonitoring != nil {
			databricksDataObservabilityJobsMonitoringModel := dataflowsModel.DatabricksDataObservabilityJobsMonitoring
			if databricksDataObservabilityJobsMonitoringModel == nil {
				databricksDataObservabilityJobsMonitoringModel = &datadogIntegrationDatabricksAccountDatabricksDataObservabilityJobsMonitoringIntegrationDataflowResponseModel{}
			}
			if enabled, ok := databricksDataObservabilityJobsMonitoring.GetEnabledOk(); ok && enabled != nil {
				databricksDataObservabilityJobsMonitoringModel.Enabled = types.BoolValue(*enabled)
			}
			if settings, ok := databricksDataObservabilityJobsMonitoring.GetSettingsOk(); ok && settings != nil && databricksDataObservabilityJobsMonitoringModel.Settings != nil {
				settingsModel := databricksDataObservabilityJobsMonitoringModel.Settings
				if settingsModel == nil {
					settingsModel = &datadogIntegrationDatabricksAccountDatabricksDataObservabilityJobsMonitoringIntegrationDataflowSettingsResponseModel{}
				}
				if ddApiKeyId, ok := settings.GetDdApiKeyIdOk(); ok && ddApiKeyId != nil {
					settingsModel.DdApiKeyId = types.StringValue(*ddApiKeyId)
				}
				if djmGlobalInitScriptEnabled, ok := settings.GetDjmGlobalInitScriptEnabledOk(); ok && djmGlobalInitScriptEnabled != nil {
					settingsModel.DjmGlobalInitScriptEnabled = types.BoolValue(*djmGlobalInitScriptEnabled)
				}
				if scriptGpumEnabled, ok := settings.GetScriptGpumEnabledOk(); ok && scriptGpumEnabled != nil {
					settingsModel.ScriptGpumEnabled = types.BoolValue(*scriptGpumEnabled)
				}
				if scriptLogsEnabled, ok := settings.GetScriptLogsEnabledOk(); ok && scriptLogsEnabled != nil {
					settingsModel.ScriptLogsEnabled = types.BoolValue(*scriptLogsEnabled)
				}
				if serverlessJobsEnabled, ok := settings.GetServerlessJobsEnabledOk(); ok && serverlessJobsEnabled != nil {
					settingsModel.ServerlessJobsEnabled = types.BoolValue(*serverlessJobsEnabled)
				}
				databricksDataObservabilityJobsMonitoringModel.Settings = settingsModel
			}
			dataflowsModel.DatabricksDataObservabilityJobsMonitoring = databricksDataObservabilityJobsMonitoringModel
		}
		if databricksDataObservabilityQualityMonitoring, ok := dataflows.GetDatabricksDataObservabilityQualityMonitoringOk(); ok && databricksDataObservabilityQualityMonitoring != nil {
			databricksDataObservabilityQualityMonitoringModel := dataflowsModel.DatabricksDataObservabilityQualityMonitoring
			if databricksDataObservabilityQualityMonitoringModel == nil {
				databricksDataObservabilityQualityMonitoringModel = &datadogIntegrationDatabricksAccountDatabricksDataObservabilityQualityMonitoringIntegrationDataflowResponseModel{}
			}
			if enabled, ok := databricksDataObservabilityQualityMonitoring.GetEnabledOk(); ok && enabled != nil {
				databricksDataObservabilityQualityMonitoringModel.Enabled = types.BoolValue(*enabled)
			}
			if settings, ok := databricksDataObservabilityQualityMonitoring.GetSettingsOk(); ok && settings != nil {
				settingsModel := databricksDataObservabilityQualityMonitoringModel.Settings
				if settingsModel == nil {
					settingsModel = &datadogIntegrationDatabricksAccountDatabricksDataObservabilityQualityMonitoringIntegrationDataflowSettingsResponseModel{}
				}
				if doCrawlersCron, ok := settings.GetDoCrawlersCronOk(); ok && doCrawlersCron != nil {
					settingsModel.DoCrawlersCron = types.StringValue(*doCrawlersCron)
				}
				if syncSystemCatalog, ok := settings.GetSyncSystemCatalogOk(); ok && syncSystemCatalog != nil {
					settingsModel.SyncSystemCatalog = types.BoolValue(*syncSystemCatalog)
				}
				databricksDataObservabilityQualityMonitoringModel.Settings = settingsModel
			}
			dataflowsModel.DatabricksDataObservabilityQualityMonitoring = databricksDataObservabilityQualityMonitoringModel
		}
		if databricksModelServingMetrics, ok := dataflows.GetDatabricksModelServingMetricsOk(); ok && databricksModelServingMetrics != nil {
			databricksModelServingMetricsModel := dataflowsModel.DatabricksModelServingMetrics
			if databricksModelServingMetricsModel == nil {
				databricksModelServingMetricsModel = &datadogIntegrationDatabricksAccountDatabricksModelServingMetricsIntegrationDataflowResponseModel{}
			}
			if enabled, ok := databricksModelServingMetrics.GetEnabledOk(); ok && enabled != nil {
				databricksModelServingMetricsModel.Enabled = types.BoolValue(*enabled)
			}
			dataflowsModel.DatabricksModelServingMetrics = databricksModelServingMetricsModel
		}
		state.Dataflows = dataflowsModel
	}
	if settings, ok := attributes.GetSettingsOk(); ok && settings != nil {
		settingsModel := state.Settings
		if settingsModel == nil {
			settingsModel = &datadogIntegrationDatabricksAccountDatabricksIntegrationAccountSettingsResponseModel{}
		}
		if systemTablesSqlWarehouseId, ok := settings.GetSystemTablesSqlWarehouseIdOk(); ok && systemTablesSqlWarehouseId != nil {
			settingsModel.SystemTablesSqlWarehouseId = types.StringValue(*systemTablesSqlWarehouseId)
		}
		if workspaceUrl, ok := settings.GetWorkspaceUrlOk(); ok && workspaceUrl != nil {
			settingsModel.WorkspaceUrl = types.StringValue(*workspaceUrl)
		}
		state.Settings = settingsModel
	}
	return diags
}
