# Copied from https://github.com/hashicorp/terraform-provider-scaffolding/blob/master/.github/workflows/release.yml
name: release

permissions:
  contents: write
  pull-requests: write
  id-token: write # Required for dd-octo-sts action

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - v3

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-16-core-latest
    environment: release
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    steps:
      - name: Get GitHub App token
        id: get_token
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        with:
          scope: DataDog/terraform-provider-datadog
          policy: self.release.create-release
          pool_name: dd-api-reliability
      - name: Create tag
        id: create_tag
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          RELEASE_BRANCH: ${{ github.head_ref }}
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          script: |
            const tagName = `v${process.env.RELEASE_BRANCH.split("/")[1]}`;
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagName}`,
              sha: context.payload.pull_request.merge_commit_sha,
            });
            core.setOutput("tag_name", tagName);
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ steps.create_tag.outputs.tag_name }}
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # Shared runner has public egress, so Go is resolved and downloaded
          # from go.dev. Track the minor line; must satisfy go.mod's `go`
          # directive (currently 1.25.8).
          go-version: "1.25"
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
