// Generated by tfgen as an acceptance-test scaffold. Complete the TODOs and
// record a cassette (see below); tfgen will not overwrite this file once it exists.
package test

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// TestAccDatadogAuthnMappingsDatasource is a generated scaffold. It needs a recorded cassette to pass
// in replay mode:
//  1. Complete testAccDatasourceDatadogAuthnMappingsConfig below: add the resource(s) that seed the data
//     this data source reads, and set the lookup/filter value(s).
//  2. Record the cassette: RECORD=true make testacc TESTARGS='-run TestAccDatadogAuthnMappingsDatasource'
//  3. Review datadog/tests/cassettes/TestAccDatadogAuthnMappingsDatasource.yaml (and its .freeze), then commit them so the test
//     runs in replay mode.
func TestAccDatadogAuthnMappingsDatasource(t *testing.T) {
	t.Parallel()
	ctx, _, accProviders := testAccFrameworkMuxProviders(context.Background(), t)
	uniq := strings.ToLower(uniqueEntityName(ctx, t))

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: accProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDatasourceDatadogAuthnMappingsConfig(uniq),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.datadog_authn_mappings.foo", "id"),
					resource.TestCheckResourceAttrSet("data.datadog_authn_mappings.foo", "authn_mappings.#"),
					// TODO(tfgen): assert specific attributes once the cassette is recorded.
				),
			},
		},
	})
}

func testAccDatasourceDatadogAuthnMappingsConfig(uniq string) string {
	return fmt.Sprintf(`
# TODO(tfgen): create the resource(s) this data source reads (use %[1]q for unique names), then add a depends_on so the read observes them.
data "datadog_authn_mappings" "foo" {
	filter = %[1]q
	page_number = 0
	page_size = 0
}
`, uniq)
}
