// Generated by tfgen as an acceptance-test scaffold. Complete the TODOs and
// record a cassette (see below); tfgen will not overwrite this file once it exists.
package test

import (
	"context"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// TestAccDatadogDowntimeDatasource is a generated scaffold. It needs a recorded cassette to pass
// in replay mode:
//  1. Complete testAccDatasourceDatadogDowntimeConfig below: add the resource(s) that seed the data
//     this data source reads, and set the lookup/filter value(s).
//  2. Record the cassette: RECORD=true make testacc TESTARGS='-run TestAccDatadogDowntimeDatasource'
//  3. Review datadog/tests/cassettes/TestAccDatadogDowntimeDatasource.yaml (and its .freeze), then commit them so the test
//     runs in replay mode.
func TestAccDatadogDowntimeDatasource(t *testing.T) {
	t.Parallel()
	_, _, accProviders := testAccFrameworkMuxProviders(context.Background(), t)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: accProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDatasourceDatadogDowntimeConfig(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.datadog_downtime.foo", "id"),
					// TODO(tfgen): assert specific attributes once the cassette is recorded.
				),
			},
		},
	})
}

func testAccDatasourceDatadogDowntimeConfig() string {
	return `
# TODO(tfgen): create the resource this data source reads, then reference it below.
data "datadog_downtime" "foo" {
	id = "REPLACE_ME" # TODO(tfgen): set to the seeded resource's id, e.g. datadog_x.foo.id
}
`
}
