// Generated by tfgen as an acceptance-test scaffold. Complete the TODOs and
// record a cassette (see below); tfgen will not overwrite this file once it exists.
package test

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// TestAccDatadogApplicationKeysDatasource is a generated scaffold. It needs a recorded cassette to pass
// in replay mode:
//  1. Complete testAccDatasourceDatadogApplicationKeysConfig below: add the resource(s) that seed the data
//     this data source reads, and set the lookup/filter value(s).
//  2. Record the cassette: RECORD=true make testacc TESTARGS='-run TestAccDatadogApplicationKeysDatasource'
//  3. Review datadog/tests/cassettes/TestAccDatadogApplicationKeysDatasource.yaml (and its .freeze), then commit them so the test
//     runs in replay mode.
func TestAccDatadogApplicationKeysDatasource(t *testing.T) {
	t.Parallel()
	ctx, _, accProviders := testAccFrameworkMuxProviders(context.Background(), t)
	uniq := strings.ToLower(uniqueEntityName(ctx, t))

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: accProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDatasourceDatadogApplicationKeysConfig(uniq),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.datadog_application_keys.foo", "id"),
					resource.TestCheckResourceAttrSet("data.datadog_application_keys.foo", "application_keys.#"),
					// TODO(tfgen): assert specific attributes once the cassette is recorded.
				),
			},
		},
	})
}

func testAccDatasourceDatadogApplicationKeysConfig(uniq string) string {
	return fmt.Sprintf(`
# TODO(tfgen): create the resource(s) this data source reads (use %[1]q for unique names), then add a depends_on so the read observes them.
data "datadog_application_keys" "foo" {
	filter = %[1]q
	filter_created_at_end = %[1]q
	filter_created_at_start = %[1]q
	filter_owned_by = %[1]q
	include = %[1]q
	page_number = 0
	page_size = 0
}
`, uniq)
}
