// Generated by tfgen as an acceptance-test scaffold. Complete the TODOs and
// record a cassette (see below); tfgen will not overwrite this file once it exists.
package test

import (
	"context"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// TestAccDatadogRumApplicationsDatasource is a generated scaffold. It needs a recorded cassette to pass
// in replay mode:
//  1. Complete testAccDatasourceDatadogRumApplicationsConfig below: add the resource(s) that seed the data
//     this data source reads, and set the lookup/filter value(s).
//  2. Record the cassette: RECORD=true make testacc TESTARGS='-run TestAccDatadogRumApplicationsDatasource'
//  3. Review datadog/tests/cassettes/TestAccDatadogRumApplicationsDatasource.yaml (and its .freeze), then commit them so the test
//     runs in replay mode.
func TestAccDatadogRumApplicationsDatasource(t *testing.T) {
	t.Parallel()
	_, _, accProviders := testAccFrameworkMuxProviders(context.Background(), t)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: accProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDatasourceDatadogRumApplicationsConfig(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.datadog_rum_applications.foo", "id"),
					resource.TestCheckResourceAttrSet("data.datadog_rum_applications.foo", "rum_applications.#"),
					// TODO(tfgen): assert specific attributes once the cassette is recorded.
				),
			},
		},
	})
}

func testAccDatasourceDatadogRumApplicationsConfig() string {
	return `
# TODO(tfgen): create the resource(s) this data source reads, then add a depends_on so the read observes them.
data "datadog_rum_applications" "foo" {
	id = "56dcdaf9-5c49-482a-97e0-273dd490ef0b"
}
`
}
